Repository OpenRA/OpenRA, pull requests merged in 2018-08, with the labels that each got.

#15429 Remove duplicate line from V19.Husk
  mods/ra/rules/civilian.yaml
Labels: PR: Needs +2

#15452 Allow to use non tileset specific build-valid.
  OpenRA.Mods.Common/Orders/PlaceBuildingOrderGenerator.cs
Labels: PR: Needs +2

#15458 Remove all uses of Server.ExternalPort
  launch-dedicated.cmd
  launch-dedicated.sh
  packaging/freebsd/openra
Labels: PR: For stable, PR: Needs +2

#15470 Revert ShpTD empty space trimming.
  OpenRA.Mods.Common/SpriteLoaders/ShpTDLoader.cs
Labels: PR: For stable, PR: Needs +2

#15463 Fix tree owners in TD (for real this time)
  mods/cnc/maps/axis-of-advance.oramap
  mods/cnc/maps/riverside-frontline.oramap
  mods/cnc/maps/tiberian-falls.oramap
  mods/cnc/maps/valley-of-gold.oramap
Labels: PR: For stable

#15465 Disable the threaded renderer on Windows.
  OpenRA.Game/Settings.cs
  OpenRA.Platforms.Default/Sdl2PlatformWindow.cs
Labels: PR: For stable, PR: Needs +2

#15466 Clear selection when a text field's contents is changed programatically.
  OpenRA.Mods.Common/Widgets/TextFieldWidget.cs
Labels: PR: For stable, PR: Needs +2

#15451 Fixed backwards animation playback.
  OpenRA.Game/Graphics/Animation.cs
Labels: PR: Needs +2

#15459 TS: Aircrafts land instantly to reload their ammo.
  OpenRA.Mods.Common/Activities/Air/Land.cs
Labels: PR: Needs +2

#15469 Hide the Ready checkbox when a spectator transfers away Admin.
  OpenRA.Mods.Common/Widgets/Logic/Lobby/LobbyLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Lobby/LobbyUtils.cs
Labels: PR: For stable, PR: Needs +2

#15440 Fix AI idle harvester handling
  OpenRA.Mods.Common/AI/AIHarvesterManager.cs
  OpenRA.Mods.Common/AI/HackyAI.cs
Labels: PR: For stable, PR: Needs +2

#15473 Fix death sequences of Chan, Einstein, and Delphi
  mods/ra/sequences/infantry.yaml
Labels: PR: For stable

#15483 Fix issueing superfluous `difficulty` lobby command from mission browser
  OpenRA.Mods.Common/Widgets/Logic/MissionBrowserLogic.cs
Labels: PR: For stable, PR: Needs +2

#15481 Resolve conflicts between actor and API names (Radar)
  mods/cnc/maps/nod05/map.yaml
  mods/cnc/maps/nod05/nod05.lua
  mods/cnc/maps/nod06a/map.yaml
  mods/cnc/maps/nod06a/nod06a.lua
  mods/ra/maps/allies-06a/allies06a.lua
  mods/ra/maps/allies-06a/map.yaml
  mods/ra/maps/allies-06b/allies06b.lua
  mods/ra/maps/allies-06b/map.yaml
  mods/ra/maps/soviet-04a/map.yaml
  mods/ra/maps/soviet-04a/soviet04a-reinforcements_teams.lua
  mods/ra/maps/soviet-04a/soviet04a.lua
  mods/ra/maps/soviet-04b/map.yaml
  mods/ra/maps/soviet-04b/soviet04b-reinforcements_teams.lua
  mods/ra/maps/soviet-04b/soviet04b.lua
  mods/ra/maps/soviet-05/map.yaml
  mods/ra/maps/soviet-05/soviet05.lua
Labels: PR: For stable, PR: Needs +2

#15480 Revert parts of "D2k - Limit Production to Atreides and Ordos Palaces" on prep-1807
  mods/d2k/rules/structures.yaml
Labels: PR: For stable, PR: Needs +2

#15499 Fix badge label padding.
  OpenRA.Mods.Common/Widgets/Logic/PlayerProfileLogic.cs
Labels: PR: For stable

#15500 (RA Balance) Revert ranger change and dial back missile sub damage
  mods/ra/rules/vehicles.yaml
  mods/ra/weapons/missiles.yaml
Labels: PR: For stable, PR: Needs +2

#15506 Revert "Add "Restart" button for multiplayer replays"
  OpenRA.Mods.Common/Widgets/Logic/Ingame/IngameMenuLogic.cs
Labels: PR: For stable

#15505 Fix husks not updating targetable positions on teleport
  OpenRA.Game/Actor.cs
  OpenRA.Mods.Common/Traits/Husk.cs
Labels: PR: For stable, PR: Needs +2

#15510 Fix Cargo>EjectOnDeath crash with multipile INotifyBlockingMove
  OpenRA.Mods.Common/Traits/Cargo.cs
Labels: PR: Needs +2

#15528 Fix GivesExperienceModifier not working
  OpenRA.Mods.Common/Traits/GivesExperience.cs
Labels: PR: Needs +2

#15519 Ensure that TLS 1.2 is enabled for web downloads.
  OpenRA.Game/Download.cs
Labels: PR: For stable, PR: Needs +2

#15514 Add Engine.SupportDir argument.
  OpenRA.Game/Game.cs
  OpenRA.Game/Platform.cs
  OpenRA.Server/Program.cs
Labels: PR: For stable, PR: Needs +2

#15535 Revert "Re-active Edge-Scrolling for inverted Mouse-Scrolling"
  OpenRA.Mods.Common/Widgets/ViewportControllerWidget.cs
Labels: PR: For stable, PR: Needs +2

#15550 fix threadedRenderer context creation logic
  OpenRA.Platforms.Default/Sdl2PlatformWindow.cs
Labels: PR: For stable, PR: Needs +2

#15557 Fix crash when a non-admin player mouses over a bot in the lobby.
  OpenRA.Mods.Common/Widgets/Logic/Lobby/LobbyLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Lobby/LobbyUtils.cs
Labels: PR: For stable

#15558 Fix compiler warnings on Linux
  OpenRA.Game/OpenRA.Game.csproj
  OpenRA.Mods.Cnc/OpenRA.Mods.Cnc.csproj
  OpenRA.Mods.Common/OpenRA.Mods.Common.csproj
  OpenRA.Mods.D2k/OpenRA.Mods.D2k.csproj
  OpenRA.Platforms.Default/OpenRA.Platforms.Default.csproj
  OpenRA.Server/OpenRA.Server.csproj
  OpenRA.Test/OpenRA.Test.csproj
  OpenRA.Utility/OpenRA.Utility.csproj
Labels: PR: For stable
