Repository OpenRA/OpenRA, pull requests merged in 2018-10, with the labels that each got.

#15464 Updated CPos struct to use bit field for all properties.
  OpenRA.Game/CPos.cs
  OpenRA.Game/Map/MapPreview.cs
  OpenRA.Game/Network/Order.cs
  OpenRA.Game/Network/OrderIO.cs
  OpenRA.Test/OpenRA.Game/CPosTest.cs
  OpenRA.Test/OpenRA.Game/OrderTest.cs
  OpenRA.Test/OpenRA.Test.csproj
Labels: PR: Needs +2

#15643 Properly end capturing during an owner change
  OpenRA.Mods.Common/Activities/ExternalCaptureActor.cs
  OpenRA.Mods.Common/Traits/ExternalCapturable.cs
Labels: PR: For stable, PR: Needs +2

#15677 Fix incorrect sampler index check
  glsl/combined.frag
Labels: PR: For stable

#15563 [INSTALL.md] Converting lists (of dependencies) to install commands; adding dep install commands for additional distros; updating install/usage information
  INSTALL.md
Labels: PR: Needs +2

#15679 Add a proper exception when creating an actor with an invalid owner in Lua
  OpenRA.Mods.Common/Scripting/Global/ActorGlobal.cs
Labels: PR: Needs +2

#15666 Correct the amount of money found in crates in allies03
  mods/ra/maps/allies-03a/rules.yaml
  mods/ra/maps/allies-03b/rules.yaml
Labels: PR: Needs +2

#15628 Fix game crash when adding a player with a removed owner selected
  OpenRA.Mods.Common/Traits/World/EditorActorLayer.cs
  OpenRA.Mods.Common/Widgets/Logic/Editor/ActorSelectorLogic.cs
Labels: PR: Needs +2

#15652 Refactored cursors.yaml to use palettes from rules.
  OpenRA.Game/Graphics/CursorProvider.cs
  OpenRA.Game/Traits/TraitsInterfaces.cs
  OpenRA.Mods.Common/Traits/World/PaletteFromFile.cs
  OpenRA.Mods.Common/Traits/World/PaletteFromPng.cs
  mods/cnc/cursors.yaml
  mods/cnc/rules/palettes.yaml
  mods/d2k/cursors.yaml
  mods/d2k/rules/palettes.yaml
  mods/modcontent/cursors.yaml
  mods/modcontent/mod.yaml
  mods/modcontent/rules.yaml
  mods/ra/cursors.yaml
  mods/ra/rules/palettes.yaml
  mods/ts/cursors.yaml
  mods/ts/rules/palettes.yaml
Labels: PR: Needs +2

#15582 Add Allies08a
  mods/ra/maps/allies-08a/allies08a-AI.lua
  mods/ra/maps/allies-08a/allies08a.lua
  mods/ra/maps/allies-08a/map.bin
  mods/ra/maps/allies-08a/map.png
  mods/ra/maps/allies-08a/map.yaml
  mods/ra/maps/allies-08a/rules.yaml
  mods/ra/missions.yaml
Labels: PR: Needs +2

#15624 Add Aircraft Takeoff & Landing Sounds (Planes)
  OpenRA.Mods.Common/Activities/Air/Fly.cs
  OpenRA.Mods.Common/Activities/Air/HeliFly.cs
  OpenRA.Mods.Common/Activities/Air/HeliLand.cs
  OpenRA.Mods.Common/Activities/Air/Land.cs
  OpenRA.Mods.Common/OpenRA.Mods.Common.csproj
  OpenRA.Mods.Common/Traits/Air/Aircraft.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20180923/ChangeTakeOffSoundAndLandingSound.cs
  mods/ts/rules/aircraft.yaml
Labels: PR: Needs +2

#15669 Move TerrainRenderer to a mod-defined trait.
  OpenRA.Game/Graphics/WorldRenderer.cs
  OpenRA.Game/OpenRA.Game.csproj
  OpenRA.Game/Traits/TraitsInterfaces.cs
  OpenRA.Mods.Common/OpenRA.Mods.Common.csproj
  OpenRA.Mods.Common/Traits/World/TerrainRenderer.cs
  mods/cnc/rules/world.yaml
  mods/d2k/rules/world.yaml
  mods/ra/rules/world.yaml
  mods/ts/rules/world.yaml
Labels: PR: Needs +2

#15723 Make CrateAction conditional
  OpenRA.Mods.Common/Traits/Crates/CrateAction.cs
Labels: PR: Needs +2

#15694 Reorganize RA missions list
  mods/ra/missions.yaml
Labels: PR: Needs +2

#15681 Prevent ReturnToBase from causing a divide by zero crash
  OpenRA.Mods.Common/Activities/Air/ReturnToBase.cs
Labels: PR: For stable, PR: Needs +2

#15757 Proper usage of IHealthInfo.
  OpenRA.Mods.Common/Warheads/DamageWarhead.cs
Labels: PR: Needs +2
