Repository OpenRA/OpenRA, pull requests merged in 2018-12, with the labels that each got.

#15836 Improve Hind visibility
  mods/ra/bits/hind.shp
Labels: PR: Needs +2

#15889 Prevent multiple Transforms from triggering in the same tick.
  OpenRA.Game/Actor.cs
  OpenRA.Mods.Cnc/Traits/ConyardChronoReturn.cs
  OpenRA.Mods.Common/Activities/Transform.cs
Labels: PR: For stable

#15885 Fix queued EnterTransport unload glitch.
  OpenRA.Mods.Common/Activities/EnterTransport.cs
Labels: PR: For stable, PR: Needs +2

#15890 Fix production tooltip padding.
  OpenRA.Mods.Common/Widgets/Logic/Ingame/ProductionTooltipLogic.cs
  mods/cnc/chrome/tooltips.yaml
  mods/common/chrome/tooltips.yaml
  mods/d2k/chrome/tooltips.yaml
Labels: PR: Needs +2

#15835 Remove airstrike/paradrop beacon when the whole squad is shot down
  OpenRA.Mods.Common/Traits/SupportPowers/AirstrikePower.cs
  OpenRA.Mods.Common/Traits/SupportPowers/ParatroopersPower.cs
Labels: PR: Needs +2

#15893 Allow MadTank Detonate order to be queued.
  OpenRA.Mods.Cnc/Traits/MadTank.cs
Labels: PR: Needs +2

#15892 Remove legacy workaround that crashes modern Mono.
  OpenRA.Game/Graphics/Palette.cs
Labels: PR: Needs +2

#15894 Add a --utility argument to the AppImages.
  packaging/linux/AppRun.in
  packaging/linux/buildpackage.sh
  packaging/linux/openra-utility.appimage.in
Labels: PR: Needs +2

#15907 RA balance change for December 2018
  mods/ra/rules/defaults.yaml
Labels: PR: Needs +2

#15927 Fix "game is full" error when the game is not full.
  OpenRA.Game/Server/Server.cs
Labels: PR: Needs +2

#15921 Split off CaptureManagerBotModule from HackyAI
  OpenRA.Mods.Common/AI/HackyAI.cs
  OpenRA.Mods.Common/OpenRA.Mods.Common.csproj
  OpenRA.Mods.Common/Traits/BotModules/CaptureManagerBotModule.cs
  OpenRA.Mods.Common/TraitsInterfaces.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20180923/ExtractHackyAIModules.cs
Labels: PR: Is Dependency, PR: Needs +2

#15924 Fix cell-out-of-bounds crashes in BuildableTerrainLayer.
  OpenRA.Mods.D2k/Traits/World/BuildableTerrainLayer.cs
Labels: PR: Needs +2

#15844 Allow forcing sprite body Z position to ground
  OpenRA.Mods.Common/Traits/Render/WithSpriteBody.cs
Labels: PR: Needs +2

#15583 Add Allies08b
  mods/ra/maps/allies-08b/allies08b-AI.lua
  mods/ra/maps/allies-08b/allies08b.lua
  mods/ra/maps/allies-08b/map.bin
  mods/ra/maps/allies-08b/map.png
  mods/ra/maps/allies-08b/map.yaml
  mods/ra/maps/allies-08b/rules.yaml
  mods/ra/missions.yaml
Labels: PR: Needs +2

#15935 Change existing husks to neutral when owner loses.
  mods/ra/rules/defaults.yaml
Labels: PR: Needs +2

#15936 Fix QuantizeFacing returning values >= numFacings.
  OpenRA.Mods.Common/Util.cs
Labels: PR: Needs +2

#15360 Throttles for notification sounds so rapid user actions do not produce annoying sounds
  OpenRA.Game/GameRules/SoundInfo.cs
  mods/cnc/audio/notifications.yaml
  mods/d2k/audio/notifications.yaml
  mods/ra/audio/notifications.yaml
  mods/ts/audio/speech-generic.yaml
Labels: PR: Needs +2

#15915 Fix player score not updating while game info screen is visible
  OpenRA.Mods.Common/Widgets/Logic/Ingame/GameInfoStatsLogic.cs
Labels: PR: Needs +2

#15419 Improve RenderShroudCircle
  OpenRA.Mods.Cnc/Traits/Render/RenderShroudCircle.cs
Labels: PR: Needs +2

#15944 Make Concrete under buildings indestructible.
  OpenRA.Mods.D2k/Traits/World/BuildableTerrainLayer.cs
Labels: PR: Needs +2

#15704 Fix replay timer not showing correct percentage complete
  OpenRA.Game/GameInformation.cs
  OpenRA.Game/Network/ReplayConnection.cs
  OpenRA.Game/World.cs
  OpenRA.Mods.Common/Widgets/Logic/Ingame/GameTimerLogic.cs
Labels: PR: Needs +2

#15895 Add facing support to GravityBomb
  OpenRA.Mods.Common/Projectiles/GravityBomb.cs
Labels: PR: Needs +2

#15933 QueryRemoteMapDetails sets each maps's status now correctly
  OpenRA.Game/Map/MapCache.cs
Labels: PR: Needs +2

#15947 Revert turret realignment before undeploy
  OpenRA.Mods.Common/Activities/UndeployForGrantedCondition.cs
  OpenRA.Mods.Common/Activities/WaitForTurretAlignment.cs
  OpenRA.Mods.Common/OpenRA.Mods.Common.csproj
  OpenRA.Mods.Common/Traits/Turreted.cs
Labels: PR: Needs +2

#15918 Fix LandOnCondition causing stopping after changing altitude.
  OpenRA.Mods.Common/Traits/Air/Aircraft.cs
Labels: PR: Needs +2

#15870 Add Tiberian Dawn Nod Campaign 10a
  AUTHORS
  mods/cnc/maps/nod10a/map.bin
  mods/cnc/maps/nod10a/map.png
  mods/cnc/maps/nod10a/map.yaml
  mods/cnc/maps/nod10a/nod10a.lua
  mods/cnc/maps/nod10a/rules.yaml
  mods/cnc/missions.yaml
Labels: PR: Needs +2

#15396 Ant Mission 1
  mods/ra/maps/ant-01/ant-01.lua
  mods/ra/maps/ant-01/ant-attack.lua
  mods/ra/maps/ant-01/map.bin
  mods/ra/maps/ant-01/map.png
  mods/ra/maps/ant-01/map.yaml
  mods/ra/maps/ant-01/rules.yaml
  mods/ra/missions.yaml
  mods/ra/rules/infantry.yaml
  mods/ra/sequences/infantry.yaml
  mods/ra/weapons/other.yaml
Labels: PR: Needs +2

#15951 Revert "Fix QuantizeFacing returning values >= numFacings."
  OpenRA.Mods.Common/Util.cs
Labels: PR: Needs +2
