Repository OpenRA/OpenRA, pull requests merged in 2018-09, with the labels that each got.

#15598 Enable Airfields for AI as Ukraine
  mods/ra/rules/ai.yaml
Labels: PR: For stable, PR: Needs +2

#15599 Add a Desc for Buildable.BuildPaletteOrder.
  OpenRA.Mods.Common/Traits/Buildable.cs
Labels: PR: Needs +2

#15596 Allow deploy orders to be queued from the command bar.
  OpenRA.Mods.Cnc/Traits/MadTank.cs
  OpenRA.Mods.Cnc/Traits/Minelayer.cs
  OpenRA.Mods.Common/Traits/Air/Aircraft.cs
  OpenRA.Mods.Common/Traits/Attack/AttackSuicides.cs
  OpenRA.Mods.Common/Traits/Cargo.cs
  OpenRA.Mods.Common/Traits/Conditions/GrantConditionOnDeploy.cs
  OpenRA.Mods.Common/Traits/Transforms.cs
  OpenRA.Mods.Common/TraitsInterfaces.cs
  OpenRA.Mods.Common/Widgets/Logic/Ingame/CommandBarLogic.cs
Labels: PR: Needs +2

#15593 Disable sync reports when we know we won't need them.
  OpenRA.Game/Network/OrderManager.cs
Labels: PR: Needs +2

#15522 Allow mods to determine associated SuperPower from SelectGenericPowerTarget
  OpenRA.Mods.Common/Traits/SupportPowers/SupportPowerManager.cs
Labels: PR: Needs +2

#15588 Fix: Display progress message properly when download size missing (#1)
  OpenRA.Mods.Common/Widgets/Logic/Installation/DownloadPackageLogic.cs
Labels: PR: Needs +2

#15594 Revert RA Grenadier explosion DamageSource.
  mods/ra/rules/infantry.yaml
Labels: PR: For stable, PR: Needs +2

#15611 Fix display of progress text in Advanced Install when total file size…
  OpenRA.Mods.Common/Widgets/Logic/Installation/DownloadPackageLogic.cs
Labels: PR: Needs +2

#15610 Added destructible concrete for Dune 2000
  OpenRA.Mods.D2k/OpenRA.Mods.D2k.csproj
  OpenRA.Mods.D2k/Traits/World/BuildableTerrainLayer.cs
  OpenRA.Mods.D2k/Warheads/DamagesConcreteWarhead.cs
  mods/d2k/weapons/debris.yaml
  mods/d2k/weapons/largeguns.yaml
  mods/d2k/weapons/missiles.yaml
  mods/d2k/weapons/other.yaml
  mods/d2k/weapons/smallguns.yaml
Labels: PR: Needs +2

#15565 Fix game crashes when no maps are available to load
  OpenRA.Game/Map/MapCache.cs
  OpenRA.Mods.Common/Widgets/Logic/MainMenuLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/MultiplayerLogic.cs
Labels: PR: Needs +2

#15634 Disable the restart button on dedicated servers
  OpenRA.Mods.Common/Widgets/Logic/Ingame/IngameMenuLogic.cs
Labels: PR: For stable

#15635 Revert macOS dark mode support
  packaging/osx/buildpackage.sh
  thirdparty/fetch-thirdparty-deps-osx.sh
Labels: PR: For stable

#15549 Soviet Soldier Volkov & Chitzkoi fully ported
  AUTHORS
  OpenRA.sln
  mods/ra/maps/soviet-soldier-volkov-n-chitzkoi/map.bin
  mods/ra/maps/soviet-soldier-volkov-n-chitzkoi/map.png
  mods/ra/maps/soviet-soldier-volkov-n-chitzkoi/map.yaml
  mods/ra/maps/soviet-soldier-volkov-n-chitzkoi/notifications.yaml
  mods/ra/maps/soviet-soldier-volkov-n-chitzkoi/rules.yaml
  mods/ra/maps/soviet-soldier-volkov-n-chitzkoi/scu35ea-AI.lua
  mods/ra/maps/soviet-soldier-volkov-n-chitzkoi/scu35ea.lua
  mods/ra/maps/soviet-soldier-volkov-n-chitzkoi/weapons.yaml
Labels: PR: Needs +2

#15367 Made Valued optional for traits who do not require it.
  OpenRA.Mods.Common/Activities/Repair.cs
  OpenRA.Mods.Common/Traits/GainsExperience.cs
  OpenRA.Mods.Common/Traits/SpawnActorsOnSell.cs
  OpenRA.Mods.Common/Widgets/Logic/Ingame/ProductionTooltipLogic.cs
Labels: PR: Needs +2

#15639 Prevent units from gaining more experience than MaxLevel requires
  OpenRA.Mods.Common/Traits/GainsExperience.cs
Labels: PR: For stable

#15410 Change menu cancel buttons to back
  mods/cnc/chrome/mapchooser.yaml
  mods/common/chrome/map-chooser.yaml
  mods/common/chrome/replaybrowser.yaml
Labels: PR: Needs +2

#15303 Add GrantConditionOnProduction
  OpenRA.Mods.Common/OpenRA.Mods.Common.csproj
  OpenRA.Mods.Common/Traits/Conditions/GrantConditionOnProduction.cs
Labels: PR: Needs +2

#15378 Refactored Health usage to IHealth.
  OpenRA.Game/Traits/TraitsInterfaces.cs
  OpenRA.Mods.Common/AI/AttackOrFleeFuzzy.cs
  OpenRA.Mods.Common/AI/SupportPowerDecision.cs
  OpenRA.Mods.Common/Activities/CaptureActor.cs
  OpenRA.Mods.Common/Activities/Repair.cs
  OpenRA.Mods.Common/Activities/RepairBuilding.cs
  OpenRA.Mods.Common/Activities/Sell.cs
  OpenRA.Mods.Common/Activities/Transform.cs
  OpenRA.Mods.Common/Lint/CheckHitShapes.cs
  OpenRA.Mods.Common/Scripting/Properties/HealthProperties.cs
  OpenRA.Mods.Common/Traits/Buildings/GroundLevelBridge.cs
  OpenRA.Mods.Common/Traits/Buildings/RepairableBuilding.cs
  OpenRA.Mods.Common/Traits/Captures.cs
  OpenRA.Mods.Common/Traits/CombatDebugOverlay.cs
  OpenRA.Mods.Common/Traits/Conditions/GrantConditionOnDamageState.cs
  OpenRA.Mods.Common/Traits/Crates/HealUnitsCrateAction.cs
  OpenRA.Mods.Common/Traits/DamagedByTerrain.cs
  OpenRA.Mods.Common/Traits/Explodes.cs
  OpenRA.Mods.Common/Traits/ExplosionOnDamageTransition.cs
  OpenRA.Mods.Common/Traits/Health.cs
  OpenRA.Mods.Common/Traits/KillsSelf.cs
  OpenRA.Mods.Common/Traits/Power/ScalePowerWithHealth.cs
  OpenRA.Mods.Common/Traits/Repairable.cs
  OpenRA.Mods.Common/Traits/RepairableNear.cs
  OpenRA.Mods.Common/Traits/SelfHealing.cs
  OpenRA.Mods.Common/Traits/Sellable.cs
  OpenRA.Mods.Common/Traits/SpawnActorsOnSell.cs
  OpenRA.Mods.Common/Warheads/CreateEffectWarhead.cs
  OpenRA.Mods.Common/Warheads/HealthPercentageDamageWarhead.cs
  OpenRA.Mods.Common/Warheads/SpreadDamageWarhead.cs
Labels: PR: Needs +2

#15525 Allow usage of different palette for WithSpriteTurret
  OpenRA.Mods.Common/Traits/Render/WithSpriteTurret.cs
Labels: PR: Needs +2

#15390 ClickSound and ClickDisabledSound and ChatLine are optional ui sounds.
  OpenRA.Mods.Common/Widgets/ButtonWidget.cs
  OpenRA.Mods.Common/Widgets/DropDownButtonWidget.cs
  OpenRA.Mods.Common/Widgets/Logic/Ingame/Hotkeys/CycleProductionActorsHotkeyLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Ingame/IngameChatLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Ingame/MenuButtonsChromeLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Ingame/ObserverStatsLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Lobby/LobbyLogic.cs
  OpenRA.Mods.Common/Widgets/ProductionTabsWidget.cs
  OpenRA.Mods.Common/Widgets/ScrollPanelWidget.cs
  mods/cnc/metrics.yaml
  mods/d2k/metrics.yaml
  mods/modcontent/metrics.yaml
  mods/ra/metrics.yaml
  mods/ts/metrics.yaml
Labels: PR: Needs +2

#15336 Support loading sprites from PNG sheets with embedded frame metadata
  OpenRA.Game/FileFormats/PngLoader.cs
  OpenRA.Game/OpenRA.Game.csproj
  OpenRA.Mods.Common/FileFormats/Png.cs
  OpenRA.Mods.Common/OpenRA.Mods.Common.csproj
  OpenRA.Mods.Common/SpriteLoaders/PngSheetLoader.cs
  OpenRA.Mods.Common/Traits/World/PaletteFromPng.cs
  OpenRA.Mods.Common/UtilityCommands/ConvertPngToShpCommand.cs
  OpenRA.Mods.Common/UtilityCommands/PngSheetExportMetadataCommand.cs
  OpenRA.Mods.Common/UtilityCommands/PngSheetImportMetadataCommand.cs
Labels: PR: Needs +2

#15479 Changed SubCell to byte.
  OpenRA.Game/Exts.cs
  OpenRA.Game/Network/Order.cs
  OpenRA.Game/Traits/TraitsInterfaces.cs
  OpenRA.Mods.Common/ActorInitializer.cs
  OpenRA.Mods.Common/Traits/World/ActorMap.cs
  OpenRA.Mods.Common/Traits/World/EditorActorLayer.cs
  OpenRA.Mods.Common/UtilityCommands/ImportLegacyMapCommand.cs
Labels: PR: Needs +2
