Repository OpenRA/OpenRA, pull requests merged in 2018-11, with the labels that each got.

#15742 Fix target lines still being visible after an owner change
  OpenRA.Mods.Common/Traits/Render/DrawLineToTarget.cs
Labels: PR: Needs +2

#15753 Add MPSpawnUnits>BaseActorOffset
  OpenRA.Mods.Common/Traits/World/MPStartUnits.cs
  OpenRA.Mods.Common/Traits/World/SpawnMPUnits.cs
Labels: PR: Needs +2

#15754 Limit samplers to 8 in combined.frag.
  OpenRA.Game/Graphics/SpriteRenderer.cs
  glsl/combined.frag
Labels: PR: For stable, PR: Needs +2

#15730 Move Moneycrate to campaign-rules.yaml
  mods/ra/maps/allies-03a/rules.yaml
  mods/ra/maps/allies-03b/rules.yaml
  mods/ra/maps/allies-04/rules.yaml
  mods/ra/maps/soviet-02b/rules.yaml
  mods/ra/maps/soviet-06a/rules.yaml
  mods/ra/maps/soviet-soldier-volkov-n-chitzkoi/rules.yaml
  mods/ra/rules/campaign-rules.yaml
Labels: PR: Needs +2

#15770 Fix SubCell indexing in Map.CenterOfSubCell and MapGrid.OffsetOfSubCell
  OpenRA.Game/Map/Map.cs
  OpenRA.Game/Map/MapGrid.cs
Labels: PR: Needs +2

#15749 Remove unused waypoints from Soviet02a
  mods/ra/maps/soviet-02a/map.yaml
  mods/ra/maps/soviet-02a/soviet02a.lua
Labels: PR: Needs +2

#15764 Allow player to add a "priority unit" to production queue
  OpenRA.Game/Network/Order.cs
  OpenRA.Mods.Common/Traits/Player/ParallelProductionQueue.cs
  OpenRA.Mods.Common/Traits/Player/ProductionQueue.cs
  OpenRA.Mods.Common/Widgets/ProductionPaletteWidget.cs
Labels: PR: Needs +2

#15782 Draw target lines for allied players and observers
  OpenRA.Mods.Common/Traits/Render/DrawLineToTarget.cs
Labels: PR: Needs +2

#15745 Replicate palette high bits into the low bits
  OpenRA.Game/Graphics/Palette.cs
Labels: PR: Needs +2

#15791 Remove unused HarvesterEnemyAvoidanceRadius
  OpenRA.Mods.Common/AI/HackyAI.cs
Labels: PR: Needs +2

#15802 Revert granting condition from HackyAI
  OpenRA.Mods.Common/AI/HackyAI.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20180923/AddHarvesterBotModule.cs
  mods/cnc/rules/ai.yaml
  mods/d2k/rules/ai.yaml
  mods/ra/maps/fort-lonestar/rules.yaml
  mods/ra/rules/ai.yaml
  mods/ts/rules/ai.yaml
Labels: PR: Needs +2

#15806 Check for null in Turreted.StopAiming
  OpenRA.Mods.Common/Traits/Turreted.cs
Labels: PR: Needs +2

#15702 Add RequiresForceFire to Demolition
  OpenRA.Mods.Common/Traits/Demolition.cs
Labels: PR: Needs +2

#15828 Remove unused tileset update/save code.
  OpenRA.Game/Map/TileSet.cs
  OpenRA.Mods.Common/OpenRA.Mods.Common.csproj
  OpenRA.Mods.Common/UtilityCommands/FixClassicTilesets.cs
Labels: PR: Needs +2

#15818 Show team/spawn widget after admin transfer.
  OpenRA.Mods.Common/Widgets/Logic/Lobby/LobbyUtils.cs
Labels: PR: For stable, PR: Needs +2

#15823 Defer setting slot on client to completeConnection
  OpenRA.Game/Server/Server.cs
Labels: PR: For stable

#15838 Fix AttackMove crash
  OpenRA.Mods.Common/Traits/AttackMove.cs
Labels: PR: For stable, PR: Needs +2

#15811 Made Turreted PausableConditionalTrait
  OpenRA.Mods.Common/Traits/Turreted.cs
Labels: PR: Is Dependency, PR: Needs +2

#15815 Added smudge chance.
  OpenRA.Mods.Common/Warheads/LeaveSmudgeWarhead.cs
Labels: PR: Needs +2

#15045 Correctly handle Production traits disabled by condition.
  OpenRA.Mods.Common/Traits/Player/ProductionQueue.cs
  OpenRA.Mods.Common/Traits/ProductionQueueFromSelection.cs
  OpenRA.Mods.Common/Widgets/Logic/Ingame/ProductionTabsLogic.cs
  OpenRA.Mods.Common/Widgets/ProductionTabsWidget.cs
Labels: PR: Needs +2

#15392 Fixing several ShellCheck warnings
  launch-dedicated.sh
  launch-game.sh
  packaging/linux/buildpackage.sh
  packaging/osx/buildpackage.sh
  packaging/package-all.sh
  packaging/source/buildpackage.sh
  packaging/update-wiki.sh
  packaging/windows/buildpackage.sh
  thirdparty/fetch-geoip-db.sh
  thirdparty/fetch-thirdparty-deps-osx.sh
  thirdparty/fetch-thirdparty-deps-windows.sh
  thirdparty/fetch-thirdparty-deps.sh
Labels: PR: Needs +2

#15551 Editor feature to edit actor ID and owner.
  OpenRA.Mods.Common/EditorBrushes/EditorDefaultBrush.cs
  OpenRA.Mods.Common/OpenRA.Mods.Common.csproj
  OpenRA.Mods.Common/Traits/World/EditorActorLayer.cs
  OpenRA.Mods.Common/Traits/World/EditorActorPreview.cs
  OpenRA.Mods.Common/Widgets/EditorViewportControllerWidget.cs
  OpenRA.Mods.Common/Widgets/Logic/Editor/ActorEditLogic.cs
  mods/cnc/chrome/editor.yaml
  mods/common/chrome/editor.yaml
Labels: PR: Fixup requested, PR: Needs +2

#15830 Fix bot module plumbing
  OpenRA.Game/Traits/TraitsInterfaces.cs
  OpenRA.Mods.Common/AI/BotOrderManager.cs
  OpenRA.Mods.Common/AI/DummyAI.cs
  OpenRA.Mods.Common/AI/HackyAI.cs
  OpenRA.Mods.Common/OpenRA.Mods.Common.csproj
  OpenRA.Mods.Common/Traits/BotModules/HarvesterBotModule.cs
  OpenRA.Mods.Common/TraitsInterfaces.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20180923/AddBotOrderManager.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20180923/ExtractHackyAIModules.cs
  OpenRA.Mods.Common/UpdateRules/UpdatePath.cs
  mods/cnc/rules/ai.yaml
  mods/d2k/rules/ai.yaml
  mods/ra/rules/ai.yaml
  mods/ts/rules/ai.yaml
Labels: PR: Is Dependency, PR: Needs +2

#14875 Implement exponentially scaled slider widget
  AUTHORS
  OpenRA.Mods.Common/OpenRA.Mods.Common.csproj
  OpenRA.Mods.Common/Widgets/ExponentialSliderWidget.cs
  OpenRA.Mods.Common/Widgets/SliderWidget.cs
  mods/cnc/chrome/lobby-music.yaml
  mods/cnc/chrome/music.yaml
  mods/cnc/chrome/settings.yaml
  mods/common/chrome/lobby-music.yaml
  mods/common/chrome/musicplayer.yaml
  mods/common/chrome/settings.yaml
Labels: PR: Needs +2

#15786 Convert AISupportPowerManager to module
  OpenRA.Mods.Common/AI/HackyAI.cs
  OpenRA.Mods.Common/OpenRA.Mods.Common.csproj
  OpenRA.Mods.Common/Traits/BotModules/BotModuleLogic/SupportPowerDecision.cs
  OpenRA.Mods.Common/Traits/BotModules/SupportPowerBotModule.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20180923/ExtractHackyAIModules.cs
  mods/cnc/rules/ai.yaml
  mods/d2k/rules/ai.yaml
  mods/ra/rules/ai.yaml
Labels: PR: Is Dependency, PR: Needs +2

#15856 Fix FindResources aborting to early
  OpenRA.Mods.Common/Activities/FindResources.cs
Labels: PR: Needs +2
