Repository OpenRA/OpenRA, pull requests merged in 2019-11, with the labels that each got.

#17233 Prevent showing wall connections in unexplored terrain
  OpenRA.Mods.Common/Orders/PlaceBuildingOrderGenerator.cs
  OpenRA.Mods.Common/Traits/Buildings/BuildingUtils.cs
  OpenRA.Mods.Common/Traits/Player/PlaceBuilding.cs
Labels: PR: Needs +2

#17166 Prevent chronoshifting an empty selection
  OpenRA.Mods.Cnc/Traits/SupportPowers/ChronoshiftPower.cs
Labels: PR: Needs +2

#17263 Remove landing behaviour from force-move orders on selectable buildings.
  OpenRA.Mods.Common/Traits/Air/Aircraft.cs
Labels: PR: For stable, PR: Needs +2

#17281 Cache IPathFinder in Mobile at creation
  OpenRA.Mods.Common/Activities/Move/Move.cs
  OpenRA.Mods.Common/Traits/Mobile.cs
Labels: PR: Needs +2

#17236 Add PlaceDefenseTowardsEnemyChance trait to BaseBuilderBotModule
  OpenRA.Mods.Common/Traits/BotModules/BaseBuilderBotModule.cs
  OpenRA.Mods.Common/Traits/BotModules/BotModuleLogic/BaseBuilderQueueManager.cs
Labels: PR: Needs +2

#17240 Show dialogue only when there are unsaved changes
  OpenRA.Mods.Common/Traits/World/EditorActionManager.cs
  OpenRA.Mods.Common/Widgets/Logic/Ingame/IngameMenuLogic.cs
Labels: PR: Needs +2

#17305 Allow GrantCondition to grant conditions permanently.
  OpenRA.Mods.Common/Traits/Conditions/GrantCondition.cs
Labels: PR: Needs +2

#17276 Fix MCV Manager glitch when restrict building area is enabled.
  OpenRA.Mods.Common/Traits/BotModules/McvManagerBotModule.cs
Labels: PR: Needs +2

#17150 Fix actors returning fire at invisible attackers
  OpenRA.Mods.Common/Traits/AutoTarget.cs
Labels: PR: Needs +2

#17309 Fix squadmanager adding naval units to ground attack forces.
  OpenRA.Mods.Common/Traits/BotModules/SquadManagerBotModule.cs
Labels: PR: Needs +2

#17245 Fix #17230: Dummy audio output class
  OpenRA.Game/Sound/Sound.cs
  OpenRA.Game/Sound/SoundDevice.cs
  OpenRA.Mods.Common/Widgets/VqaPlayerWidget.cs
  OpenRA.Platforms.Default/DefaultPlatform.cs
  OpenRA.Platforms.Default/DummySoundEngine.cs
  OpenRA.Platforms.Default/OpenAlSoundEngine.cs
Labels: PR: Needs +2

#17274 Weighted A*
  OpenRA.Mods.Common/Pathfinder/BasePathSearch.cs
  OpenRA.Mods.Common/Pathfinder/Constants.cs
  OpenRA.Mods.Common/Pathfinder/PathGraph.cs
  OpenRA.Mods.Common/Pathfinder/PathSearch.cs
  OpenRA.Mods.Common/Traits/Harvester.cs
Labels: PR: Needs +2

#17255 Replace AmmoPool lookup methods with properties
  OpenRA.Mods.Cnc/Activities/LayMines.cs
  OpenRA.Mods.Common/Activities/Air/ReturnToBase.cs
  OpenRA.Mods.Common/Activities/Resupply.cs
  OpenRA.Mods.Common/Scripting/Properties/AmmoPoolProperties.cs
  OpenRA.Mods.Common/Traits/Air/Aircraft.cs
  OpenRA.Mods.Common/Traits/AmmoPool.cs
  OpenRA.Mods.Common/Traits/BotModules/Squads/States/AirStates.cs
  OpenRA.Mods.Common/Traits/ReloadAmmoPool.cs
  OpenRA.Mods.Common/Traits/Repairable.cs
Labels: PR: Needs +2

#17076 Add a trait PlayerRadarTerrain to track explored terrain
  OpenRA.Game/World.cs
  OpenRA.Mods.Common/Traits/Player/PlayerRadarTerrain.cs
  OpenRA.Mods.Common/Widgets/RadarWidget.cs
  mods/cnc/rules/player.yaml
  mods/d2k/rules/player.yaml
  mods/ra/rules/player.yaml
  mods/ts/rules/player.yaml
Labels: PR: Needs +2

#17321 Fix McvManagerBotModule spamming deploy orders
  OpenRA.Mods.Common/Traits/BotModules/McvManagerBotModule.cs
Labels: PR: Needs +2

#17372 Fix RA desert tree fire palette
  OpenRA.Mods.Common/Traits/Render/WithDamageOverlay.cs
  mods/ra/rules/defaults.yaml
Labels: PR: Needs +2

#17364 Fix FCOM still providing space while being captured
  mods/ra/rules/campaign-rules.yaml
  mods/ra/rules/civilian.yaml
Labels: PR: Needs +2

#17224 Fix ExtractLanguageStrings utility command
  OpenRA.Mods.Common/UtilityCommands/ExtractLanguageStringsCommand.cs
Labels: PR: Needs +2

#17384 Update update rule paths
  OpenRA.Mods.Common/UpdateRules/Rules/20191117/RemoveInitialFacingHardcoding.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20191117/RemoveYesNo.cs
  OpenRA.Mods.Common/UpdateRules/UpdatePath.cs
Labels: PR: Is Dependency, PR: Needs +2
