Repository OpenRA/OpenRA, pull requests merged in 2019-12, with the labels that each got.

#17358 Move ShpD2 and TmpRA/TD loaders to Mods.Cnc
  OpenRA.Mods.Cnc/SpriteLoaders/ShpD2Loader.cs
  OpenRA.Mods.Cnc/SpriteLoaders/TmpRALoader.cs
  OpenRA.Mods.Cnc/SpriteLoaders/TmpTDLoader.cs
Labels: PR: Is Dependency, PR: Needs +2

#17303 Fix botmodules querying the Player actor before it is assigned
  OpenRA.Mods.Common/Traits/BotModules/BaseBuilderBotModule.cs
  OpenRA.Mods.Common/Traits/BotModules/HarvesterBotModule.cs
  OpenRA.Mods.Common/Traits/BotModules/McvManagerBotModule.cs
  OpenRA.Mods.Common/Traits/BotModules/SquadManagerBotModule.cs
  OpenRA.Mods.Common/Traits/BotModules/SupportPowerBotModule.cs
  OpenRA.Mods.Common/Traits/BotModules/UnitBuilderBotModule.cs
Labels: PR: Needs +2

#17164 Lua API - Added Actor.TooltipName
  OpenRA.Mods.Common/Scripting/Properties/GeneralProperties.cs
Labels: PR: Needs +2

#17203 Don't throw an exception when a field is missing
  OpenRA.Game/GameRules/ActorInfo.cs
  OpenRA.Game/ObjectCreator.cs
Labels: PR: Needs +2

#17365 Change color of selection box based on selection mode.
  OpenRA.Mods.Common/Widgets/WorldInteractionControllerWidget.cs
  mods/cnc/metrics.yaml
  mods/d2k/metrics.yaml
  mods/ra/metrics.yaml
  mods/ts/metrics.yaml
Labels: PR: For stable, PR: Needs +2

#16760 Add selection tiers as inheritable templates
  mods/cnc/rules/defaults.yaml
  mods/cnc/rules/infantry.yaml
  mods/cnc/rules/tech.yaml
  mods/cnc/rules/vehicles.yaml
  mods/d2k/rules/defaults.yaml
  mods/d2k/rules/infantry.yaml
  mods/d2k/rules/structures.yaml
  mods/d2k/rules/vehicles.yaml
  mods/ra/maps/fort-lonestar/rules.yaml
  mods/ra/rules/defaults.yaml
  mods/ra/rules/infantry.yaml
  mods/ra/rules/vehicles.yaml
  mods/ts/rules/civilian-vehicles.yaml
  mods/ts/rules/defaults.yaml
  mods/ts/rules/nod-vehicles.yaml
  mods/ts/rules/shared-infantry.yaml
  mods/ts/rules/shared-vehicles.yaml
Labels: PR: For stable, PR: Needs +2

#17386 Move VocLoader from D2k to Cnc
  OpenRA.Mods.Cnc/AudioLoaders/VocLoader.cs
Labels: PR: Needs +2

#17410 Move ShpTDLoader, LZO and XORDelta formats to Mods.Cnc
  OpenRA.Mods.Cnc/FileFormats/LZOCompression.cs
  OpenRA.Mods.Cnc/FileFormats/XORDeltaCompression.cs
  OpenRA.Mods.Cnc/SpriteLoaders/ShpTDLoader.cs
  OpenRA.Mods.Cnc/UtilityCommands/ConvertPngToShpCommand.cs
  OpenRA.Mods.Cnc/UtilityCommands/ImportTSMapCommand.cs
  OpenRA.Mods.Cnc/UtilityCommands/RemapShpCommand.cs
Labels: PR: Is Dependency, PR: Needs +2

#17397 Restore old visibility recalc frequency (Prep Edition)
  mods/cnc/rules/aircraft.yaml
  mods/d2k/rules/aircraft.yaml
  mods/ra/rules/aircraft.yaml
Labels: PR: For stable, PR: Needs +2

#17432 Remove stray "Hotkeys" label in the Input Settings panel in TD
  mods/cnc/chrome/settings.yaml
Labels: PR: For stable, PR: Needs +2

#17381 Fix team chat messages not always being displayed
  OpenRA.Game/Network/UnitOrders.cs
Labels: PR: For stable, PR: Needs +2

#17435 Overhaul cursor doubling feature
  OpenRA.Game/Graphics/CursorProvider.cs
  OpenRA.Game/Graphics/SoftwareCursor.cs
  OpenRA.Mods.Common/Widgets/Logic/SettingsLogic.cs
  OpenRA.Mods.Common/Widgets/MouseAttachmentWidget.cs
  OpenRA.Mods.Common/Widgets/TooltipContainerWidget.cs
  OpenRA.Platforms.Default/Sdl2PlatformWindow.cs
  mods/cnc/chrome/settings.yaml
  mods/common/chrome/settings.yaml
Labels: PR: Is Dependency, PR: Needs +2

#17434 Fix for RA2 Mod: cloning vats
  OpenRA.Mods.Cnc/Traits/Buildings/ClonesProducedUnits.cs
Labels: PR: Needs +2

#17471 Fix ModContent cursor.
  mods/modcontent/cursor.pal
  mods/modcontent/cursor.png
  mods/modcontent/cursor.shp
  mods/modcontent/cursors.yaml
  mods/modcontent/mod.yaml
  mods/modcontent/rules.yaml
Labels: PR: Needs +2

#17473 Remove ISync from RallyPoint
  OpenRA.Mods.Common/Traits/Buildings/RallyPoint.cs
Labels: PR: Needs +2

#17460 Fix for mod credits overriding engine credits
  AUTHORS
  OpenRA.Mods.Common/Widgets/Logic/CreditsLogic.cs
Labels: PR: Needs +2

#17478 Move unit order resolving into a helper function
  OpenRA.Game/Network/UnitOrders.cs
Labels: PR: Needs +2

#17480 Remove a nowadays unnecessary loop safeguard
  OpenRA.Mods.Common/Widgets/WorldInteractionControllerWidget.cs
Labels: PR: Needs +2

#17479 Move voice playing for orders into a helper function
  OpenRA.Game/VoiceExts.cs
Labels: PR: Needs +2

#17505 Pass DamageTypes in Explodes
  OpenRA.Mods.Common/Traits/Explodes.cs
Labels: PR: Needs +2

#17485 Fix an indentation style issue in TransformsIntoAircraft
  OpenRA.Mods.Common/Traits/Buildings/TransformsIntoAircraft.cs
Labels: PR: Needs +2

#17512 Filter invalid actor IDs when restoring selection save data.
  OpenRA.Mods.Common/Traits/World/Selection.cs
Labels: PR: For stable, PR: Needs +2

#17467 Fix duplicated/distorted SequencePlaceBuildingPreview annotations.
  OpenRA.Mods.Common/Traits/Buildings/SequencePlaceBuildingPreview.cs
Labels: PR: Needs +2

#17465 Fix WithTextDecoration rendering with RequiresSelection: false
  OpenRA.Mods.Common/Traits/Render/WithTextDecoration.cs
Labels: PR: Needs +2

#17522 TakeCover fixes
  OpenRA.Mods.Common/Traits/Infantry/TakeCover.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20191117/RenameProneTime.cs
  OpenRA.Mods.Common/UpdateRules/UpdatePath.cs
Labels: PR: Is Dependency, PR: Needs +2

#17463 Fix bots using player actor powers after defeat
  OpenRA.Mods.Common/Traits/SupportPowers/SupportPowerManager.cs
Labels: PR: For stable, PR: Needs +2

#17533 Remove dublicate function
  mods/cnc/maps/nod09/nod09-AI.lua
Labels: PR: Needs +2

#17535 Remove a leftover geoip reference from the linux packaging script
  packaging/linux/buildpackage.sh
Labels: PR: For stable
