Repository OpenRA/OpenRA, pull requests merged in 2019-05, with the labels that each got.

#15945 Fix /givecashall debug-command
  OpenRA.Mods.Common/Commands/DevCommands.cs
  OpenRA.Mods.Common/Traits/Player/DeveloperMode.cs
Labels: PR: Needs +2

#16476 Remove HeliFlyCircle activity
  OpenRA.Mods.Common/Activities/Air/HeliFlyCircle.cs
  OpenRA.Mods.Common/OpenRA.Mods.Common.csproj
  OpenRA.Mods.Common/Traits/Air/Aircraft.cs
Labels: PR: Needs +2

#16487 Add references to the Code of Conduct.
  CONTRIBUTING.md
  README.md
Labels: PR: Needs +2

#16456 Use TryGet instead of Get and assign a default fallback Color
  OpenRA.Game/Game.cs
Labels: PR: Needs +2

#16468 Reduce overhead of every single order/sync frame by 162/222 bytes
  OpenRA.Game/Server/Server.cs
Labels: PR: Needs +2

#16401 Make ActorTags display ChildActivities
  OpenRA.Game/Activities/Activity.cs
  OpenRA.Mods.Common/Traits/Render/RenderDebugState.cs
Labels: PR: Needs +2

#16471 Add /playerxp command.
  OpenRA.Mods.Common/Commands/DevCommands.cs
  OpenRA.Mods.Common/Traits/Player/DeveloperMode.cs
Labels: PR: Needs +2

#16490 Optimize aircraft repulsion a little
  OpenRA.Mods.Common/Traits/Air/Aircraft.cs
Labels: PR: Needs +2

#16522 Update the forum link in the readme
  README.md
Labels: PR: Needs +2

#16382 Replace pseudo-childactivities in AttackMoveActivity.
  OpenRA.Mods.Common/Activities/Move/AttackMoveActivity.cs
  OpenRA.Mods.Common/Traits/AttackMove.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20190314/RenameAttackMoveConditions.cs
  OpenRA.Mods.Common/UpdateRules/UpdatePath.cs
  mods/cnc/rules/defaults.yaml
  mods/d2k/rules/defaults.yaml
  mods/ra/rules/campaign-rules.yaml
  mods/ra/rules/defaults.yaml
  mods/ra/rules/infantry.yaml
  mods/ts/rules/defaults.yaml
Labels: PR: Needs +2

#16500 Fix palette effects on RA desert buildings/rocks
  mods/ra/rules/palettes.yaml
Labels: PR: Needs +2

#15975 Fix Exceptions in VocLoader
  OpenRA.Mods.Common/AudioLoaders/VocLoader.cs
Labels: PR: Needs +2

#16544 Fix Sarin Gas Crackdown not ending after losing all units
  mods/ra/maps/sarin-gas-1-crackdown/crackdown.lua
Labels: PR: Needs +2

#16458 Fix FrozenUnderFog visibility calculation when fog is disabled.
  OpenRA.Mods.Common/ShroudExts.cs
  OpenRA.Mods.Common/Traits/Modifiers/FrozenUnderFog.cs
Labels: PR: Needs +2

#16537 Fix powershell if statements not checking the return value of calls
  make.ps1
Labels: PR: Needs +2

#16529 Use Write-Host instead of echo
  make.ps1
Labels: PR: Fixup requested, PR: Needs +2

#16527 Added configurations for starting the mods in VS
  OpenRA.Game/OpenRA.Game.csproj
  OpenRA.sln
Labels: PR: Needs +2

#16511 Fix man page installation
  Makefile
Labels: PR: Needs +2

#16545 Fix TD chrome.yaml definitions for panel-allblack
  mods/cnc/chrome.yaml
Labels: PR: Needs +2

#16514 Mines will no longer damage each other
  mods/ra/rules/defaults.yaml
  mods/ra/weapons/explosions.yaml
  mods/ra/weapons/smallcaliber.yaml
Labels: PR: Needs +2

#16562 Fix TD observer production icon hover crash.
  mods/cnc/chrome/ingame.yaml
  mods/cnc/chrome/tooltips.yaml
Labels: PR: Needs +2

#16556 Fix ICaptureProgressWatchers continuing after captor disposal.
  OpenRA.Mods.Common/Traits/CaptureManager.cs
Labels: PR: Needs +2

#16561 Fix dogs won't be build in Fort Lonestar
  mods/ra/maps/fort-lonestar/rules.yaml
Labels: PR: Needs +2

#16563 Fix "Max Speed" option when viewing replays.
  OpenRA.Game/Game.cs
Labels: PR: Needs +2

#16442 Added Cell and Wold position to TerrainGeometryOverlay
  OpenRA.Mods.Common/Widgets/Logic/Ingame/DebugLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Ingame/LoadIngamePlayerOrObserverUILogic.cs
  mods/cnc/chrome/ingame-debuginfo.yaml
  mods/cnc/mod.yaml
  mods/common/chrome/ingame-debuginfo.yaml
  mods/d2k/mod.yaml
  mods/ra/mod.yaml
  mods/ts/mod.yaml
Labels: PR: Needs +2

#16578 Added check to see if world.LocalPlayer
  OpenRA.Mods.Common/Widgets/Logic/Ingame/LoadIngamePlayerOrObserverUILogic.cs
Labels: PR: Needs +2

#16575 Replaces RunConfiguration and Configuration with launchSettings.json
  OpenRA.Game/OpenRA.Game.csproj
  OpenRA.Game/Properties/launchSettings.json
  OpenRA.sln
Labels: PR: Is Dependency, PR: Needs +2

#16550 Fix multiple clients being assigned as admin.
  OpenRA.Game/Server/Server.cs
Labels: PR: Needs +2

#16567 Prefer own service depots over allies'
  OpenRA.Mods.Common/Traits/Repairable.cs
  OpenRA.Mods.Common/Traits/RepairableNear.cs
Labels: PR: Needs +2

#16582 Make StoresResources trait public
  OpenRA.Mods.Common/Traits/StoresResources.cs
Labels: PR: Needs +2

#16312 CreateEffectWarhead improvements
  OpenRA.Mods.Common/Warheads/CreateEffectWarhead.cs
  OpenRA.Mods.Common/Warheads/Warhead.cs
Labels: PR: Needs +2

#16504 Make ClonesProducedUnits Conditional
  OpenRA.Mods.Cnc/Traits/Buildings/ClonesProducedUnits.cs
Labels: PR: Needs +2

#16594 Empty the default of TrailSequences in NukePower (version 2)
  OpenRA.Mods.Common/Traits/SupportPowers/NukePower.cs
Labels: PR: Needs +2

#16588 Fix Bullet contrails
  OpenRA.Mods.Common/Projectiles/Bullet.cs
Labels: PR: Needs +2

#16589 Added field to ProductionQueue to customize ordering in ObserverProductionIconsWidget
  OpenRA.Mods.Common/Traits/Player/ProductionQueue.cs
  OpenRA.Mods.Common/Widgets/ObserverProductionIconsWidget.cs
  mods/cnc/rules/structures.yaml
  mods/d2k/rules/player.yaml
  mods/ra/rules/player.yaml
  mods/ts/rules/player.yaml
Labels: PR: Needs +2

#16583 Added tooltip to support powers in spec ui
  OpenRA.Mods.Common/Widgets/Logic/Ingame/SupportPowerTooltipLogic.cs
  OpenRA.Mods.Common/Widgets/ObserverSupportPowerIconsWidget.cs
  OpenRA.Mods.Common/Widgets/SupportPowersWidget.cs
  mods/cnc/chrome/ingame.yaml
  mods/cnc/chrome/tooltips.yaml
  mods/common/chrome/ingame-observer.yaml
  mods/ra/chrome/ingame-observer.yaml
  mods/ts/chrome/ingame-observer.yaml
Labels: PR: Needs +2

#16587 Change default support dir location on Windows and Linux
  OpenRA.Game/Platform.cs
Labels: PR: Needs +2

#16610 Fix WithSpriteBody crashes
  OpenRA.Mods.Cnc/Traits/Render/WithEmbeddedTurretSpriteBody.cs
  OpenRA.Mods.Cnc/Traits/Render/WithGunboatBody.cs
  OpenRA.Mods.Common/Traits/Render/WithResourceLevelSpriteBody.cs
Labels: PR: Needs +2

#16601 Fix loadscreen text when switching between internal mods.
  OpenRA.Mods.Cnc/CncLoadScreen.cs
Labels: PR: Needs +2

#16564 Rework paradrop logic to be more robust.
  OpenRA.Mods.Common/Activities/Parachute.cs
  OpenRA.Mods.Common/Traits/EjectOnDeath.cs
  OpenRA.Mods.Common/Traits/ParaDrop.cs
  OpenRA.Mods.Common/Traits/ProductionParadrop.cs
  OpenRA.Mods.Common/Traits/SupportPowers/ParatroopersPower.cs
Labels: PR: Needs +2

#16547 Move Selection into a trait
  OpenRA.Game/Actor.cs
  OpenRA.Game/Game.cs
  OpenRA.Game/Traits/TraitsInterfaces.cs
  OpenRA.Game/World.cs
  OpenRA.Mods.Common/Traits/World/GameSaveViewportManager.cs
  OpenRA.Mods.Common/Traits/World/Selection.cs
  OpenRA.Mods.Common/Widgets/Logic/Ingame/Hotkeys/CycleBasesHotkeyLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Ingame/Hotkeys/CycleProductionActorsHotkeyLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Ingame/Hotkeys/JumpToSelectedActorsHotkeyLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Ingame/Hotkeys/RemoveFromControlGroupHotkeyLogic.cs
  mods/cnc/rules/world.yaml
  mods/d2k/rules/world.yaml
  mods/ra/rules/world.yaml
  mods/ts/rules/world.yaml
Labels: PR: Needs +2
