Repository OpenRA/OpenRA, pull requests merged in 2019-02, with the labels that each got.

#16130 Reduce thief speed and engineer CaptureDelay
  mods/ra/rules/infantry.yaml
Labels: PR: For stable, PR: Needs +2

#16138 Add VolumeModifier support to music.
  OpenRA.Game/GameRules/MusicInfo.cs
  OpenRA.Game/Sound/Sound.cs
Labels: PR: For stable, PR: Needs +2

#16155 Consider dead aircraft to no longer be in range in AirstrikePower and ParatroopersPower
  OpenRA.Mods.Common/Traits/SupportPowers/AirstrikePower.cs
  OpenRA.Mods.Common/Traits/SupportPowers/ParatroopersPower.cs
Labels: PR: For stable, PR: Needs +2

#15981 Remove unnecessary trait queries from HarvesterBotModule
  OpenRA.Mods.Common/Traits/BotModules/HarvesterBotModule.cs
Labels: PR: Needs +2

#16156 Reset unit stance on owner change.
  OpenRA.Mods.Common/Traits/AutoTarget.cs
Labels: PR: For stable, PR: Needs +2

#16152 Prefer target to lastVisible target if it is visible.
  OpenRA.Mods.Common/Activities/Attack.cs
Labels: PR: For stable, PR: Needs +2

#16158 Fix double-revoke crash in Demolishable.
  OpenRA.Mods.Common/Traits/Demolishable.cs
Labels: PR: For stable, PR: Needs +2

#16128 Add engineer and thief to Monster Tank Madness
  mods/ra/maps/monster-tank-madness/monster-tank-madness.lua
Labels: PR: For stable, PR: Needs +2

#16162 Let the extraction helicopter of Monster Tank Madness leave
  mods/ra/maps/monster-tank-madness/monster-tank-madness.lua
Labels: PR: For stable

#16170 Fix unresponsive aircraft when executing orders queued during resupply
  OpenRA.Mods.Common/Activities/Air/ResupplyAircraft.cs
  OpenRA.Mods.Common/Activities/Air/TakeOff.cs
Labels: PR: For stable

#16168 Defer UpdateFrozenActor until the end of the tick.
  OpenRA.Mods.Common/Traits/Modifiers/FrozenUnderFog.cs
Labels: PR: For stable, PR: Needs +2

#16054 Fix for #7083: Fly stops turning when target is inside the turn radius
  OpenRA.Mods.Common/Activities/Air/Fly.cs
  OpenRA.Mods.Common/Activities/Air/ReturnToBase.cs
Labels: PR: For stable, PR: Needs +2

#16182 Abort activities when we don't know how close to move to a target.
  OpenRA.Mods.Cnc/Activities/LeapAttack.cs
  OpenRA.Mods.Common/Activities/Attack.cs
  OpenRA.Mods.Common/Traits/Attack/AttackFollow.cs
Labels: PR: For stable, PR: Needs +2

#16175 Cache passenger bounty traits.
  OpenRA.Mods.Common/Traits/GivesBounty.cs
Labels: PR: For stable, PR: Needs +2

#16178 Clarify mission objectives #16169
  mods/ra/maps/infiltration/infiltration.lua
Labels: PR: Needs +2

#16064 Prevent multiple enumeration of validCells in SpawnMPUnits
  OpenRA.Mods.Common/Traits/World/SpawnMPUnits.cs
Labels: PR: Needs +2

#16194 Fix pre-placed frozen actors not being targetable
  OpenRA.Mods.Common/Traits/Modifiers/FrozenUnderFog.cs
Labels: PR: For stable

#16221 Fix editor crash when modifying newly placed actor ID.
  OpenRA.Mods.Common/Traits/World/EditorActorLayer.cs
  OpenRA.Mods.Common/Widgets/Logic/Editor/ActorEditLogic.cs
Labels: PR: For stable, PR: Needs +2

#15996 Reorder stance hotkeys in settings to match command bar
  mods/common/hotkeys/game.yaml
Labels: PR: Needs +2

#16222 Reuse GPSDotEffect for the lifetime of the actor.
  OpenRA.Mods.Cnc/Traits/GpsDot.cs
Labels: PR: For stable, PR: Needs +2

#16219 Avoid resetting FrozenActor.Hidden when refreshing GPS.
  OpenRA.Mods.Cnc/Traits/FrozenUnderFogUpdatedByGps.cs
Labels: PR: For stable, PR: Needs +2

#16196 Fix for #14013: App config for StyleCheck
  OpenRA.StyleCheck/App.config
  OpenRA.StyleCheck/OpenRA.StyleCheck.csproj
Labels: PR: Needs +2

#16225 Make JamsMissiles conditional
  OpenRA.Mods.Common/Traits/JamsMissiles.cs
Labels: PR: Needs +2

#16227 Add a boolean to show or not Refund X$ on the tooltip while selling.
  OpenRA.Mods.Common/Traits/Sellable.cs
Labels: PR: Needs +2

#15805 Implemented trait defined Rollovers.
  OpenRA.Game/Traits/TraitsInterfaces.cs
  OpenRA.Mods.Common/Traits/Render/SelectionDecorations.cs
  OpenRA.Mods.Common/Widgets/WorldInteractionControllerWidget.cs
Labels: PR: Needs +2

#15678 Alter default tabs' drop-down heights to align with the RA mod.
  OpenRA.Mods.Common/Widgets/Logic/Lobby/LobbyUtils.cs
Labels: PR: Needs +2

#16188 Making fake structure prices consistent
  mods/ra/rules/fakes.yaml
Labels: PR: Needs +2

#16207 Make ReturnToBase order queueable
  OpenRA.Mods.Common/Traits/Air/Aircraft.cs
Labels: PR: Needs +2

#16220 Remove flawed RateLimit implementation.
  OpenRA.Game/GameRules/SoundInfo.cs
  mods/cnc/audio/notifications.yaml
  mods/d2k/audio/notifications.yaml
  mods/ra/audio/notifications.yaml
  mods/ts/audio/speech-generic.yaml
Labels: PR: For stable, PR: Needs +2

#16211 Fix Pitfight: split stacked ore mine actors to different cells
  mods/ra/maps/pitfight.oramap
Labels: PR: For stable, PR: Needs +2

#16236 Work around ChildActivity cancellation issues in AttackLeap
  OpenRA.Mods.Cnc/Activities/LeapAttack.cs
Labels: PR: For stable, PR: Needs +2

#15809 Conditional TakeCover
  OpenRA.Mods.Common/Traits/Infantry/TakeCover.cs
Labels: PR: Needs +2
