Repository OpenRA/OpenRA, pull requests merged in 2019-09, with the labels that each got.

#16797 Rename FlyCircle to FlyIdle and make it tick TickIdle
  OpenRA.Mods.Common/Activities/Air/FlyIdle.cs
  OpenRA.Mods.Common/Activities/Air/Land.cs
  OpenRA.Mods.Common/Activities/Air/ReturnToBase.cs
  OpenRA.Mods.Common/Traits/Air/Aircraft.cs
Labels: PR: Needs +2

#17029 Update comment in Activity.cs
  OpenRA.Game/Activities/Activity.cs
Labels: PR: Needs +2

#17035 Remove the duplicate Selectable trait on TENF
  mods/ra/rules/fakes.yaml
Labels: PR: For stable, PR: Needs +2

#17007 GetAvailableSubCell should block cells outside the map
  OpenRA.Mods.Common/Traits/World/Locomotor.cs
Labels: PR: For stable, PR: Needs +2

#17003 More robust logic for ThisMinute stats
  OpenRA.Mods.Common/Traits/Player/PlayerStatistics.cs
Labels: PR: For stable, PR: Needs +2

#17025 #17018 Gets rid of cutoff line in chat window
  OpenRA.Mods.Common/Widgets/ChatDisplayWidget.cs
Labels: PR: For stable, PR: Needs +2

#17045 Fix a division by zero error in FindAndDeliverResources
  OpenRA.Mods.Common/Activities/FindAndDeliverResources.cs
Labels: PR: For stable, PR: Needs +2

#17037 Fix crushable logic for actors in cell
  OpenRA.Mods.Common/Traits/World/Locomotor.cs
Labels: PR: For stable, PR: Needs +2

#17061 Remove IronCurtainable from RA aircraft.
  mods/ra/rules/defaults.yaml
Labels: PR: For stable, PR: Needs +2

#17032 Locomotor cache should handle custom layers
  OpenRA.Mods.Common/Traits/World/Locomotor.cs
Labels: PR: For stable, PR: Needs +2

#17016 Fix crash with dead cargo.
  OpenRA.Mods.Common/Activities/RideTransport.cs
  OpenRA.Mods.Common/Traits/Cargo.cs
Labels: PR: For stable, PR: Needs +2

#17026 Fix ActorPreviewWidget viewport manipulation.
  OpenRA.Game/Graphics/Animation.cs
  OpenRA.Mods.Common/Graphics/ActorPreview.cs
  OpenRA.Mods.Common/Graphics/ModelActorPreview.cs
  OpenRA.Mods.Common/Graphics/SpriteActorPreview.cs
  OpenRA.Mods.Common/Graphics/UIModelRenderable.cs
  OpenRA.Mods.Common/Widgets/ActorPreviewWidget.cs
Labels: PR: Needs +2

#17075 Prevent users from selecting a directional target outside the map
  OpenRA.Mods.Common/Traits/SupportPowers/SelectDirectionalTarget.cs
Labels: PR: For stable, PR: Needs +2

#16737 Fix multiple (enabled) RejectsOrders traits not working as intended
  OpenRA.Mods.Common/Traits/RejectsOrders.cs
Labels: PR: Needs +2

#16858 PlayerStatistics should stop ticking after lost/win
  OpenRA.Mods.Common/Traits/Player/PlayerStatistics.cs
Labels: PR: Is Dependency, PR: Needs +2

#16975 Issues/16183
  OpenRA.Mods.Common/Traits/Conditions/GrantExternalConditionToProduced.cs
Labels: PR: Needs +2

#17019 Allow minefields to start and end on occupied cells.
  OpenRA.Mods.Cnc/Traits/Minelayer.cs
Labels: PR: Needs +2

#16900 Fix actors with no footprint not being copied and pasted
  OpenRA.Mods.Common/Traits/World/EditorActorLayer.cs
Labels: PR: Needs +2

#17004 Add UnionRectangles extension method.
  OpenRA.Game/Exts.cs
  OpenRA.Game/Traits/World/ScreenMap.cs
  OpenRA.Mods.Common/Graphics/DefaultSpriteSequence.cs
  OpenRA.Mods.Common/Traits/World/EditorActorPreview.cs
  OpenRA.Mods.Common/Widgets/ActorPreviewWidget.cs
  OpenRA.Mods.Common/Widgets/ProductionPaletteWidget.cs
  OpenRA.Mods.Common/Widgets/SupportPowersWidget.cs
Labels: PR: Needs +2

#17030 Fix idling aircraft on map Intervention
  mods/ra/maps/intervention/intervention.lua
  mods/ra/maps/intervention/rules.yaml
Labels: PR: For stable, PR: Needs +2

#17068 Fix player viewport saving for non-spectators.
  OpenRA.Mods.Common/Traits/World/GameSaveViewportManager.cs
Labels: PR: For stable, PR: Needs +2

#17079 Add duplicate hotkey tracking in the hotkey definition
  OpenRA.Game/HotkeyDefinition.cs
  OpenRA.Mods.Common/Widgets/Logic/SettingsLogic.cs
Labels: PR: Needs +2

#16408 Prevent harvesters getting stuck in gridlock by allowing units to give way.
  OpenRA.Game/Traits/TraitsInterfaces.cs
  OpenRA.Mods.Cnc/Traits/Minelayer.cs
  OpenRA.Mods.Cnc/Traits/TDGunboat.cs
  OpenRA.Mods.Common/Activities/Attack.cs
  OpenRA.Mods.Common/Activities/FindAndDeliverResources.cs
  OpenRA.Mods.Common/Activities/HarvestResource.cs
  OpenRA.Mods.Common/Activities/Move/Move.cs
  OpenRA.Mods.Common/Activities/Move/MoveAdjacentTo.cs
  OpenRA.Mods.Common/Activities/UnloadCargo.cs
  OpenRA.Mods.Common/Pathfinder/PathFinderUnitPathCacheDecorator.cs
  OpenRA.Mods.Common/Pathfinder/PathGraph.cs
  OpenRA.Mods.Common/Pathfinder/PathSearch.cs
  OpenRA.Mods.Common/Traits/Air/Aircraft.cs
  OpenRA.Mods.Common/Traits/Attack/AttackBase.cs
  OpenRA.Mods.Common/Traits/BotModules/HarvesterBotModule.cs
  OpenRA.Mods.Common/Traits/Buildings/TransformsIntoMobile.cs
  OpenRA.Mods.Common/Traits/Cargo.cs
  OpenRA.Mods.Common/Traits/Crates/Crate.cs
  OpenRA.Mods.Common/Traits/Harvester.cs
  OpenRA.Mods.Common/Traits/Husk.cs
  OpenRA.Mods.Common/Traits/Mobile.cs
  OpenRA.Mods.Common/Traits/World/Locomotor.cs
  OpenRA.Mods.Common/Traits/World/PathFinder.cs
  OpenRA.Mods.D2k/Activities/SwallowActor.cs
  OpenRA.Mods.D2k/Traits/Sandworm.cs
Labels: PR: Needs +2

#17088 Implement IEquatable on structs.
  OpenRA.Game/Input/Hotkey.cs
  OpenRA.Game/Primitives/Color.cs
  OpenRA.Game/Primitives/Pair.cs
  OpenRA.Game/Primitives/Rectangle.cs
  OpenRA.Game/Primitives/Size.cs
  OpenRA.Game/Primitives/float3.cs
Labels: PR: Needs +2

#16595 Add option for airlift to arrive from player baseline
  OpenRA.Mods.Cnc/Traits/Buildings/ProductionAirdrop.cs
Labels: PR: Needs +2

#17113 Fix MRV not auto targeting friendly vehicles
  mods/ts/rules/nod-vehicles.yaml
Labels: PR: Needs +2

#17086 Fix reinforcements on the ts shellmap not attack moving
  mods/ts/maps/fields-of-green/fields-of-green.lua
Labels: PR: Needs +2

#17147 Fix ctank and stank building faster then they should
  mods/ra/rules/vehicles.yaml
Labels: PR: For stable, PR: Needs +2

#16772 Editor undo redo
  OpenRA.Mods.Common/EditorBrushes/EditorActorBrush.cs
  OpenRA.Mods.Common/EditorBrushes/EditorCopyPasteBrush.cs
  OpenRA.Mods.Common/EditorBrushes/EditorDefaultBrush.cs
  OpenRA.Mods.Common/EditorBrushes/EditorResourceBrush.cs
  OpenRA.Mods.Common/EditorBrushes/EditorTileBrush.cs
  OpenRA.Mods.Common/Traits/World/EditorActionManager.cs
  OpenRA.Mods.Common/Traits/World/EditorActorLayer.cs
  OpenRA.Mods.Common/Traits/World/EditorActorPreview.cs
  OpenRA.Mods.Common/Widgets/EditorViewportControllerWidget.cs
  OpenRA.Mods.Common/Widgets/Logic/Editor/ActorEditLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Editor/HistoryLogLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Editor/MapEditorLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Editor/MapEditorTabsLogic.cs
  mods/cnc/chrome/editor.yaml
  mods/cnc/rules/world.yaml
  mods/common/chrome/editor.yaml
  mods/d2k/rules/world.yaml
  mods/ra/rules/world.yaml
  mods/ts/rules/world.yaml
Labels: PR: Needs +2

#17154 Rename duplicated actors
  mods/d2k/maps/shellmap/map.yaml
Labels: PR: Needs +2

#17122 Fix the expansion mcv in soviet05 being transported off the map
  mods/ra/maps/soviet-05/soviet05.lua
Labels: PR: For stable, PR: Needs +2

#17143 Add check to see if transport is dead to UnreserveSpace
  OpenRA.Mods.Common/Traits/Cargo.cs
Labels: PR: For stable, PR: Needs +2

#17146 Make mine targetable on attack everything stance for AutoTargetGround
  mods/ra/rules/defaults.yaml
Labels: PR: For stable, PR: Needs +2
