Repository OpenRA/OpenRA, pull requests merged in 2019-01, with the labels that each got.

#15974 Evaluate smooth scrolling per-frame instead of per-tick.
  OpenRA.Mods.Common/Widgets/ScrollPanelWidget.cs
Labels: PR: Needs +2

#15984 Add stance support to GrantExternalConditionPower.
  OpenRA.Mods.Common/Traits/SupportPowers/GrantExternalConditionPower.cs
Labels: PR: Needs +2

#15986 Add DamageTypes to Capture Sabotage
  OpenRA.Mods.Common/Activities/CaptureActor.cs
  OpenRA.Mods.Common/Traits/Captures.cs
Labels: PR: Needs +2

#15989 Map Editor - Copy filter
  OpenRA.Mods.Common/EditorBrushes/EditorCopyPasteBrush.cs
  OpenRA.Mods.Common/Widgets/Logic/Editor/MapEditorLogic.cs
  mods/cnc/chrome/editor.yaml
  mods/common/chrome/editor.yaml
Labels: PR: Needs +2

#15957 Rearrange default observer hotkeys
  OpenRA.Mods.Common/Widgets/Logic/Ingame/MenuButtonsChromeLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Ingame/ObserverStatsLogic.cs
  mods/cnc/chrome/ingame-observerstats.yaml
  mods/cnc/chrome/ingame.yaml
  mods/common/chrome/ingame-observer.yaml
  mods/common/chrome/ingame-observerstats.yaml
  mods/common/hotkeys/observer.yaml
  mods/ra/chrome/ingame-observer.yaml
  mods/ts/chrome/ingame-observer.yaml
  mods/ts/chrome/ingame-observerstats.yaml
Labels: PR: Needs +2

#15982 Prevent unit requests from stacking during production.
  OpenRA.Mods.Common/Traits/BotModules/McvManagerBotModule.cs
  OpenRA.Mods.Common/Traits/BotModules/UnitBuilderBotModule.cs
  OpenRA.Mods.Common/TraitsInterfaces.cs
Labels: PR: Is Dependency, PR: Needs +2

#16011 Hide husks under fog regardless of their owner.
  mods/cnc/rules/defaults.yaml
  mods/d2k/rules/defaults.yaml
  mods/ra/rules/defaults.yaml
  mods/ts/rules/defaults.yaml
Labels: PR: For stable

#15929 Add an interface to prevent actors from being spawned by SpawnMapActors
  OpenRA.Mods.Common/Traits/World/SpawnMapActors.cs
  OpenRA.Mods.Common/TraitsInterfaces.cs
Labels: PR: Is Dependency, PR: Needs +2

#15581 Change tree husks from FrozenUnderFog to HiddenUnderShroud
  mods/cnc/rules/defaults.yaml
  mods/ra/rules/defaults.yaml
Labels: PR: For stable

#16035 Add IsDead check to fix crash in Sarin Gas 1
  mods/ra/maps/sarin-gas-1-crackdown/crackdown.lua
Labels: PR: For stable

#16051 Fix Warhead.IsValidAgainst crash
  OpenRA.Mods.Common/Warheads/Warhead.cs
Labels: PR: For stable

#16043 Reset the client state when being moved to spectator
  OpenRA.Mods.Common/ServerTraits/LobbyCommands.cs
Labels: PR: For stable

#16080 Fix LeapAttack setting attack.IsAiming too early
  OpenRA.Mods.Cnc/Activities/LeapAttack.cs
Labels: PR: For stable

#16085 Fix crash by chat commands in replay
  OpenRA.Mods.Common/Widgets/Logic/Ingame/IngameChatLogic.cs
Labels: PR: For stable

#16081 Remove Game.Debug messages from ValidateOrder.
  OpenRA.Mods.Common/Traits/World/ValidateOrder.cs
Labels: PR: For stable, PR: Needs +2

#15680 Fix OnAllRemovedFromWorld only triggering once
  OpenRA.Mods.Common/Scripting/Global/TriggerGlobal.cs
  OpenRA.Mods.Common/Scripting/ScriptTriggers.cs
Labels: PR: For stable

#16072 Disable bot logic during replays.
  OpenRA.Mods.Common/Traits/Player/ModularBot.cs
Labels: PR: For stable, PR: Needs +2

#16114 Fix source package creation.
  packaging/source/buildpackage.sh
Labels: PR: For stable

#16093 Add AttackMove workaround for Aircraft.
  OpenRA.Mods.Common/Traits/Air/Aircraft.cs
Labels: PR: For stable, PR: Needs +2

#16113 Fix gate animations.
  OpenRA.Mods.Common/Traits/Buildings/Gate.cs
  mods/ts/rules/defaults.yaml
  mods/ts/sequences/structures.yaml
Labels: PR: For stable, PR: Needs +2
