Repository OpenRA/OpenRA, pull requests merged in 2019-03, with the labels that each got.

#16238 Fix a crash in soviet05
  mods/ra/maps/soviet-05/soviet05.lua
Labels: PR: For stable

#16252 Fix maximum range estimation for stationary turrets and stance-restricted units.
  OpenRA.Mods.Common/Traits/Attack/AttackFollow.cs
Labels: PR: For stable, PR: Needs +2

#16253 Work around harvester unloading activity queue issues.
  OpenRA.Mods.Common/Activities/FindResources.cs
Labels: PR: For stable, PR: Needs +2

#16237 Fix server list map preview polish issues.
  OpenRA.Mods.Common/Widgets/Logic/ServerListLogic.cs
Labels: PR: Needs +2

#16262 Make Mobile a PausableConditionalTrait
  OpenRA.Mods.Common/Activities/Move/Move.cs
  OpenRA.Mods.Common/Activities/Move/VisualMoveIntoTarget.cs
  OpenRA.Mods.Common/OpenRA.Mods.Common.csproj
  OpenRA.Mods.Common/Scripting/Properties/MobileProperties.cs
  OpenRA.Mods.Common/Traits/Mobile.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20181215/MakeMobilePausableConditional.cs
  OpenRA.Mods.Common/UpdateRules/UpdatePath.cs
  mods/cnc/rules/ships.yaml
  mods/cnc/rules/vehicles.yaml
  mods/d2k/rules/defaults.yaml
  mods/d2k/rules/vehicles.yaml
  mods/ra/rules/defaults.yaml
  mods/ra/rules/infantry.yaml
  mods/ra/rules/ships.yaml
  mods/ra/rules/vehicles.yaml
  mods/ts/rules/civilian-vehicles.yaml
  mods/ts/rules/defaults.yaml
  mods/ts/rules/gdi-vehicles.yaml
  mods/ts/rules/nod-vehicles.yaml
  mods/ts/rules/shared-vehicles.yaml
Labels: PR: Is Dependency, PR: Needs +2

#16276 Fixed NuGet-related dependency fetching on Windows
  thirdparty/fetch-thirdparty-deps.ps1
Labels: PR: Needs +2

#16280 Let civilians use the normal stand animation when panicking
  mods/cnc/sequences/civilian.yaml
  mods/ra/sequences/infantry.yaml
  mods/ts/sequences/infantry.yaml
Labels: PR: Needs +2

#16226 Implement Harvester>BaleUnloadAmount
  OpenRA.Mods.Common/Traits/Harvester.cs
Labels: PR: Needs +2

#16223 Make WithRangeCircle conditional
  OpenRA.Mods.Common/Traits/Render/WithRangeCircle.cs
Labels: PR: Needs +2

#16228 Add ExperienceTrickler trait
  OpenRA.Mods.Common/OpenRA.Mods.Common.csproj
  OpenRA.Mods.Common/Traits/ExperienceTrickler.cs
Labels: PR: Needs +2

#16288 Fix invalid target crash in SupportPowerManager.Activate.
  OpenRA.Mods.Common/Traits/SupportPowers/SupportPowerManager.cs
Labels: PR: Needs +2

#16268 Notify players when a vehicle have been lost to a Thief.
  mods/ra/rules/defaults.yaml
Labels: PR: For stable, PR: Needs +2

#16271 Work around a crash for invalid FrozenActor targets.
  OpenRA.Mods.Common/Traits/Mobile.cs
Labels: PR: For stable, PR: Needs +2

#16294 Fix prep update path for upcoming release
  OpenRA.Mods.Common/UpdateRules/UpdatePath.cs
Labels: PR: For stable, PR: Needs +2

#16266 Rename fields on Repairable traits
  OpenRA.Mods.Common/Activities/Air/HeliReturnToBase.cs
  OpenRA.Mods.Common/Activities/Air/ReturnToBase.cs
  OpenRA.Mods.Common/OpenRA.Mods.Common.csproj
  OpenRA.Mods.Common/Traits/Air/Aircraft.cs
  OpenRA.Mods.Common/Traits/Repairable.cs
  OpenRA.Mods.Common/Traits/RepairableNear.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20190106/StreamlineRepairableTraits.cs
  OpenRA.Mods.Common/UpdateRules/UpdatePath.cs
  mods/cnc/rules/defaults.yaml
  mods/d2k/rules/defaults.yaml
  mods/ra/rules/defaults.yaml
  mods/ts/rules/defaults.yaml
Labels: PR: Is Dependency, PR: Needs +2

#16217 Make Attack use ChildActivities
  OpenRA.Mods.Common/Activities/Attack.cs
  OpenRA.Mods.Common/Activities/Move/MoveAdjacentTo.cs
  OpenRA.Mods.Common/Activities/Move/MoveWithinRange.cs
Labels: PR: Needs +2

#16264 Support 24 bit png loading.
  OpenRA.Game/FileFormats/Png.cs
Labels: PR: Needs +2

#16255 Add support for multiple (un)deploy sounds on GrantConditionOnDeploy
  OpenRA.Mods.Common/OpenRA.Mods.Common.csproj
  OpenRA.Mods.Common/Traits/Conditions/GrantConditionOnDeploy.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20181215/MultipleDeploySounds.cs
  OpenRA.Mods.Common/UpdateRules/UpdatePath.cs
  mods/ts/rules/gdi-vehicles.yaml
  mods/ts/rules/nod-vehicles.yaml
  mods/ts/rules/shared-vehicles.yaml
Labels: PR: Needs +2

#16299 Change MECH repair voice from Move to Action
  mods/ra/rules/infantry.yaml
Labels: PR: Needs +2

#16291 Add int channel version of Color.FromAhsl.
  OpenRA.Game/Primitives/Color.cs
Labels: PR: Needs +2

#16286 Remove bogus and unnecessary Color[] FieldLoader override.
  OpenRA.Game/FieldLoader.cs
Labels: PR: Needs +2

#16129 Allow PortableChrono to queue teleports
  OpenRA.Mods.Cnc/Activities/Teleport.cs
  OpenRA.Mods.Cnc/Traits/PortableChrono.cs
Labels: PR: Needs +2

#16065 Allow minelaying to be queued
  OpenRA.Mods.Cnc/Activities/LayMines.cs
  OpenRA.Mods.Cnc/Traits/Minelayer.cs
Labels: PR: Needs +2

#16060 Allow deploy orders on units with the Cargo trait to be queued
  OpenRA.Mods.Common/Activities/UnloadCargo.cs
  OpenRA.Mods.Common/Traits/Cargo.cs
Labels: PR: Needs +2

#16304 Prevent support powers from creating two camera actors
  OpenRA.Mods.Common/Traits/SupportPowers/AirstrikePower.cs
  OpenRA.Mods.Common/Traits/SupportPowers/ParatroopersPower.cs
Labels: PR: Needs +2

#16177 Also trigger mission fail when subpen is sold
  mods/ra/maps/monster-tank-madness/monster-tank-madness.lua
Labels: PR: Needs +2

#16324 Require .NET Framework >= 4.7.2 on Windows.
  packaging/windows/OpenRA.nsi
Labels: PR: Is Dependency, PR: Needs +2

#16261 Addition of customizability to Hovers
  OpenRA.Mods.Common/Traits/Render/Hovers.cs
  mods/ts/rules/gdi-vehicles.yaml
Labels: PR: Needs +2

#16346 Remove ISync from AttackMove.
  OpenRA.Mods.Common/Traits/AttackMove.cs
Labels: PR: Needs +2

#16340 Update bleed update rule folder and update path
  OpenRA.Mods.Common/OpenRA.Mods.Common.csproj
  OpenRA.Mods.Common/UpdateRules/Rules/20190314/MakeMobilePausableConditional.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20190314/MultipleDeploySounds.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20190314/RemoveSimpleBeacon.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20190314/StreamlineRepairableTraits.cs
  OpenRA.Mods.Common/UpdateRules/UpdatePath.cs
Labels: PR: Needs +2

#16349 Remove pretick argument from Activity.Queue()
  OpenRA.Game/Activities/Activity.cs
  OpenRA.Mods.Common/Activities/Parachute.cs
Labels: PR: Needs +2

#16337 TS: fix disruptor healing
  mods/ts/rules/gdi-vehicles.yaml
Labels: PR: Needs +2

#16333 Fix auto-generated wiki docs
  OpenRA.Mods.Common/UtilityCommands/ExtractSettingsDocsCommand.cs
  OpenRA.Mods.Common/UtilityCommands/ExtractTraitDocsCommand.cs
  OpenRA.Mods.Common/UtilityCommands/ExtractWeaponDocsCommand.cs
  packaging/update-wiki.sh
Labels: PR: Needs +2

#16348 Replace SequenceActivities with ChildActivity in several activities.
  OpenRA.Mods.Cnc/Traits/Attack/AttackTesla.cs
  OpenRA.Mods.Common/Activities/Hunt.cs
  OpenRA.Mods.Common/Activities/Move/Follow.cs
  OpenRA.Mods.Common/Activities/UnloadCargo.cs
  OpenRA.Mods.Common/Traits/Attack/AttackFollow.cs
Labels: PR: Needs +2

#16295 Cargo crash fix and improvements
  OpenRA.Mods.Common/Traits/Cargo.cs
  OpenRA.Mods.Common/Traits/Passenger.cs
Labels: PR: Needs +2

#16313 Fix transport being blocked by its own passengers.
  OpenRA.Mods.Common/Traits/Cargo.cs
Labels: PR: Needs +2

#16319 Ship a minimal mono 5.10 runtime in the macOS .app bundles
  Makefile
  OpenRA.Platforms.Default.dll.config
  packaging/osx/buildpackage.sh
  thirdparty/fetch-thirdparty-deps-osx.sh
Labels: PR: Is Dependency, PR: Needs +2

#16351 Honor modifiers in multitap detection
  OpenRA.Platforms.Default/MultiTapDetection.cs
  OpenRA.Platforms.Default/Sdl2Input.cs
Labels: PR: Needs +2

#15952 Add Counterstrike mission Sarin Gas 2: Down Under
  mods/ra/maps/sarin-gas-2-down-under/downunder.lua
  mods/ra/maps/sarin-gas-2-down-under/map.bin
  mods/ra/maps/sarin-gas-2-down-under/map.png
  mods/ra/maps/sarin-gas-2-down-under/map.yaml
  mods/ra/maps/sarin-gas-2-down-under/rules.yaml
  mods/ra/missions.yaml
Labels: PR: Needs +2

#15990 Add hotkey for removing selected actors from control groups
  OpenRA.Game/Selection.cs
  OpenRA.Mods.Common/OpenRA.Mods.Common.csproj
  OpenRA.Mods.Common/Widgets/Logic/Ingame/Hotkeys/RemoveFromControlGroupHotkeyLogic.cs
  mods/cnc/chrome/ingame.yaml
  mods/common/chrome/ingame.yaml
  mods/common/hotkeys/game.yaml
Labels: PR: Needs +2

#16167 Counterstrike Soviet mission Top o' The World ported
  OpenRA.sln
  mods/ra/maps/top-o-the-world/map.bin
  mods/ra/maps/top-o-the-world/map.png
  mods/ra/maps/top-o-the-world/map.yaml
  mods/ra/maps/top-o-the-world/rules.yaml
  mods/ra/maps/top-o-the-world/scu36ea.lua
  mods/ra/maps/top-o-the-world/weapons.yaml
  mods/ra/missions.yaml
Labels: PR: Needs +2

#16354 Simplify Activity class
  OpenRA.Game/Activities/Activity.cs
  OpenRA.Game/Actor.cs
  OpenRA.Game/Traits/ActivityUtils.cs
  OpenRA.Mods.Common/Activities/Air/ResupplyAircraft.cs
  OpenRA.Mods.Common/Activities/DeliverResources.cs
  OpenRA.Mods.Common/Activities/FindResources.cs
Labels: PR: Needs +2

#16364 Replace SequenceActivities with ChildActivity in several air activities.
  OpenRA.Mods.Common/Activities/Air/FlyFollow.cs
  OpenRA.Mods.Common/Activities/Air/HeliAttack.cs
Labels: PR: Needs +2

#16366 Update SharpZipLib to 1.1.0.
  OpenRA.Game/FileFormats/Png.cs
  OpenRA.Game/FileSystem/ZipFile.cs
  OpenRA.Game/OpenRA.Game.csproj
  OpenRA.Game/Primitives/ZipFileHelper.cs
  OpenRA.Mods.Common/Widgets/Logic/Installation/DownloadPackageLogic.cs
  thirdparty/fetch-thirdparty-deps.ps1
  thirdparty/fetch-thirdparty-deps.sh
Labels: PR: Needs +2

#16367 TS - Seperate shellmap rules to Rules.yaml and make walls indestructible
  mods/ts/maps/fields-of-green/map.yaml
  mods/ts/maps/fields-of-green/rules.yaml
Labels: PR: Needs +2

#16358 Fix crash due to conflicting access to collection in killed Cargo
  OpenRA.Mods.Common/Traits/Passenger.cs
Labels: PR: Needs +2

#16329 Update thirdparty/configure-native-deps.sh
  thirdparty/configure-native-deps.sh
Labels: PR: Needs +2

#16371 Added the setting insert_final_newline to editorconfig
  .editorconfig
Labels: PR: Needs +2

#16372 Fix chinook being unable to land.
  OpenRA.Mods.Common/Traits/Air/Aircraft.cs
Labels: PR: Needs +2
