Repository OpenRA/OpenRA, pull requests merged in 2020-12, with the labels that each got.

#18881 Make WRot readonly and use in parameter modifier
  OpenRA.Game/Graphics/ModelRenderer.cs
  OpenRA.Game/WRot.cs
  OpenRA.Game/WVec.cs
  OpenRA.Mods.Common/Graphics/ModelRenderable.cs
  OpenRA.Mods.Common/Graphics/UIModelRenderable.cs
  OpenRA.Mods.Common/Traits/BodyOrientation.cs
Labels: PR: Needs +2

#18861 Add a utility.sh development helper
  utility.sh
Labels: PR: Needs +2

#18883 Update float3 to readonly and use in modifier for parameters.
  OpenRA.Game/Graphics/Renderable.cs
  OpenRA.Game/Graphics/RgbaColorRenderer.cs
  OpenRA.Game/Graphics/RgbaSpriteRenderer.cs
  OpenRA.Game/Graphics/SheetBuilder.cs
  OpenRA.Game/Graphics/Sprite.cs
  OpenRA.Game/Graphics/SpriteRenderable.cs
  OpenRA.Game/Graphics/SpriteRenderer.cs
  OpenRA.Game/Graphics/TerrainSpriteLayer.cs
  OpenRA.Game/Graphics/Util.cs
  OpenRA.Game/Graphics/Vertex.cs
  OpenRA.Game/Graphics/Viewport.cs
  OpenRA.Game/Primitives/float3.cs
  OpenRA.Mods.Common/Graphics/ModelRenderable.cs
  OpenRA.Mods.Common/Traits/TerrainLighting.cs
  OpenRA.Mods.Common/Traits/World/ShroudRenderer.cs
Labels: PR: Needs +2

#18890 Expose Player.HomeLocation to the Lua API.
  OpenRA.Mods.Common/Scripting/Properties/PlayerProperties.cs
Labels: PR: Needs +2

#18885 Make Attack turn during its own tick
  OpenRA.Mods.Common/Activities/Attack.cs
Labels: PR: Needs +2

#18869 Revert renderable buffer sorting improvements
  OpenRA.Game/Graphics/WorldRenderer.cs
Labels: PR: Needs +2

#18837 Enable dark mode support on macOS.
  packaging/macos/Info.plist.in
Labels: PR: Needs +2

#18878 ST Death Explosion Change
  mods/cnc/rules/husks.yaml
  mods/cnc/rules/vehicles.yaml
  mods/cnc/weapons/explosions.yaml
Labels: PR: Needs +2

#18896 Fix WithDeliveryAnimation overriding sell animation.
  OpenRA.Mods.Common/Traits/Render/WithDeliveryAnimation.cs
Labels: PR: Needs +2

#18893 Fix WithInfantryBody wrongly overwriting attack animations
  OpenRA.Mods.Common/Traits/Render/WithInfantryBody.cs
Labels: PR: Needs +2

#18903 Fix TD SAM Site facings being reset when damaged while closed.
  OpenRA.Mods.Cnc/Traits/Render/WithEmbeddedTurretSpriteBody.cs
  mods/cnc/rules/structures.yaml
Labels: PR: Needs +2

#18904 Fix Neutral crushing checks.
  OpenRA.Game/Primitives/LongBitSet.cs
  OpenRA.Mods.Cnc/Traits/Mine.cs
  OpenRA.Mods.Common/Traits/Crushable.cs
Labels: PR: Needs +2

#18894 Fix rally point target line exit display.
  OpenRA.Mods.Common/Effects/RallyPointIndicator.cs
  OpenRA.Mods.Common/Traits/Buildings/RallyPoint.cs
Labels: PR: Needs +2

#18874 Add DisplayFaction details to the replay metadata.
  OpenRA.Game/GameInformation.cs
  OpenRA.Game/Player.cs
  OpenRA.Mods.Common/Traits/World/CreateMPPlayers.cs
Labels: PR: Needs +2

#18902 Fix restart black screen race condition.
  OpenRA.Game/Game.cs
Labels: PR: Needs +2

#18430 Add Counterstrike mission Sarin Gas 3: Controlled Burn
  mods/ra/maps/sarin-gas-3-controlled-burn/controlledburn-AI.lua
  mods/ra/maps/sarin-gas-3-controlled-burn/controlledburn.lua
  mods/ra/maps/sarin-gas-3-controlled-burn/map.bin
  mods/ra/maps/sarin-gas-3-controlled-burn/map.png
  mods/ra/maps/sarin-gas-3-controlled-burn/map.yaml
  mods/ra/maps/sarin-gas-3-controlled-burn/rules.yaml
  mods/ra/missions.yaml
Labels: PR: Needs +2

#18695 Add Allies 09a
  mods/ra/maps/allies-09a/allies09a-AI.lua
  mods/ra/maps/allies-09a/allies09a.lua
  mods/ra/maps/allies-09a/map.bin
  mods/ra/maps/allies-09a/map.png
  mods/ra/maps/allies-09a/map.yaml
  mods/ra/maps/allies-09a/rules.yaml
  mods/ra/maps/allies-09a/weapons.yaml
  mods/ra/missions.yaml
Labels: PR: Needs +2

#18913 Fix infantry move animations *not* overriding the attack animation.
  OpenRA.Mods.Common/Traits/Render/WithInfantryBody.cs
Labels: PR: Needs +2

#18915 Switch mirror for nsis3 package.
  .travis.yml
Labels: PR: Needs +2

#18922 Fix docs.openra.net deployment (part 2)
  .github/workflows/documentation.yml
Labels: PR: For stable, PR: Needs +2

#18911 Removed dead code in the .aud reader
  OpenRA.Mods.Cnc/FileFormats/AudReader.cs
Labels: PR: Needs +2

#18436 Remove unneeded chrome yaml declarations
  mods/cnc/chrome.yaml
  mods/ra/chrome.yaml
  mods/ts/chrome.yaml
Labels: PR: Needs +2

#18443 Introduce loader for Meg V3 file format
  OpenRA.Mods.Cnc/FileSystem/MegFile.cs
Labels: PR: Needs +2

#18933 Enabled debug mode by default on Linux launch scripts
  launch-game.sh
Labels: PR: Needs +2

#18934 Add the 9th Dark Tournament map as "Oil Spill"
  mods/ra/maps/oil-spill/map.bin
  mods/ra/maps/oil-spill/map.png
  mods/ra/maps/oil-spill/map.yaml
  mods/ra/maps/oil-spill/oil-spill.lua
  mods/ra/maps/oil-spill/rules.yaml
  mods/ra/maps/oil-spill/sequences.yaml
Labels: PR: For stable, PR: Needs +2

#18947 Update MasterServerPinger to modern approach
  OpenRA.Mods.Common/ServerTraits/MasterServerPinger.cs
Labels: PR: Is Dependency, PR: Needs +2

#18044 Allow custom system chat labels
  OpenRA.Game/Game.cs
  mods/d2k/metrics.yaml
Labels: PR: Needs +2

#18953 Fix an incorrect comment in install_assemblies_mono
  packaging/functions.sh
Labels: PR: For stable, PR: Needs +2

#18945 Updated SharpZipLib
  OpenRA.Game/OpenRA.Game.csproj
Labels: PR: Needs +2

#18895 Improved BlankLoadScreen performance
  OpenRA.Mods.Common/LoadScreens/BlankLoadScreen.cs
Labels: PR: Needs +2

#18937 Parse .aud file metadata correctly
  OpenRA.Mods.Cnc/AudioLoaders/AudLoader.cs
  OpenRA.Mods.Cnc/FileFormats/AudReader.cs
Labels: PR: Needs +2

#18794 feat: ActorSpawnManager.SpawnInterval supports 1 or 2 values
  OpenRA.Mods.Common/Traits/World/ActorSpawnManager.cs
Labels: PR: Needs +2

#18792 Activity, fixes.
  OpenRA.Game/Activities/Activity.cs
Labels: PR: Needs +2

#18806 Server DispatchOrdersToClients create frame once for all clients.
  OpenRA.Game/Server/Server.cs
Labels: PR: Needs +2

#18959 Remove vestigial translation plumbing.
  OpenRA.Game/FieldLoader.cs
  OpenRA.Game/GameSpeed.cs
  OpenRA.Game/Manifest.cs
  OpenRA.Game/Map/Map.cs
  OpenRA.Game/ModData.cs
  OpenRA.Game/Settings.cs
  OpenRA.Game/Traits/Player/Shroud.cs
  OpenRA.Game/Traits/World/Faction.cs
  OpenRA.Mods.Cnc/Traits/SupportPowers/GrantPrerequisiteChargeDrainPower.cs
  OpenRA.Mods.Common/Traits/Buildable.cs
  OpenRA.Mods.Common/Traits/Player/ConquestVictoryConditions.cs
  OpenRA.Mods.Common/Traits/Player/DeveloperMode.cs
  OpenRA.Mods.Common/Traits/Player/PlayerResources.cs
  OpenRA.Mods.Common/Traits/Player/ProvidesTechPrerequisite.cs
  OpenRA.Mods.Common/Traits/Player/StrategicVictoryConditions.cs
  OpenRA.Mods.Common/Traits/Render/WithTextDecoration.cs
  OpenRA.Mods.Common/Traits/Tooltip.cs
  OpenRA.Mods.Common/Traits/TooltipDescription.cs
  OpenRA.Mods.Common/Traits/World/CrateSpawner.cs
  OpenRA.Mods.Common/Traits/World/MPStartLocations.cs
  OpenRA.Mods.Common/Traits/World/MapBuildRadius.cs
  OpenRA.Mods.Common/Traits/World/MapCreeps.cs
  OpenRA.Mods.Common/Traits/World/MapOptions.cs
  OpenRA.Mods.Common/Traits/World/ScriptLobbyDropdown.cs
  OpenRA.Mods.Common/Traits/World/SpawnMPUnits.cs
  OpenRA.Mods.Common/UtilityCommands/ExtractLanguageStringsCommand.cs
  OpenRA.Mods.Common/Widgets/ButtonWidget.cs
  OpenRA.Mods.Common/Widgets/ImageWidget.cs
  OpenRA.Mods.Common/Widgets/LabelWidget.cs
  OpenRA.Mods.Common/Widgets/Logic/SettingsLogic.cs
  OpenRA.Mods.Common/Widgets/ProductionPaletteWidget.cs
  OpenRA.Mods.Common/Widgets/SupportPowersWidget.cs
  mods/cnc/languages/english.yaml
  mods/cnc/mod.yaml
  mods/d2k/languages/english.yaml
  mods/d2k/mod.yaml
  mods/ra/languages/english.yaml
  mods/ts/languages/english.yaml
  mods/ts/mod.yaml
Labels: PR: Needs +2

#18967 Correct Shock Trooper Move and Select voices
  mods/ra/audio/voices.yaml
Labels: PR: Needs +2

#18963 Explicitly return on failure in make.ps1
  make.ps1
Labels: PR: Needs +2

#18980 Add player random faction info in the objectives panel
  OpenRA.Mods.Common/Widgets/Logic/Ingame/GameInfoStatsLogic.cs
Labels: PR: Needs +2

#18964 Enable mechanic voices from Aftermath
  mods/ra/audio/voices.yaml
Labels: PR: For stable, PR: Needs +2

#18977 Fix TD Building SoundOnDamageTransition DamagedSound and add variety to Building DestroyedSounds
  mods/cnc/rules/defaults.yaml
Labels: PR: For stable, PR: Needs +2

#18954 Update launch.json to work with the new launcher
  .vscode/launch.json
Labels: PR: For stable, PR: Needs +2
