Repository OpenRA/OpenRA, pull requests merged in 2020-03, with the labels that each got.

#17741 Round dropdown arrow position to an integer pixel.
  OpenRA.Mods.Common/Widgets/DropDownButtonWidget.cs
Labels: PR: Needs +2

#17742 Fix WithDisguisingInfantryBody idle animation crash.
  OpenRA.Mods.Cnc/Traits/Render/WithDisguisingInfantryBody.cs
  OpenRA.Mods.Common/Traits/Render/WithInfantryBody.cs
Labels: PR: Needs +2

#17749 Fix a crash in --clear-invalid-mod-registrations
  OpenRA.Game/ExternalMods.cs
Labels: PR: Needs +2

#17756 Fix GetActorsAt(CPos, SubCell) with special-case subcells.
  OpenRA.Mods.Common/Traits/World/ActorMap.cs
Labels: PR: Needs +2

#17620 Added remappable support to production icons
  OpenRA.Mods.Common/Traits/Buildable.cs
  OpenRA.Mods.Common/Traits/Player/PlayerStatistics.cs
  OpenRA.Mods.Common/Widgets/ObserverArmyIconsWidget.cs
  OpenRA.Mods.Common/Widgets/ObserverProductionIconsWidget.cs
  OpenRA.Mods.Common/Widgets/ProductionPaletteWidget.cs
Labels: PR: Needs +2

#17776 Fix aircraft not taking off properly
  OpenRA.Mods.Common/Traits/Buildings/Reservable.cs
Labels: PR: For stable, PR: Needs +2

#17777 Cache CandidateMovementCells within the same tick.
  OpenRA.Mods.Common/Activities/Move/MoveAdjacentTo.cs
Labels: PR: For stable, PR: Needs +2

#17799 Made the GlobalLightingPaletteEffect public
  OpenRA.Mods.Common/Traits/PaletteEffects/GlobalLightingPaletteEffect.cs
Labels: PR: Needs +2

#17775 Update macOS launcher to fix "View Logs" button.
  packaging/macos/buildpackage.sh
  thirdparty/fetch-thirdparty-deps-osx.sh
Labels: PR: For stable, PR: Needs +2

#17085 Add gdi08a
  OpenRA.sln
  mods/cnc/maps/gdi08a/gdi08a-AI.lua
  mods/cnc/maps/gdi08a/gdi08a.lua
  mods/cnc/maps/gdi08a/map.bin
  mods/cnc/maps/gdi08a/map.png
  mods/cnc/maps/gdi08a/map.yaml
  mods/cnc/maps/gdi08a/rules.yaml
  mods/cnc/missions.yaml
Labels: PR: Needs +2

#17811 Fixed spies ignoring the target's faction
  OpenRA.Mods.Cnc/Traits/Render/WithDisguisingInfantryBody.cs
Labels: PR: Needs +2

#17798 Fix the settings tooltip container being overwritten ingame
  mods/cnc/chrome/settings.yaml
  mods/common/chrome/settings.yaml
Labels: PR: For stable, PR: Needs +2

#17813 Remove invalid caching from GCOT.
  OpenRA.Mods.Common/Traits/Conditions/GrantConditionOnTerrain.cs
Labels: PR: For stable, PR: Needs +2

#17819 Removed .lua scripts from the .NET solution file
  OpenRA.sln
Labels: PR: Needs +2

#17514 Add gdi09ea
  mods/cnc/maps/gdi09/gdi09-AI.lua
  mods/cnc/maps/gdi09/gdi09.lua
  mods/cnc/maps/gdi09/map.bin
  mods/cnc/maps/gdi09/map.png
  mods/cnc/maps/gdi09/map.yaml
  mods/cnc/maps/gdi09/rules.yaml
  mods/cnc/maps/gdi09/weapons.yaml
  mods/cnc/missions.yaml
Labels: PR: For stable, PR: Needs +2

#17807 Replace deprecated native OpenAL with OpenAL Soft on macOS.
  packaging/macos/buildpackage.sh
  thirdparty/fetch-thirdparty-deps-osx.sh
  thirdparty/fetch-thirdparty-deps.sh
Labels: PR: For stable, PR: Needs +2

#17838 Added an option to allow placing buildings on resources
  OpenRA.Mods.Common/Traits/Buildings/Building.cs
  OpenRA.Mods.Common/Traits/Buildings/BuildingUtils.cs
Labels: PR: Needs +2

#17806 Adjust the stroke of the muted indicator glyph
  mods/cnc/chrome.yaml
  mods/cnc/uibits/chrome-2x.png
  mods/cnc/uibits/chrome-3x.png
  mods/cnc/uibits/chrome.png
  mods/d2k/chrome.yaml
  mods/d2k/uibits/glyphs-2x.png
  mods/d2k/uibits/glyphs-3x.png
  mods/d2k/uibits/glyphs.png
  mods/ra/chrome.yaml
  mods/ra/uibits/glyphs-2x.png
  mods/ra/uibits/glyphs-3x.png
  mods/ra/uibits/glyphs.png
  mods/ts/chrome.yaml
  mods/ts/uibits/glyphs-2x.png
  mods/ts/uibits/glyphs-3x.png
  mods/ts/uibits/glyphs.png
Labels: PR: For stable, PR: Needs +2

#17822 Added a shared parallel production queue
  OpenRA.Mods.Common/Traits/Player/ClassicParallelProductionQueue.cs
Labels: PR: Needs +2

#17844 Removed an unused terrain type
  mods/ra/tilesets/desert.yaml
Labels: PR: Needs +2

#17845 Fix detection circle line rendering.
  OpenRA.Mods.Common/Graphics/DetectionCircleAnnotationRenderable.cs
Labels: PR: For stable

#17841 Remove text caching from CncLoadScreen.
  OpenRA.Mods.Cnc/CncLoadScreen.cs
Labels: PR: For stable, PR: Needs +2

#17805 Restore ability to configure RMB orders + RMB panning.
  OpenRA.Game/Settings.cs
  OpenRA.Mods.Common/Widgets/Logic/IntroductionPromptLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/SettingsLogic.cs
  OpenRA.Mods.Common/Widgets/ViewportControllerWidget.cs
  mods/cnc/chrome/mainmenu-prompts.yaml
  mods/cnc/chrome/settings.yaml
  mods/common/chrome/mainmenu-prompts.yaml
  mods/common/chrome/settings.yaml
Labels: PR: For stable, PR: Needs +2

#17790 Align lobby bits in the player tab in TD
  mods/cnc/chrome/lobby-players.yaml
Labels: PR: For stable, PR: Needs +2

#17812 Always show the building fake tags
  mods/ra/rules/defaults.yaml
Labels: PR: Needs +2

#17789 Transformation can pass exp/level to new actor
  OpenRA.Mods.Common/Traits/GainsExperience.cs
Labels: PR: Needs +2

#17848 Fix and simplify ScrollPanelWidget thumb rect calculation.
  OpenRA.Mods.Common/Widgets/ScrollPanelWidget.cs
Labels: PR: For stable

#17851 Fix SpriteEffect updating twice in the first tick.
  OpenRA.Mods.Common/Effects/SpriteEffect.cs
Labels: PR: For stable, PR: Needs +2

#17861 Fix minelayers leaking enemy mine positions through the fog.
  OpenRA.Mods.Cnc/Activities/LayMines.cs
Labels: PR: For stable, PR: Needs +2

#17849 Make the right edge of the TD Airstrip transitable.
  mods/cnc/rules/structures.yaml
Labels: PR: For stable, PR: Needs +2

#17854 Adjust the map visibility panel height
  mods/cnc/chrome/editor.yaml
  mods/common/chrome/editor.yaml
Labels: PR: For stable, PR: Needs +2

#17852 Move selectableActor check inside InputOverridesSelection.
  OpenRA.Game/Orders/UnitOrderGenerator.cs
  OpenRA.Mods.Common/Widgets/WorldInteractionControllerWidget.cs
Labels: PR: For stable, PR: Needs +2

#17815 Added additional notification support to infiltration
  OpenRA.Mods.Cnc/Traits/Infiltration/InfiltrateForCash.cs
  OpenRA.Mods.Cnc/Traits/Infiltration/InfiltrateForExploration.cs
  OpenRA.Mods.Cnc/Traits/Infiltration/InfiltrateForPowerOutage.cs
  OpenRA.Mods.Cnc/Traits/Infiltration/InfiltrateForSupportPower.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20200202/RenameInfiltrationNotifications.cs
  OpenRA.Mods.Common/UpdateRules/UpdatePath.cs
  mods/ra/rules/structures.yaml
Labels: PR: Needs +2

#17868 Fix actors with no footprint leaving stale data when deleted.
  OpenRA.Mods.Common/Traits/World/EditorActorLayer.cs
Labels: PR: For stable, PR: Needs +2

#17814 RA Balance changes for March 2020
  mods/ra/rules/aircraft.yaml
  mods/ra/rules/vehicles.yaml
  mods/ra/weapons/missiles.yaml
  mods/ra/weapons/smallcaliber.yaml
Labels: PR: Needs +2

#17721 Added DamageTypes to Repairing
  OpenRA.Mods.Common/Activities/Resupply.cs
  OpenRA.Mods.Common/Traits/Buildings/RepairableBuilding.cs
  OpenRA.Mods.Common/Traits/RepairsUnits.cs
Labels: PR: Needs +2
