Repository OpenRA/OpenRA, pull requests merged in 2020-05, with the labels that each got.

#17966 Fixed LeaveSmudgeWarhead querying invalid targets
  OpenRA.Mods.Common/Warheads/LeaveSmudgeWarhead.cs
Labels: PR: Needs +2

#18014 Added an out of bounds check to GrantConditionOnTerrain
  OpenRA.Mods.Common/Traits/Conditions/GrantConditionOnTerrain.cs
Labels: PR: Needs +2

#18011 Make all warheads use WarheadArgs
  OpenRA.Game/GameRules/WeaponInfo.cs
  OpenRA.Mods.Common/Warheads/DamageWarhead.cs
  OpenRA.Mods.Common/Warheads/HealthPercentageDamageWarhead.cs
  OpenRA.Mods.Common/Warheads/SpreadDamageWarhead.cs
  OpenRA.Mods.Common/Warheads/TargetDamageWarhead.cs
Labels: PR: Needs +2

#17923 Added some basic error handling to png metadata writing
  OpenRA.Mods.Common/UtilityCommands/PngSheetImportMetadataCommand.cs
Labels: PR: Needs +2

#18000 Add a decoration glyph for friendly units in tunnels
  mods/ts/bits/typeglyphs.shp
  mods/ts/rules/defaults.yaml
  mods/ts/rules/nod-vehicles.yaml
  mods/ts/rules/shared-vehicles.yaml
  mods/ts/sequences/misc.yaml
Labels: PR: Needs +2

#18019 Remove OpenRA.PostProcess.exe.
  OpenRA.Game/OpenRA.Game.csproj
  OpenRA.PostProcess/OpenRA.PostProcess.csproj
  OpenRA.Server/OpenRA.Server.csproj
  OpenRA.Utility/OpenRA.Utility.csproj
  OpenRA.sln
  packaging/windows/MakeLAA.cs
  packaging/windows/buildpackage.sh
Labels: PR: Is Dependency, PR: Needs +2

#17588 Added more context when crashing during .png sheet loading
  OpenRA.Mods.Common/SpriteLoaders/PngSheetLoader.cs
Labels: PR: Needs +2

#18010 D2k weapon damage spread and falloff
  mods/d2k/weapons/debris.yaml
  mods/d2k/weapons/largeguns.yaml
  mods/d2k/weapons/missiles.yaml
  mods/d2k/weapons/other.yaml
  mods/d2k/weapons/smallguns.yaml
Labels: PR: Needs +2

#17992 Hide selection decorations when spectators zoom too far out.
  OpenRA.Game/Graphics/Viewport.cs
  OpenRA.Mods.Common/Traits/Render/SelectionDecorationsBase.cs
Labels: PR: Needs +2

#18021 Fixed PNG frame count calculation
  OpenRA.Mods.Common/SpriteLoaders/PngSheetLoader.cs
Labels: PR: Needs +2

#18022 Fixed the component tower locking up when fired upon during the make animation.
  mods/ts/rules/gdi-support.yaml
  mods/ts/sequences/structures.yaml
Labels: PR: Needs +2

#18031 Add infiltration sounds support to InfiltrateForSupportPowerReset
  OpenRA.Mods.Cnc/Traits/Infiltration/InfiltrateForSupportPowerReset.cs
Labels: PR: Needs +2

#18045 Added Tiberian Sun civilian voices
  mods/ts/audio/voices.yaml
  mods/ts/rules/civilian-infantry.yaml
Labels: PR: Needs +2

#18041 Fixed RangeModifiers not being initialized by SpiceBloom
  OpenRA.Mods.D2k/Traits/SpiceBloom.cs
Labels: PR: Needs +2

#18020 Reimplement ClassicQuantizeFacing using a look-up-table.
  OpenRA.Mods.Cnc/Util.cs
Labels: PR: Is Dependency, PR: Needs +2

#18049 Remove DeathSounds overwrites from the desert shellmap
  mods/ra/maps/desert-shellmap/rules.yaml
Labels: PR: Needs +2

#18076 Add IsInWorld check for control groups
  OpenRA.Mods.Common/Traits/World/Selection.cs
Labels: PR: Needs +2

#18089 Changed documentation for OnEnterComplete
  OpenRA.Mods.Common/Activities/Enter.cs
Labels: PR: Needs +2

#18037 Reset filters after selected text is removed
  OpenRA.Mods.Common/Widgets/TextFieldWidget.cs
Labels: PR: Needs +2

#18083 Add map.contains check to CanStayInCell
  OpenRA.Mods.Common/Traits/World/Locomotor.cs
Labels: PR: For stable, PR: Needs +2

#18070 Fix a scripting error in nod04b
  mods/cnc/maps/nod04b/nod04b.lua
Labels: PR: For stable, PR: Needs +2

#18097 Added a transparent index setting for player highlighting
  OpenRA.Game/Traits/Player/PlayerHighlightPalette.cs
Labels: PR: Needs +2

#18064 check name for Actor.GrantCondition()
  OpenRA.Game/Actor.cs
  OpenRA.Mods.Cnc/Traits/Attack/AttackLeap.cs
  OpenRA.Mods.Cnc/Traits/ConyardChronoReturn.cs
  OpenRA.Mods.Cnc/Traits/Disguise.cs
  OpenRA.Mods.Cnc/Traits/MadTank.cs
  OpenRA.Mods.Common/Activities/Move/AttackMoveActivity.cs
  OpenRA.Mods.Common/Traits/Air/Aircraft.cs
  OpenRA.Mods.Common/Traits/Attack/AttackCharges.cs
  OpenRA.Mods.Common/Traits/Buildings/PrimaryBuilding.cs
  OpenRA.Mods.Common/Traits/CaptureManager.cs
  OpenRA.Mods.Common/Traits/Cargo.cs
  OpenRA.Mods.Common/Traits/Carryable.cs
  OpenRA.Mods.Common/Traits/Cloak.cs
  OpenRA.Mods.Common/Traits/Conditions/GrantConditionOnDeploy.cs
  OpenRA.Mods.Common/Traits/Conditions/GrantConditionOnLineBuildDirection.cs
  OpenRA.Mods.Common/Traits/Demolishable.cs
  OpenRA.Mods.Common/Traits/KillsSelf.cs
  OpenRA.Mods.Common/Traits/Parachutable.cs
  OpenRA.Mods.Common/Traits/Passenger.cs
  OpenRA.Mods.Common/Traits/Render/WithMakeAnimation.cs
  OpenRA.Mods.D2k/Activities/SwallowActor.cs
Labels: PR: Is Dependency, PR: Needs +2

#18108 Correct aircraft repulsion direction when outside of the map.
  OpenRA.Mods.Common/Traits/Air/Aircraft.cs
Labels: PR: Needs +2

#18128 Remove bogus weapon override defintions from TD campaign maps
  mods/cnc/maps/gdi04a/map.yaml
  mods/cnc/maps/gdi04b/map.yaml
  mods/cnc/maps/gdi05a/map.yaml
Labels: PR: Needs +2

#17835 Prevent AI from sending squads against certain target types
  OpenRA.Mods.Common/Traits/BotModules/SquadManagerBotModule.cs
  OpenRA.Mods.Common/Traits/BotModules/Squads/States/AirStates.cs
  OpenRA.Mods.Common/Traits/BotModules/Squads/States/GroundStates.cs
  OpenRA.Mods.Common/Traits/BotModules/Squads/States/NavyStates.cs
  OpenRA.Mods.Common/Traits/BotModules/Squads/States/StateBase.cs
  mods/d2k/rules/ai.yaml
Labels: PR: Needs +2

#18142 Add trim_trailing_whitespace to .editorconfig
  .editorconfig
Labels: PR: Needs +2

#18141 Fix resupply not displaying target lines correctly
  OpenRA.Mods.Common/Activities/Resupply.cs
Labels: PR: Needs +2

#18140 Make the TS Test AI build aircraft
  mods/ts/rules/ai.yaml
Labels: PR: Needs +2

#18133 Added a bullet bounce sound
  OpenRA.Mods.Common/Projectiles/Bullet.cs
Labels: PR: Needs +2

#17829 Let AI autotargeting in D2k ignore sandworms
  mods/d2k/rules/campaign-rules.yaml
  mods/d2k/rules/defaults.yaml
Labels: PR: Needs +2

#18152 Fix a crash when a harvester is rebuilt in cnc64gdi01
  mods/cnc/maps/cnc64gdi01/cnc64gdi01.lua
Labels: PR: For stable, PR: Needs +2

#18148 Fixed a crash when putting AmbientSound on the World actor
  OpenRA.Mods.Common/Traits/Sound/AmbientSound.cs
Labels: PR: Needs +2

#17758 Added TurnOnIdle for Tiberian Sun infantry
  AUTHORS
  OpenRA.Mods.Common/Traits/TurnOnIdle.cs
  mods/ts/rules/defaults.yaml
Labels: PR: Needs +2

#18187 Fix Barrel explosion not dealing damage
  mods/ra/weapons/explosions.yaml
Labels: PR: Needs +2

#18126 Add Tree armor type and remove tree-only warheads from RA nukes
  mods/ra/rules/defaults.yaml
  mods/ra/weapons/explosions.yaml
  mods/ra/weapons/missiles.yaml
  mods/ra/weapons/other.yaml
  mods/ra/weapons/superweapons.yaml
Labels: PR: Needs +2

#18067 Convert QuantizeFacing to WAngle.
  OpenRA.Mods.Cnc/Graphics/ClassicSpriteSequence.cs
  OpenRA.Mods.Cnc/Traits/ClassicFacingBodyOrientation.cs
  OpenRA.Mods.Cnc/Traits/Render/WithCargo.cs
  OpenRA.Mods.Cnc/Util.cs
  OpenRA.Mods.Common/Activities/HarvestResource.cs
  OpenRA.Mods.Common/Graphics/DefaultSpriteSequence.cs
  OpenRA.Mods.Common/Traits/Attack/AttackGarrisoned.cs
  OpenRA.Mods.Common/Traits/BodyOrientation.cs
  OpenRA.Mods.Common/Traits/Render/WithMuzzleOverlay.cs
  OpenRA.Mods.Common/Traits/Turreted.cs
  OpenRA.Mods.Common/Util.cs
Labels: PR: Needs +2

#18205 Use OccupiesSpace to avoid Mobile look-ups
  OpenRA.Mods.Common/Traits/World/PathFinder.cs
Labels: PR: Needs +2

#18200 Fix harvest animation facing glitch.
  mods/cnc/rules/vehicles.yaml
  mods/ra/rules/vehicles.yaml
Labels: PR: Needs +2

#18199 Added .NET Coding Conventions to EditorConfig
  .editorconfig
Labels: PR: Needs +2
