Repository OpenRA/OpenRA, pull requests merged in 2020-01, with the labels that each got.

#17363 Fix DeliverUnit-related crash
  OpenRA.Mods.Common/Activities/DeliverUnit.cs
Labels: PR: For stable, PR: Needs +2

#17451 Fix ants teleporting into the map area in ant-01
  mods/ra/maps/ant-01/ant-attack.lua
Labels: PR: For stable, PR: Needs +2

#17482 Add a hotkey to cycle harvesters
  OpenRA.Mods.Common/Widgets/Logic/Ingame/Hotkeys/CycleHarvestersHotkeyLogic.cs
  mods/cnc/chrome/ingame.yaml
  mods/common/chrome/ingame.yaml
  mods/common/hotkeys/game.yaml
Labels: PR: Needs +2

#17376 Remove CurrentAdjacentCells update on each tick in Cargo
  OpenRA.Mods.Common/Traits/Cargo.cs
Labels: PR: Needs +2

#17517 Overhaul cursor loading
  OpenRA.Game/Graphics/HardwareCursor.cs
Labels: PR: For stable, PR: Needs +2

#17550 Use system chat line for audio muted/unmuted notifications
  OpenRA.Mods.Common/Widgets/Logic/MuteHotkeyLogic.cs
Labels: PR: For stable, PR: Needs +2

#17519 Fixed a crash when hardware cursor is null
  OpenRA.Game/Graphics/HardwareCursor.cs
Labels: PR: Needs +2

#17462 Fix crash in RallyPointIndicator.
  OpenRA.Mods.Common/Effects/RallyPointIndicator.cs
Labels: PR: Needs +2

#17496 Fix naming in editor
  OpenRA.Mods.Common/Widgets/Logic/Editor/ActorEditLogic.cs
Labels: PR: Needs +2

#17454 Fix ReloadAmmoPool.ResetFire ignoring multipliers
  OpenRA.Mods.Common/Traits/ReloadAmmoPool.cs
Labels: PR: Needs +2

#17338 Add support for defining the palette of WithResourceLevelOverlay
  OpenRA.Mods.Common/Traits/Render/WithResourceLevelOverlay.cs
Labels: PR: Needs +2

#17475 Make the command bar directly check if a GuardOrderGenerator is active
  OpenRA.Mods.Common/Widgets/Logic/Ingame/CommandBarLogic.cs
Labels: PR: Needs +2

#17576 Restore red lines for harvester targets.
  OpenRA.Mods.Common/Activities/FindAndDeliverResources.cs
  OpenRA.Mods.Common/Activities/HarvestResource.cs
Labels: PR: For stable, PR: Needs +2

#17420 Prevent cell triggers in sarin-gas-2 from firing several times
  mods/ra/maps/sarin-gas-2-down-under/downunder.lua
Labels: PR: For stable, PR: Needs +2

#17561 Fix cargo initialisation
  OpenRA.Mods.Common/Traits/Cargo.cs
Labels: PR: Needs +2

#17569 Fix the Build function in gdi04b
  mods/cnc/maps/gdi04b/gdi04b.lua
Labels: PR: Needs +2

#17382 Default LocalClientId in ReplayConnection to -1
  OpenRA.Game/Network/ReplayConnection.cs
Labels: PR: Needs +2

#17494 Prepare TD and content installer chrome for fractional DPI/UI scaling
  OpenRA.Mods.Cnc/CncLoadScreen.cs
  mods/cnc/chrome.yaml
  mods/cnc/chrome/ingame.yaml
  mods/cnc/uibits/chrome-2x.png
  mods/cnc/uibits/chrome-3x.png
  mods/cnc/uibits/chrome.png
  mods/cnc/uibits/reticle.png
  mods/modcontent/chrome-2x.png
  mods/modcontent/chrome-3x.png
  mods/modcontent/chrome.png
  mods/modcontent/chrome.yaml
Labels: PR: Is Dependency, PR: Needs +2

#17552 Restore MODIFIER_OVERRIDES handling of unmodified attack move hotkey.
  OpenRA.Mods.Common/Widgets/Logic/Ingame/CommandBarLogic.cs
Labels: PR: For stable, PR: Needs +2

#17566 Fix Texture.GetData under GLES.
  OpenRA.Platforms.Default/OpenGL.cs
  OpenRA.Platforms.Default/Texture.cs
Labels: PR: Needs +2

#17495 Prepare RA chrome for fractional DPI/UI scaling
  OpenRA.Mods.Common/LoadScreens/LogoStripeLoadScreen.cs
  mods/common/chrome/assetbrowser.yaml
  mods/common/chrome/ingame-observer.yaml
  mods/common/chrome/lobby-music.yaml
  mods/common/chrome/musicplayer.yaml
  mods/d2k/chrome.yaml
  mods/ra/chrome.yaml
  mods/ra/chrome/ingame-observer.yaml
  mods/ra/chrome/ingame-player.yaml
  mods/ra/uibits/buttons.png
  mods/ra/uibits/chrome.png
  mods/ra/uibits/dialog.png
  mods/ra/uibits/glyphs-2x.png
  mods/ra/uibits/glyphs-3x.png
  mods/ra/uibits/glyphs.png
  mods/ra/uibits/loadscreen-2x.png
  mods/ra/uibits/loadscreen-3x.png
  mods/ra/uibits/loadscreen.png
  mods/ra/uibits/sidebar.png
  mods/ts/chrome.yaml
  mods/ts/chrome/ingame-observer.yaml
Labels: PR: Is Dependency, PR: Needs +2

#17579 Moved the hard-coded shroud palette to the C&C folder
  OpenRA.Mods.Cnc/Traits/World/ShroudPalette.cs
Labels: PR: Needs +2

#17539 Moved the AssetBrowserFileEndingsFilter to IGlobalModData
  OpenRA.Mods.Common/AssetBrowser.cs
  OpenRA.Mods.Common/Widgets/Logic/AssetBrowserLogic.cs
  mods/cnc/chrome/assetbrowser.yaml
  mods/cnc/mod.yaml
  mods/common/chrome/assetbrowser.yaml
  mods/d2k/mod.yaml
  mods/ra/mod.yaml
  mods/ts/mod.yaml
Labels: PR: Needs +2

#16710 Separated resource rendering into another trait
  OpenRA.Mods.Common/Orders/PlaceBuildingOrderGenerator.cs
  OpenRA.Mods.Common/Traits/Buildings/BuildingUtils.cs
  OpenRA.Mods.Common/Traits/Harvester.cs
  OpenRA.Mods.Common/Traits/SeedsResource.cs
  OpenRA.Mods.Common/Traits/World/EditorResourceLayer.cs
  OpenRA.Mods.Common/Traits/World/ResourceLayer.cs
  OpenRA.Mods.Common/Traits/World/ResourceRenderer.cs
  OpenRA.Mods.Common/UpdateRules/Rules/AddResourceRenderer.cs
  OpenRA.Mods.Common/Widgets/ViewportControllerWidget.cs
  OpenRA.Mods.D2k/Traits/SpiceBloom.cs
  OpenRA.Mods.D2k/Traits/World/D2kEditorResourceLayer.cs
  OpenRA.Mods.D2k/Traits/World/D2kResourceRenderer.cs
  mods/cnc/rules/world.yaml
  mods/d2k/rules/world.yaml
  mods/ra/rules/world.yaml
  mods/ts/rules/world.yaml
Labels: PR: Needs +2

#17558 Added cursor palette support to GIMP/Jasc palette definitions
  OpenRA.Mods.Common/Traits/World/PaletteFromGimpOrJascFile.cs
Labels: PR: Needs +2

#17587 Fix missing TD slider tick marks
  mods/cnc/chrome.yaml
Labels: PR: Needs +2

#17585 Let all Positionable traits notify visual position changes
  OpenRA.Mods.Cnc/Traits/TDGunboat.cs
  OpenRA.Mods.Common/Traits/Crates/Crate.cs
  OpenRA.Mods.Common/Traits/Husk.cs
Labels: PR: Needs +2

#17501 Use template chooser with new issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/crash-report.md
  .github/ISSUE_TEMPLATE/feature---enhancement-request.md
Labels: PR: Needs +2

#17504 Prepare D2k chrome for fractional DPI/UI scaling
  mods/d2k/chrome.yaml
  mods/d2k/chrome/ingame-player.yaml
  mods/d2k/uibits/buttons.png
  mods/d2k/uibits/chrome.png
  mods/d2k/uibits/dialog.png
  mods/d2k/uibits/glyphs-2x.png
  mods/d2k/uibits/glyphs-3x.png
  mods/d2k/uibits/glyphs.png
  mods/d2k/uibits/loadscreen-2x.png
  mods/d2k/uibits/loadscreen-3x.png
  mods/d2k/uibits/loadscreen.png
Labels: PR: Is Dependency, PR: Needs +2

#17506 Prepare TS chrome for fractional DPI/UI scaling
  mods/ts/chrome.yaml
  mods/ts/chrome/ingame-player.yaml
  mods/ts/uibits/buttons.png
  mods/ts/uibits/dialog.png
  mods/ts/uibits/glyphs-2x.png
  mods/ts/uibits/glyphs-3x.png
  mods/ts/uibits/glyphs.png
  mods/ts/uibits/loadscreen.png
Labels: PR: Is Dependency, PR: Needs +2

#17119 Warhead refactor part 3: Add WarheadArgs
  OpenRA.Game/Effects/DelayedImpact.cs
  OpenRA.Game/GameRules/WeaponInfo.cs
  OpenRA.Game/Traits/TraitsInterfaces.cs
  OpenRA.Mods.Cnc/Projectiles/IonCannon.cs
  OpenRA.Mods.Cnc/Projectiles/TeslaZap.cs
  OpenRA.Mods.Cnc/Traits/EnergyWall.cs
  OpenRA.Mods.Cnc/Traits/MadTank.cs
  OpenRA.Mods.Common/Activities/Air/FallToEarth.cs
  OpenRA.Mods.Common/Projectiles/AreaBeam.cs
  OpenRA.Mods.Common/Projectiles/Bullet.cs
  OpenRA.Mods.Common/Projectiles/GravityBomb.cs
  OpenRA.Mods.Common/Projectiles/InstantHit.cs
  OpenRA.Mods.Common/Projectiles/LaserZap.cs
  OpenRA.Mods.Common/Projectiles/Missile.cs
  OpenRA.Mods.Common/Projectiles/NukeLaunch.cs
  OpenRA.Mods.Common/Projectiles/Railgun.cs
  OpenRA.Mods.Common/Traits/Buildings/Bridge.cs
  OpenRA.Mods.Common/Traits/Buildings/GroundLevelBridge.cs
  OpenRA.Mods.Common/Traits/Crates/ExplodeCrateAction.cs
  OpenRA.Mods.Common/Traits/Explodes.cs
  OpenRA.Mods.Common/Traits/ExplosionOnDamageTransition.cs
  OpenRA.Mods.Common/Warheads/ChangeOwnerWarhead.cs
  OpenRA.Mods.Common/Warheads/CreateEffectWarhead.cs
  OpenRA.Mods.Common/Warheads/CreateResourceWarhead.cs
  OpenRA.Mods.Common/Warheads/DamageWarhead.cs
  OpenRA.Mods.Common/Warheads/DestroyResourceWarhead.cs
  OpenRA.Mods.Common/Warheads/FireClusterWarhead.cs
  OpenRA.Mods.Common/Warheads/GrantExternalConditionWarhead.cs
  OpenRA.Mods.Common/Warheads/LeaveSmudgeWarhead.cs
  OpenRA.Mods.Common/Warheads/Warhead.cs
  OpenRA.Mods.D2k/Warheads/DamagesConcreteWarhead.cs
Labels: PR: Needs +2

#17608 Add stray update rules to the correct path
  OpenRA.Mods.Common/UpdateRules/Rules/20191117/AddResourceRenderer.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20191117/ReformatChromeProvider.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20191117/RenameSpins.cs
  OpenRA.Mods.Common/UpdateRules/UpdatePath.cs
Labels: PR: Needs +2

#17611 Use proper glyph for in-game chat close button
  mods/common/chrome/ingame-chat.yaml
Labels: PR: Needs +2

#17242 Refactor WithInfantryBody TickIdle code
  OpenRA.Mods.Common/Traits/Render/WithInfantryBody.cs
Labels: PR: Needs +2

#17601 Fix DisguiseTooltip condtionality
  OpenRA.Mods.Cnc/Traits/Disguise.cs
Labels: PR: Needs +2

#17609 Remove old update rules
  OpenRA.Mods.Common/UpdateRules/Rules/20171014/AddNukeLaunchAnimation.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20171014/AircraftCanHoverGeneralization.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20171014/CapturableChanges.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20171014/ChangeBuildableArea.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20171014/ChangeCanPowerDown.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20171014/DecoupleSelfReloading.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20171014/DropPauseAnimationWhenDisabled.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20171014/LegacyBetaWarning.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20171014/MoveVisualBounds.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20171014/RemoveIDisable.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20171014/RemoveMobileOnRails.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20171014/RemoveOutOfAmmo.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20171014/RemovePlayerPaletteTileset.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20171014/RenameBurstDelay.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20171014/RenameWithTurreted.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20171014/ReplaceCanPowerDown.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20171014/ReplaceRequiresPower.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20171014/ReworkCheckboxes.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20171014/ScaleDefaultModHealth.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20171014/ScaleModHealth.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20171014/ScaleModHealthBy10.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20171014/ScaleModHealthBy100.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20171014/ScaleSupportPowerSecondsToTicks.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20171014/SplitGateFromBuilding.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20171014/WarnAboutInfiltrateForTypes.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20180307/AddShakeToBridge.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20180307/ChangeIntensityToDuration.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20180307/DefineGroundCorpseDefault.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20180307/DefineLocomotors.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20180307/DefineOwnerLostAction.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20180307/DefineSoundDefaults.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20180307/DefineSquadExcludeHarvester.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20180307/IgnoreAbstractActors.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20180307/MoveHackyAISupportPowerDecisions.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20180307/RemoveCanUndeployFromGrantConditionOnDeploy.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20180307/RemovePaletteFromCurrentTileset.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20180307/RemoveTerrainTypeIsWaterFlag.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20180307/RemoveWeaponScanRadius.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20180307/RemoveWithReloadingSpriteTurret.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20180307/RenameEmitInfantryOnSell.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20180307/RenameWormSpawner.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20180307/SplitAimAnimations.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20180307/SplitRepairDecoration.cs
  OpenRA.Mods.Common/UpdateRules/UpdatePath.cs
Labels: PR: Needs +2

#17593 Fix horizontal positioning of dropdown arrow glyph.
  OpenRA.Mods.Common/Widgets/DropDownButtonWidget.cs
Labels: PR: Needs +2

#16793 Make GrantConditionOnAttack PausableConditional
  OpenRA.Mods.Common/Traits/Conditions/GrantConditionOnAttack.cs
Labels: PR: Needs +2

#17626 Fix mission specific buildings not granting prerequisites
  mods/ra/maps/allies-05a/rules.yaml
  mods/ra/maps/monster-tank-madness/rules.yaml
Labels: PR: For stable, PR: Needs +2

#17617 Display a confirmation prompt on settings panel reset
  OpenRA.Mods.Common/Widgets/Logic/SettingsLogic.cs
Labels: PR: Needs +2

#17633 Use common notice colors for UPnP status labels
  OpenRA.Mods.Common/Widgets/Logic/ServerCreationLogic.cs
  mods/common/metrics.yaml
Labels: PR: Needs +2

#17629 Fix the description of VeteranProductionIconOverlay
  OpenRA.Mods.Common/Traits/Render/VeteranProductionIconOverlay.cs
Labels: PR: Needs +2
