Repository OpenRA/OpenRA, pull requests merged in 2020-10, with the labels that each got.

#18610 Fix ValidStances of RevealsMap not working
  OpenRA.Mods.Common/Traits/RevealsMap.cs
Labels: PR: Needs +2

#18577 Add support for querying the Passengers of an actor via Lua
  OpenRA.Mods.Common/Scripting/Properties/TransportProperties.cs
Labels: PR: Needs +2

#18481 Let docking angle be determined by the host building.
  OpenRA.Mods.Common/Activities/Air/ReturnToBase.cs
  OpenRA.Mods.Common/Traits/Air/Aircraft.cs
  OpenRA.Mods.Common/UpdateRules/Rules/RemoveTurnToDock.cs
  OpenRA.Mods.Common/UpdateRules/UpdatePath.cs
  mods/cnc/rules/defaults.yaml
  mods/cnc/rules/structures.yaml
  mods/d2k/rules/aircraft.yaml
  mods/ra/rules/aircraft.yaml
  mods/ra/rules/defaults.yaml
  mods/ts/rules/aircraft.yaml
  mods/ts/rules/defaults.yaml
  mods/ts/rules/gdi-structures.yaml
  mods/ts/rules/nod-structures.yaml
Labels: PR: Needs +2

#18661 Fix corrupted final frame in VQA playback.
  OpenRA.Mods.Common/FileFormats/VqaReader.cs
Labels: PR: Needs +2

#18663 Remove an used TerrainTemplateInfo constructor
  OpenRA.Game/Map/TileSet.cs
Labels: PR: Needs +2

#18554 Renamed SmudgeLayer smoke fields and set defaults to zero/null
  OpenRA.Mods.Common/Traits/World/SmudgeLayer.cs
  OpenRA.Mods.Common/UpdateRules/Rules/RenameSmudgeSmokeFields.cs
  OpenRA.Mods.Common/UpdateRules/UpdatePath.cs
  mods/cnc/rules/structures.yaml
  mods/cnc/rules/world.yaml
  mods/d2k/rules/world.yaml
  mods/ra/rules/world.yaml
  mods/ts/rules/world.yaml
Labels: PR: Is Dependency, PR: Needs +2

#18671 Fix for bogus aircraft and ships consideration in SquadManagerBotModule
  OpenRA.Mods.Common/Traits/BotModules/SquadManagerBotModule.cs
Labels: PR: Needs +2

#18630 Lock Server.LobbyInfo to prevent races with callback threads.
  OpenRA.Game/Server/Server.cs
  OpenRA.Mods.Common/ServerTraits/LobbyCommands.cs
  OpenRA.Mods.Common/ServerTraits/LobbySettingsNotification.cs
  OpenRA.Mods.Common/ServerTraits/PlayerPinger.cs
Labels: PR: Needs +2

#18676 Fixed a link in the Lua documentation
  OpenRA.Mods.Common/UtilityCommands/ExtractLuaDocsCommand.cs
Labels: PR: Needs +2

#18641 Fix turrets immediately moving from map-defined facing to InitialFacing.
  OpenRA.Mods.Common/Traits/Turreted.cs
Labels: PR: Needs +2

#18679 Fix turreted defenses always realigning
  mods/cnc/rules/structures.yaml
  mods/d2k/rules/structures.yaml
  mods/ra/rules/structures.yaml
  mods/ts/rules/gdi-support.yaml
  mods/ts/rules/nod-support.yaml
  mods/ts/rules/shared-support.yaml
Labels: PR: Needs +2

#18686 Fix d2k conyards granting an unconsumed "auto-concrete" condition
  mods/d2k/rules/structures.yaml
Labels: PR: Needs +2

#18675 Support List<> for FieldSaver/FieldLoader
  OpenRA.Game/FieldLoader.cs
  OpenRA.Game/FieldSaver.cs
Labels: PR: Needs +2

#18667 Remove unnecessary allocations from spawn point rendering
  OpenRA.Mods.Common/Widgets/Logic/Lobby/LobbyLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Lobby/LobbyUtils.cs
  OpenRA.Mods.Common/Widgets/Logic/Lobby/MapPreviewLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Lobby/SpawnSelectorTooltipLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/ReplayBrowserLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/ServerListLogic.cs
  OpenRA.Mods.Common/Widgets/MapPreviewWidget.cs
Labels: PR: Is Dependency, PR: Needs +2

#18692 Avoid WaterCheck game crash in base builder
  OpenRA.Mods.Common/AIUtils.cs
  OpenRA.Mods.Common/Traits/BotModules/BotModuleLogic/BaseBuilderQueueManager.cs
Labels: PR: Needs +2

#18697 Fix a crash in AIUtils
  OpenRA.Mods.Common/AIUtils.cs
Labels: PR: Needs +2

#18702 Use TileSet ID in sequences instead of the TileSet object.
  OpenRA.Game/GameRules/Ruleset.cs
  OpenRA.Game/Graphics/SequenceProvider.cs
  OpenRA.Game/ModData.cs
  OpenRA.Mods.Cnc/Graphics/ClassicSpriteSequence.cs
  OpenRA.Mods.Cnc/Graphics/ClassicTilesetSpecificSpriteSequence.cs
  OpenRA.Mods.Common/Graphics/DefaultSpriteSequence.cs
  OpenRA.Mods.Common/Graphics/TilesetSpecificSpriteSequence.cs
Labels: PR: Is Dependency, PR: Needs +2

#18591 Add inline node inclusion support to mod.yaml.
  OpenRA.Game/Manifest.cs
Labels: PR: Needs +2

#18706 Fix Pillbox damage
  mods/ra/weapons/smallcaliber.yaml
Labels: PR: Needs +2

#18707 Yaml Memory Improvements
  OpenRA.Game/Exts.cs
  OpenRA.Game/Map/MapCache.cs
  OpenRA.Game/Map/MapPreview.cs
  OpenRA.Game/MiniYaml.cs
Labels: PR: Needs +2

#18708 Threaded Renderer improvements
  OpenRA.Game/Graphics/PlatformInterfaces.cs
  OpenRA.Game/Graphics/TerrainSpriteLayer.cs
  OpenRA.Platforms.Default/ThreadedGraphicsContext.cs
  OpenRA.Platforms.Default/VertexBuffer.cs
Labels: PR: Needs +2

#18672 Rewrite spawn point assignment logic.
  OpenRA.Game/GameInformation.cs
  OpenRA.Game/Map/PlayerReference.cs
  OpenRA.Game/Player.cs
  OpenRA.Game/Traits/TraitsInterfaces.cs
  OpenRA.Game/World.cs
  OpenRA.Mods.Common/Scripting/Properties/PlayerProperties.cs
  OpenRA.Mods.Common/Traits/Buildings/ProductionAirdrop.cs
  OpenRA.Mods.Common/Traits/World/MPStartLocations.cs
  OpenRA.Mods.Common/Traits/World/SpawnMPUnits.cs
Labels: PR: Is Dependency, PR: Needs +2

#18703 Removed effective owner check in ChooseArmamentsForTarget
  OpenRA.Mods.Common/Traits/Attack/AttackBase.cs
Labels: PR: Needs +2

#18699 Fixed "Attempted to get trait from destroyed object" in *OrderGenerator.SelectionChanged
  OpenRA.Mods.Cnc/Traits/Minelayer.cs
  OpenRA.Mods.Common/Orders/GuardOrderGenerator.cs
  OpenRA.Mods.Common/Traits/AttackMove.cs
Labels: PR: Needs +2

#18654 TD Balance 2020 #3
  mods/cnc/rules/aircraft.yaml
  mods/cnc/rules/defaults.yaml
  mods/cnc/rules/husks.yaml
  mods/cnc/rules/infantry.yaml
  mods/cnc/rules/structures.yaml
  mods/cnc/rules/tech.yaml
  mods/cnc/rules/vehicles.yaml
  mods/cnc/rules/world.yaml
  mods/cnc/weapons/ballistics.yaml
  mods/cnc/weapons/missiles.yaml
  mods/cnc/weapons/other.yaml
  mods/cnc/weapons/smallcaliber.yaml
Labels: PR: Needs +2

#18687 Checkbox for Stealth C17
  mods/cnc/rules/aircraft.yaml
  mods/cnc/rules/player.yaml
Labels: PR: Needs +2

#18161 Fix units not attack moving to waypoints after resupply/takeoff
  OpenRA.Mods.Common/Activities/Resupply.cs
  OpenRA.Mods.Common/Traits/Buildings/Reservable.cs
Labels: PR: Needs +2

#18736 Fix a divide by zero crash in Move.
  OpenRA.Mods.Common/Activities/Move/Move.cs
Labels: PR: Needs +2

#18716 Make the calculation of DesiredLocalFacing more readable
  OpenRA.Mods.Common/Traits/Turreted.cs
Labels: PR: Needs +2

#18607 Fixed use of unintialized field in CursorSequence.
  OpenRA.Game/Graphics/CursorSequence.cs
Labels: PR: Needs +2

#17919 Fixed range circles not being completely configurable
  OpenRA.Mods.Cnc/Traits/PortableChrono.cs
  OpenRA.Mods.Cnc/Traits/SupportPowers/AttackOrderPower.cs
  OpenRA.Mods.Common/Graphics/DetectionCircleAnnotationRenderable.cs
  OpenRA.Mods.Common/Graphics/RangeCircleAnnotationRenderable.cs
  OpenRA.Mods.Common/Traits/Buildings/BaseProvider.cs
  OpenRA.Mods.Common/Traits/Render/RenderDetectionCircle.cs
  OpenRA.Mods.Common/Traits/Render/RenderJammerCircle.cs
  OpenRA.Mods.Common/Traits/Render/RenderRangeCircle.cs
  OpenRA.Mods.Common/Traits/Render/RenderShroudCircle.cs
  OpenRA.Mods.Common/Traits/Render/WithRangeCircle.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20200503/RenameCircleOutline.cs
  OpenRA.Mods.Common/UpdateRules/UpdatePath.cs
Labels: PR: Needs +2

#18698 Remove trait queries from Actor ctor.
  OpenRA.Game/Actor.cs
Labels: PR: Needs +2

#18718 Fix WithRangeCircle when Visibility is set to Always
  OpenRA.Mods.Common/Traits/Render/WithRangeCircle.cs
Labels: PR: Needs +2

#18701 Remove obsolete LocomotorInfo caching.
  OpenRA.Mods.Common/Activities/FindAndDeliverResources.cs
  OpenRA.Mods.Common/Activities/Move/MoveAdjacentTo.cs
  OpenRA.Mods.Common/Pathfinder/PathGraph.cs
  OpenRA.Mods.Common/Traits/BotModules/HarvesterBotModule.cs
  OpenRA.Mods.Common/Traits/BotModules/Squads/States/NavyStates.cs
  OpenRA.Mods.Common/Traits/Mobile.cs
  OpenRA.Mods.Common/Traits/ProductionFromMapEdge.cs
  OpenRA.Mods.Common/Traits/World/DomainIndex.cs
  OpenRA.Mods.Common/Traits/World/Locomotor.cs
  OpenRA.Mods.Common/Traits/World/PathFinder.cs
Labels: PR: Is Dependency, PR: Needs +2

#18623 Fix FMV rendering
  OpenRA.Mods.Common/Widgets/VqaPlayerWidget.cs
Labels: PR: Needs +2

#18681 Fixed the list in the Lua API documentation
  OpenRA.Mods.Common/UtilityCommands/ExtractLuaDocsCommand.cs
Labels: PR: Needs +2

#18722 Add DamageTypes to Demolition
  OpenRA.Mods.Common/Activities/Demolish.cs
  OpenRA.Mods.Common/Scripting/Properties/DemolitionProperties.cs
  OpenRA.Mods.Common/Traits/Buildings/Bridge.cs
  OpenRA.Mods.Common/Traits/Buildings/BridgeHut.cs
  OpenRA.Mods.Common/Traits/Buildings/BridgePlaceholder.cs
  OpenRA.Mods.Common/Traits/Buildings/GroundLevelBridge.cs
  OpenRA.Mods.Common/Traits/Buildings/LegacyBridgeHut.cs
  OpenRA.Mods.Common/Traits/Demolishable.cs
  OpenRA.Mods.Common/Traits/Demolition.cs
  OpenRA.Mods.Common/Traits/World/BridgeLayer.cs
  OpenRA.Mods.Common/TraitsInterfaces.cs
Labels: PR: Needs +2

#18688 Support multiple Replaceable and Replacement traits
  OpenRA.Mods.Common/Traits/Buildings/BuildingUtils.cs
  OpenRA.Mods.Common/Traits/Player/PlaceBuilding.cs
  OpenRA.Mods.Common/Traits/Replaceable.cs
  OpenRA.Mods.Common/Traits/Replacement.cs
Labels: PR: Is Dependency, PR: Needs +2

#17843 Added valid TerrainTypes to the Minelayer trait and a configurable deploy cursor
  OpenRA.Mods.Cnc/Traits/Minelayer.cs
  mods/ra/rules/vehicles.yaml
Labels: PR: Is Dependency, PR: Needs +2, PR: Unaddressed comment(s)

#18770 ShroudRenderer UpdateShroud only when at least one cell is dirty.
  OpenRA.Mods.Common/Traits/World/ShroudRenderer.cs
Labels: PR: Needs +2

#18077 Determine stance for spectators based on shroud selection
  OpenRA.Game/Player.cs
Labels: PR: Needs +2

#18680 Add Text Alignment support to SupportPowerTimerWidget
  OpenRA.Mods.Common/Widgets/SupportPowerTimerWidget.cs
Labels: PR: Needs +2

#18357 Replace TraitContainer AllEnumerator.
  OpenRA.Game/TraitDictionary.cs
  OpenRA.Game/World.cs
Labels: PR: Needs +2

#18785 Revert "Determine stance for spectators based on shroud selection"
  OpenRA.Game/Player.cs
Labels: PR: Needs +2

#18710 Fix AI air squad misbehaving in TS maps
  OpenRA.Mods.Common/Traits/BotModules/Squads/States/AirStates.cs
Labels: PR: Needs +2

#18786 vscode debugging: build before launching
  .vscode/launch.json
Labels: PR: Needs +2

#18748 Fix free-of-charge repairing still costing credits
  OpenRA.Mods.Common/Activities/Resupply.cs
Labels: PR: Needs +2

#18696 Support random factions and spawn points in server replays.
  OpenRA.Game/Player.cs
  OpenRA.Game/Server/Server.cs
  OpenRA.Game/Traits/TraitsInterfaces.cs
  OpenRA.Game/World.cs
  OpenRA.Mods.Common/Traits/World/CreateMPPlayers.cs
  OpenRA.Mods.Common/Traits/World/EditorActorLayer.cs
  OpenRA.Mods.Common/Traits/World/MPStartLocations.cs
  OpenRA.Mods.Common/Widgets/Logic/ReplayBrowserLogic.cs
Labels: PR: Needs +2

#18779 Add InvalidBounceTerrain parameter to Projectile
  OpenRA.Mods.Common/Projectiles/Bullet.cs
Labels: PR: Needs +2

#18782 Add support for offset in Explodes
  OpenRA.Mods.Common/Traits/Explodes.cs
Labels: PR: Needs +2
