Repository OpenRA/OpenRA, pull requests merged in 2020-11, with the labels that each got.

#18774 Use tie breaks to determine sort order in WorldRenderer.GenerateRenderables
  OpenRA.Game/Graphics/WorldRenderer.cs
Labels: PR: Needs +2

#18752 Revise the TD Map Pool 2020
  mods/cnc/maps/african-gambit.oramap
  mods/cnc/maps/anvil-of-war.oramap
  mods/cnc/maps/armageddon.oramap
  mods/cnc/maps/avocado.oramap
  mods/cnc/maps/badland-ridges.oramap
  mods/cnc/maps/contra.oramap
  mods/cnc/maps/dead-in-motion.oramap
  mods/cnc/maps/desert-invasion.oramap
  mods/cnc/maps/desert-lakes.oramap
  mods/cnc/maps/desert-mandarins.oramap
  mods/cnc/maps/deserted-outpost.oramap
  mods/cnc/maps/elysian-expanse.oramap
  mods/cnc/maps/fight-win-prevail.oramap
  mods/cnc/maps/frostways.oramap
  mods/cnc/maps/letters-from-lexington.oramap
  mods/cnc/maps/master-alert.oramap
  mods/cnc/maps/master-of-the-jungle-book.oramap
  mods/cnc/maps/plan-b.oramap
  mods/cnc/maps/reaching-out.oramap
  mods/cnc/maps/thawed-front.oramap
  mods/cnc/maps/the-new-mandarins.oramap
  mods/cnc/maps/tiberium-canopy.oramap
  mods/cnc/maps/tiberium-forest.oramap
  mods/cnc/maps/tiberium-rift.oramap
  mods/cnc/maps/twisted-peak.oramap
  mods/cnc/maps/understanding-power.oramap
  mods/cnc/maps/valley-of-gold-6p.oramap
  mods/cnc/maps/winters-end.oramap
Labels: PR: Needs +2

#18055 Make AI support power target selection less predictable
  OpenRA.Mods.Common/Traits/BotModules/SupportPowerBotModule.cs
Labels: PR: Needs +2

#17920 Added nuke target selection rings
  OpenRA.Mods.Common/Traits/SupportPowers/NukePower.cs
Labels: PR: Needs +2

#18809 Fixed a crash when bullets bounce outside of the map
  OpenRA.Mods.Common/Projectiles/Bullet.cs
Labels: PR: Needs +2

#18810 Fix reservable crashing when unreserving and attack moving
  OpenRA.Mods.Common/Traits/Buildings/Reservable.cs
Labels: PR: Needs +2

#18749 Apply range modifiers to Missile RangeLimit.
  OpenRA.Mods.Common/Projectiles/Missile.cs
Labels: PR: Needs +2

#18425 Add ability to right click on map to disable spawn points
  AUTHORS
  OpenRA.Game/GameInformation.cs
  OpenRA.Game/Network/GameServer.cs
  OpenRA.Game/Network/Session.cs
  OpenRA.Game/World.cs
  OpenRA.Mods.Common/ServerTraits/LobbyCommands.cs
  OpenRA.Mods.Common/Traits/World/MPStartLocations.cs
  OpenRA.Mods.Common/Widgets/Logic/Lobby/LobbyLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Lobby/LobbyUtils.cs
  OpenRA.Mods.Common/Widgets/Logic/Lobby/MapPreviewLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Lobby/SpawnSelectorTooltipLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/ReplayBrowserLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/ServerListLogic.cs
  OpenRA.Mods.Common/Widgets/MapPreviewWidget.cs
  mods/cnc/chrome.yaml
  mods/cnc/uibits/chrome-2x.png
  mods/cnc/uibits/chrome-3x.png
  mods/cnc/uibits/chrome.png
  mods/d2k/chrome.yaml
  mods/d2k/uibits/glyphs-2x.png
  mods/d2k/uibits/glyphs-3x.png
  mods/d2k/uibits/glyphs.png
  mods/ra/chrome.yaml
  mods/ra/uibits/glyphs-2x.png
  mods/ra/uibits/glyphs-3x.png
  mods/ra/uibits/glyphs.png
  mods/ts/chrome.yaml
  mods/ts/uibits/glyphs-2x.png
  mods/ts/uibits/glyphs-3x.png
  mods/ts/uibits/glyphs.png
Labels: PR: Fixup requested, PR: Needs +2

#18815 Fix angles in the Descriptions of TDGunboat
  OpenRA.Mods.Cnc/Traits/TDGunboat.cs
Labels: PR: Needs +2

#18787 Fix speech notifications not playing in some SupportPowers when selecting a target.
  OpenRA.Mods.Cnc/Traits/SupportPowers/AttackOrderPower.cs
  OpenRA.Mods.Cnc/Traits/SupportPowers/ChronoshiftPower.cs
  OpenRA.Mods.Common/Traits/SupportPowers/AirstrikePower.cs
  OpenRA.Mods.Common/Traits/SupportPowers/GrantExternalConditionPower.cs
  OpenRA.Mods.Common/Traits/SupportPowers/NukePower.cs
  OpenRA.Mods.Common/Traits/SupportPowers/ParatroopersPower.cs
  OpenRA.Mods.Common/Traits/SupportPowers/SupportPower.cs
  OpenRA.Mods.Common/Traits/SupportPowers/SupportPowerManager.cs
Labels: PR: Needs +2

#18483 Expose targetline colors to yaml
  OpenRA.Game/Traits/TraitsInterfaces.cs
  OpenRA.Mods.Cnc/Activities/Infiltrate.cs
  OpenRA.Mods.Cnc/Activities/LayMines.cs
  OpenRA.Mods.Cnc/Scripting/Properties/InfiltrateProperties.cs
  OpenRA.Mods.Cnc/Traits/Infiltration/Infiltrates.cs
  OpenRA.Mods.Cnc/Traits/Minelayer.cs
  OpenRA.Mods.Cnc/Traits/PortableChrono.cs
  OpenRA.Mods.Cnc/Traits/TDGunboat.cs
  OpenRA.Mods.Common/Activities/Air/ReturnToBase.cs
  OpenRA.Mods.Common/Activities/CaptureActor.cs
  OpenRA.Mods.Common/Activities/DeliverResources.cs
  OpenRA.Mods.Common/Activities/DeliverUnit.cs
  OpenRA.Mods.Common/Activities/Demolish.cs
  OpenRA.Mods.Common/Activities/DonateCash.cs
  OpenRA.Mods.Common/Activities/DonateExperience.cs
  OpenRA.Mods.Common/Activities/FindAndDeliverResources.cs
  OpenRA.Mods.Common/Activities/HarvestResource.cs
  OpenRA.Mods.Common/Activities/PickupUnit.cs
  OpenRA.Mods.Common/Activities/RepairBridge.cs
  OpenRA.Mods.Common/Activities/RepairBuilding.cs
  OpenRA.Mods.Common/Activities/Resupply.cs
  OpenRA.Mods.Common/Activities/RideTransport.cs
  OpenRA.Mods.Common/Scripting/Properties/CaptureProperties.cs
  OpenRA.Mods.Common/Scripting/Properties/DeliveryProperties.cs
  OpenRA.Mods.Common/Scripting/Properties/DemolitionProperties.cs
  OpenRA.Mods.Common/Scripting/Properties/MobileProperties.cs
  OpenRA.Mods.Common/Traits/Air/Aircraft.cs
  OpenRA.Mods.Common/Traits/AttackMove.cs
  OpenRA.Mods.Common/Traits/Buildings/TransformsIntoMobile.cs
  OpenRA.Mods.Common/Traits/Captures.cs
  OpenRA.Mods.Common/Traits/Carryall.cs
  OpenRA.Mods.Common/Traits/DeliversCash.cs
  OpenRA.Mods.Common/Traits/DeliversExperience.cs
  OpenRA.Mods.Common/Traits/Demolition.cs
  OpenRA.Mods.Common/Traits/EngineerRepair.cs
  OpenRA.Mods.Common/Traits/EntersTunnels.cs
  OpenRA.Mods.Common/Traits/Guard.cs
  OpenRA.Mods.Common/Traits/Harvester.cs
  OpenRA.Mods.Common/Traits/Mobile.cs
  OpenRA.Mods.Common/Traits/Passenger.cs
  OpenRA.Mods.Common/Traits/RepairsBridges.cs
Labels: PR: Needs +2

#18762 Shroud, access ProjectedCellLayer by array index over PPos index.
  OpenRA.Game/Map/ProjectedCellLayer.cs
  OpenRA.Game/Traits/Player/Shroud.cs
Labels: PR: Needs +2

#18775 Tooltip remains after leaving/switching the menu - fix #18301
  OpenRA.Mods.Common/Widgets/Logic/Ingame/IngameMenuLogic.cs
Labels: PR: Needs +2

#18830 Fix TD Repair Times for Vehicles
  mods/cnc/rules/vehicles.yaml
Labels: PR: Needs +2

#18772 Always mark defeated/victorious players as spectating
  OpenRA.Game/Player.cs
  OpenRA.Mods.Common/Traits/Player/MissionObjectives.cs
Labels: PR: Needs +2

#18829 TD Veterancy Adjustment
  mods/cnc/rules/defaults.yaml
Labels: PR: Needs +2

#18831 Fix WithVoxelBarrel orientation calculations.
  OpenRA.Mods.Common/Traits/Render/WithVoxelBarrel.cs
Labels: PR: Needs +2

#18827 Remove WorldUtils.AreMutualAllies
  OpenRA.Game/WorldUtils.cs
  OpenRA.Mods.Common/Traits/Player/StrategicVictoryConditions.cs
  OpenRA.Mods.Common/Traits/ProximityCapturable.cs
  OpenRA.Mods.Common/Widgets/StrategicProgressWidget.cs
Labels: PR: Needs +2

#18737 Fix multiple harvester dock sequence bugs
  OpenRA.Mods.Cnc/Activities/VoxelHarvesterDockSequence.cs
  OpenRA.Mods.Common/Activities/HarvesterDockSequence.cs
  OpenRA.Mods.Common/Activities/SpriteHarvesterDockSequence.cs
Labels: PR: Needs +2, PR: Unaddressed comment(s)

#18769 Make `OrderGenerator` flexible on mouse input for modder
  OpenRA.Mods.Common/Orders/OrderGenerator.cs
Labels: PR: Needs +2

#18387 Add itch app compatible portable builds
  packaging/.itch.toml
  packaging/upload-itch.sh
  packaging/windows/buildpackage.sh
Labels: PR: Needs +2

#18821 Fix TransformsIntoAircraft transforming on all orders
  OpenRA.Mods.Common/Traits/Buildings/TransformsIntoAircraft.cs
Labels: PR: Needs +2

#18832 Expose TransformsInto* targetline colors to yaml.
  OpenRA.Mods.Common/Traits/Buildings/TransformsIntoAircraft.cs
  OpenRA.Mods.Common/Traits/Buildings/TransformsIntoEntersTunnels.cs
  OpenRA.Mods.Common/Traits/Buildings/TransformsIntoPassenger.cs
  OpenRA.Mods.Common/Traits/Buildings/TransformsIntoRepairable.cs
  OpenRA.Mods.Common/Traits/Buildings/TransformsIntoTransforms.cs
Labels: PR: Needs +2

#18863 Fix production exit desync.
  OpenRA.Mods.Common/Traits/Buildings/Exit.cs
Labels: PR: Needs +2

#18873 Moved FixedColorPalette to the correct folder
  OpenRA.Game/Traits/World/FixedColorPalette.cs
Labels: PR: Needs +2

#18856 Convert Attack*.FacingTolerance to WAngle.
  OpenRA.Mods.Common/Activities/Air/FlyAttack.cs
  OpenRA.Mods.Common/Activities/Attack.cs
  OpenRA.Mods.Common/Traits/Air/AttackAircraft.cs
  OpenRA.Mods.Common/Traits/Air/AttackBomber.cs
  OpenRA.Mods.Common/Traits/Attack/AttackBase.cs
  OpenRA.Mods.Common/Traits/Attack/AttackFollow.cs
  OpenRA.Mods.Common/Traits/Attack/AttackFrontal.cs
  OpenRA.Mods.Common/Traits/AutoTarget.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20200503/ReplaceFacingAngles.cs
  OpenRA.Mods.Common/Util.cs
  mods/cnc/rules/aircraft.yaml
  mods/ra/rules/aircraft.yaml
  mods/ra/rules/vehicles.yaml
  mods/ts/rules/aircraft.yaml
Labels: PR: Needs +2
