Repository OpenRA/OpenRA, pull requests merged in 2020-04, with the labels that each got.

#17890 Fix tile errors on the map "Pie of Animosity"
  mods/ra/maps/pie-of-animosity.oramap
Labels: PR: For stable, PR: Needs +2

#17872 Fix a yaml error in GDI08a
  mods/cnc/maps/gdi08a/rules.yaml
Labels: PR: For stable, PR: Needs +2

#17809 Add Creeps as enemy in all D2k missions
  mods/d2k/maps/atreides-05/map.yaml
  mods/d2k/maps/harkonnen-01a/map.yaml
  mods/d2k/maps/harkonnen-01b/map.yaml
  mods/d2k/maps/harkonnen-02a/map.yaml
  mods/d2k/maps/harkonnen-02b/map.yaml
  mods/d2k/maps/harkonnen-03a/map.yaml
  mods/d2k/maps/harkonnen-03b/map.yaml
  mods/d2k/maps/harkonnen-04/map.yaml
  mods/d2k/maps/harkonnen-05/map.yaml
  mods/d2k/maps/harkonnen-06a/map.yaml
  mods/d2k/maps/harkonnen-06b/map.yaml
  mods/d2k/maps/harkonnen-07/map.yaml
  mods/d2k/maps/harkonnen-08/map.yaml
  mods/d2k/maps/harkonnen-09a/map.yaml
  mods/d2k/maps/harkonnen-09b/map.yaml
  mods/d2k/maps/ordos-01a/map.yaml
  mods/d2k/maps/ordos-01b/map.yaml
  mods/d2k/maps/ordos-02a/map.yaml
  mods/d2k/maps/ordos-02b/map.yaml
  mods/d2k/maps/ordos-03a/map.yaml
  mods/d2k/maps/ordos-03b/map.yaml
  mods/d2k/maps/ordos-04/map.yaml
  mods/d2k/maps/ordos-05/map.yaml
Labels: PR: Needs +2

#17763 Cache PlayerResources and unit cost in Resupply
  OpenRA.Mods.Common/Activities/Resupply.cs
Labels: PR: Needs +2

#17914 Added lint testing to production door overlays
  OpenRA.Mods.Common/Traits/Render/WithProductionDoorOverlay.cs
Labels: PR: Needs +2

#17896 Added a lint check for production bar types
  OpenRA.Mods.Common/Traits/Render/ProductionBar.cs
Labels: PR: Needs +2

#17921 Fix mine layer desync.
  OpenRA.Mods.Cnc/Activities/LayMines.cs
  OpenRA.Mods.Cnc/Traits/Minelayer.cs
Labels: PR: For stable, PR: Needs +2

#17925 Modify preset colors to not get flagged by color validator
  mods/cnc/mod.yaml
  mods/d2k/mod.yaml
  mods/ra/mod.yaml
  mods/ts/mod.yaml
Labels: PR: For stable, PR: Needs +2

#17902 Fixed a crash when multiple ResourceRenderer traits are used
  OpenRA.Mods.Common/Widgets/ViewportControllerWidget.cs
Labels: PR: Needs +2

#17944 Block profiles with revoked keys from joining auth-only servers.
  OpenRA.Game/Server/Server.cs
Labels: PR: For stable, PR: Needs +2

#17946 Fix map-specific factions remaining selected when changing map.
  OpenRA.Mods.Common/ServerTraits/LobbyCommands.cs
Labels: PR: Needs +2

#17934 Work around and explain color picker conversion issue.
  OpenRA.Mods.Common/Widgets/Logic/ColorPickerLogic.cs
Labels: PR: For stable, PR: Needs +2

#17927 Fix transit-only resupply stuck loop and force fire pathing
  OpenRA.Mods.Common/Activities/Move/Move.cs
  OpenRA.Mods.Common/Activities/Move/MoveAdjacentTo.cs
  OpenRA.Mods.Common/Activities/Move/MoveWithinRange.cs
  OpenRA.Mods.Common/Activities/Resupply.cs
  OpenRA.Mods.Common/Traits/Mobile.cs
Labels: PR: For stable, PR: Needs +2

#17957 Change all instances of ToLower() to ToLowerInvariant()
  OpenRA.Mods.Common/Lint/CheckActorReferences.cs
  OpenRA.Mods.Common/Traits/Buildings/FreeActorWithDelivery.cs
  OpenRA.Mods.Common/UtilityCommands/ImportLegacyMapCommand.cs
  OpenRA.Mods.D2k/UtilityCommands/D2kMapImporter.cs
Labels: PR: Needs +2

#17909 Remove Game.HasInputFocus
  OpenRA.Game/Game.cs
  OpenRA.Game/Graphics/PlatformInterfaces.cs
  OpenRA.Game/Renderer.cs
  OpenRA.Mods.Common/Widgets/ViewportControllerWidget.cs
  OpenRA.Platforms.Default/Sdl2Input.cs
  OpenRA.Platforms.Default/Sdl2PlatformWindow.cs
Labels: PR: Needs +2

#17955 Treat transit-only tiles as invalid locations for minelayers
  OpenRA.Mods.Cnc/Activities/LayMines.cs
  OpenRA.Mods.Cnc/Traits/Minelayer.cs
Labels: PR: For stable, PR: Needs +2

#17718 Added a map reveal trait
  OpenRA.Mods.Common/Traits/RevealsMap.cs
Labels: PR: Needs +2

#17720 Fixed the TS/RA2 LegacyTilesetImporter
  OpenRA.Mods.Cnc/UtilityCommands/LegacyTilesetImporter.cs
Labels: PR: Needs +2

#17965 Added a bounds check to LeavesTrails
  OpenRA.Mods.Common/Traits/Render/LeavesTrails.cs
Labels: PR: Needs +2

#17967 Fix a crash when completing objectives in Allies06 out of order
  mods/ra/maps/allies-06a/allies06a.lua
  mods/ra/maps/allies-06a/map.yaml
  mods/ra/maps/allies-06b/allies06b.lua
  mods/ra/maps/allies-06b/map.yaml
Labels: PR: For stable, PR: Needs +2

#17785 Clarified ScaredyCat AttackPanicChance and added PanicChance
  OpenRA.Mods.Common/Traits/Infantry/ScaredyCat.cs
Labels: PR: Needs +2

#17968 Moved Render*Circle traits to their base traits
  OpenRA.Mods.Common/Traits/Render/RenderJammerCircle.cs
  OpenRA.Mods.Common/Traits/Render/RenderShroudCircle.cs
Labels: PR: Needs +2

#17983 Correct the support dir location in ExtractSettingsDocsCommand
  OpenRA.Mods.Common/UtilityCommands/ExtractSettingsDocsCommand.cs
Labels: PR: For stable, PR: Needs +2

#17862 Restore missing minelayer pips.
  mods/ra/rules/vehicles.yaml
Labels: PR: Needs +2

#17991 Include selection decorations when calculating ScreenMap bounds.
  OpenRA.Mods.Common/Traits/Render/IsometricSelectionDecorations.cs
  OpenRA.Mods.Common/Traits/Render/SelectionDecorations.cs
Labels: PR: Is Dependency

#17976 Added target checks for ChangeOwnerWarhead
  OpenRA.Mods.Common/Warheads/ChangeOwnerWarhead.cs
Labels: PR: Needs +2
