Repository OpenRA/OpenRA, pull requests merged in 2021-02, with the labels that each got.

#19112 Use version from VERSION file for install-linux-shortcuts
  Makefile
Labels: PR: For stable, PR: Needs +2

#19118 Fix Tanya's prone firing animations.
  mods/ra/sequences/infantry.yaml
Labels: PR: For stable, PR: Needs +2

#19129 Rename remaining Stance references to PlayerRelationship.
  OpenRA.Game/Player.cs
  OpenRA.Game/Traits/TraitsInterfaces.cs
  OpenRA.Mods.Cnc/Traits/Disguise.cs
  OpenRA.Mods.Cnc/Traits/Infiltration/InfiltrateForDecoration.cs
  OpenRA.Mods.Cnc/Traits/Infiltration/Infiltrates.cs
  OpenRA.Mods.Common/Activities/CaptureActor.cs
  OpenRA.Mods.Common/Activities/RepairBuilding.cs
  OpenRA.Mods.Common/Effects/RevealShroudEffect.cs
  OpenRA.Mods.Common/Graphics/IsometricSelectionBarsAnnotationRenderable.cs
  OpenRA.Mods.Common/Graphics/SelectionBarsAnnotationRenderable.cs
  OpenRA.Mods.Common/Projectiles/Bullet.cs
  OpenRA.Mods.Common/Projectiles/Missile.cs
  OpenRA.Mods.Common/Traits/Attack/AttackBase.cs
  OpenRA.Mods.Common/Traits/AutoTarget.cs
  OpenRA.Mods.Common/Traits/BotModules/CaptureManagerBotModule.cs
  OpenRA.Mods.Common/Traits/CaptureManager.cs
  OpenRA.Mods.Common/Traits/Conditions/ProximityExternalCondition.cs
  OpenRA.Mods.Common/Traits/CreatesShroud.cs
  OpenRA.Mods.Common/Traits/DeliversCash.cs
  OpenRA.Mods.Common/Traits/DeliversExperience.cs
  OpenRA.Mods.Common/Traits/Demolition.cs
  OpenRA.Mods.Common/Traits/EngineerRepair.cs
  OpenRA.Mods.Common/Traits/GivesBounty.cs
  OpenRA.Mods.Common/Traits/GivesExperience.cs
  OpenRA.Mods.Common/Traits/Modifiers/FrozenUnderFog.cs
  OpenRA.Mods.Common/Traits/Modifiers/HiddenUnderShroud.cs
  OpenRA.Mods.Common/Traits/Radar/AppearsOnRadar.cs
  OpenRA.Mods.Common/Traits/Render/CashTricklerBar.cs
  OpenRA.Mods.Common/Traits/Render/SupportPowerChargeBar.cs
  OpenRA.Mods.Common/Traits/Render/WithDecorationBase.cs
  OpenRA.Mods.Common/Traits/Render/WithRangeCircle.cs
  OpenRA.Mods.Common/Traits/RevealsMap.cs
  OpenRA.Mods.Common/Traits/RevealsShroud.cs
  OpenRA.Mods.Common/Traits/Sound/VoiceAnnouncement.cs
  OpenRA.Mods.Common/Traits/SupportPowers/GrantExternalConditionPower.cs
  OpenRA.Mods.Common/Traits/Tooltip.cs
  OpenRA.Mods.Common/Traits/TooltipDescription.cs
  OpenRA.Mods.Common/Warheads/CreateEffectWarhead.cs
  OpenRA.Mods.Common/Warheads/Warhead.cs
  OpenRA.Mods.Common/Widgets/SupportPowerTimerWidget.cs
Labels: PR: Needs +2

#19127 BarrelExplode visual improvements
  mods/ra/weapons/explosions.yaml
Labels: PR: Needs +2

#19132 Fix deployed Tick Tank sprites
  mods/ts/bits/gatick.shp
  mods/ts/bits/gatickmk.shp
  mods/ts/bits/gttick.shp
  mods/ts/bits/gttickmk.shp
Labels: PR: Needs +2

#18948 Split settings panels logic and add support for custom panels
  OpenRA.Mods.Common/Widgets/Logic/IntroductionPromptLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Settings/AdvancedSettingsLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Settings/AudioSettingsLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Settings/DisplaySettingsLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Settings/HotkeysSettingsLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Settings/InputSettingsLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Settings/SettingsLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Settings/SettingsUtils.cs
  OpenRA.Mods.Common/Widgets/Logic/SettingsLogic.cs
  mods/cnc/chrome/settings-advanced.yaml
  mods/cnc/chrome/settings-audio.yaml
  mods/cnc/chrome/settings-display.yaml
  mods/cnc/chrome/settings-hotkeys.yaml
  mods/cnc/chrome/settings-input.yaml
  mods/cnc/chrome/settings.yaml
  mods/cnc/mod.yaml
  mods/common/chrome/settings-advanced.yaml
  mods/common/chrome/settings-audio.yaml
  mods/common/chrome/settings-display.yaml
  mods/common/chrome/settings-hotkeys.yaml
  mods/common/chrome/settings-input.yaml
  mods/common/chrome/settings.yaml
  mods/d2k/mod.yaml
  mods/ra/mod.yaml
  mods/ts/mod.yaml
Labels: PR: Needs +2

#19142 APC Balance Tweak
  mods/cnc/rules/vehicles.yaml
Labels: PR: For stable, PR: Needs +2

#18942 Remove custom palettes from building placement previews.
  OpenRA.Mods.Common/Traits/Buildings/ActorPreviewPlaceBuildingPreview.cs
  OpenRA.Mods.Common/Traits/Buildings/FootprintPlaceBuildingPreview.cs
  OpenRA.Mods.Common/Traits/Buildings/SequencePlaceBuildingPreview.cs
  OpenRA.Mods.Common/Traits/World/EditorSelectionLayer.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20201213/RemovePlaceBuildingPalette.cs
  OpenRA.Mods.Common/UpdateRules/UpdatePath.cs
  OpenRA.Mods.D2k/Traits/Buildings/D2kActorPreviewPlaceBuildingPreview.cs
  mods/cnc/rules/campaign-palettes.yaml
  mods/cnc/rules/defaults.yaml
  mods/cnc/rules/palettes.yaml
  mods/cnc/rules/structures.yaml
  mods/d2k/rules/campaign-palettes.yaml
  mods/d2k/rules/defaults.yaml
  mods/d2k/rules/palettes.yaml
  mods/d2k/rules/structures.yaml
  mods/ra/rules/campaign-palettes.yaml
  mods/ra/rules/defaults.yaml
  mods/ra/rules/fakes.yaml
  mods/ra/rules/palettes.yaml
  mods/ra/rules/structures.yaml
  mods/ts/rules/defaults.yaml
  mods/ts/rules/palettes.yaml
  mods/ts/rules/world.yaml
Labels: PR: Needs +2

#19145 Add clarifying objective to Monster Tank Madness
  mods/ra/maps/monster-tank-madness/monster-tank-madness.lua
Labels: PR: For stable, PR: Needs +2

#19066 Improve shroud performance
  OpenRA.Game/Map/ProjectedCellLayer.cs
  OpenRA.Game/Traits/Player/Shroud.cs
Labels: PR: Needs +2

#19068 Add InitialActor to Carryall.
  OpenRA.Mods.Common/Traits/Carryall.cs
Labels: PR: Needs +2

#18820 Remove GenericSelectTarget
  OpenRA.Game/Orders/GenericSelectTarget.cs
  OpenRA.Mods.Common/Orders/GuardOrderGenerator.cs
Labels: PR: Needs +2

#18458 Added UI cursor configuration to chrome metric
  OpenRA.Game/Game.cs
  OpenRA.Game/Orders/UnitOrderGenerator.cs
  OpenRA.Game/Widgets/Widget.cs
  OpenRA.Mods.Common/Orders/PlaceBuildingOrderGenerator.cs
  OpenRA.Mods.Common/Widgets/ButtonWidget.cs
  OpenRA.Mods.Common/Widgets/RadarWidget.cs
  mods/common/metrics.yaml
Labels: PR: Needs +2

#19021 Fix. Call EndGame in one place of server main loop. Ensure UPnP port …
  OpenRA.Game/Server/Server.cs
Labels: PR: Needs +2

#19110 Update AppStream metadata for linux packaging
  packaging/linux/openra.metainfo.xml.in
Labels: PR: For stable, PR: Needs +2

#19153 Remove OLDLST campaign overrides.
  OpenRA.Mods.Cnc/Traits/Render/WithRoof.cs
  mods/cnc/bits/lstnew.shp
  mods/cnc/bits/lstnew2.shp
  mods/cnc/bits/scripts/campaign-global.lua
  mods/cnc/maps/cnc64gdi01/map.yaml
  mods/cnc/maps/cnc64gdi01/rules.yaml
  mods/cnc/maps/cnc64gdi01/sequences.yaml
  mods/cnc/maps/funpark01/map.yaml
  mods/cnc/maps/funpark01/rules.yaml
  mods/cnc/maps/funpark01/sequences.yaml
  mods/cnc/maps/gdi01/map.yaml
  mods/cnc/maps/gdi01/rules.yaml
  mods/cnc/maps/gdi01/sequences.yaml
  mods/cnc/maps/gdi02/map.yaml
  mods/cnc/maps/gdi02/rules.yaml
  mods/cnc/maps/gdi02/sequences.yaml
  mods/cnc/maps/gdi06/map.yaml
  mods/cnc/maps/gdi06/rules.yaml
  mods/cnc/maps/gdi06/sequences.yaml
  mods/cnc/maps/gdi07/map.yaml
  mods/cnc/maps/gdi07/rules.yaml
  mods/cnc/maps/gdi07/sequences.yaml
  mods/cnc/rules/defaults.yaml
  mods/cnc/rules/ships.yaml
  mods/cnc/sequences/campaign.yaml
Labels: PR: Needs +2

#19160 Fixed problems with Eluant cutting off special character unicode strings
  OpenRA.Game/OpenRA.Game.csproj
Labels: PR: Is Dependency, PR: Needs +2

#19125 Add MSADPCM audio format decoding support
  OpenRA.Mods.Common/FileFormats/WavReader.cs
Labels: PR: Needs +2

#19161 Fixed D2k VQA videos crashing the game
  OpenRA.Mods.Cnc/FileFormats/VqaReader.cs
Labels: PR: For stable, PR: Needs +2

#19185 Fix TLS error on Win7
  make.ps1
Labels: PR: For stable, PR: Needs +2

#19194 Randomize AI idle harvester scan intervals
  OpenRA.Mods.Common/Traits/BotModules/HarvesterBotModule.cs
Labels: PR: Needs +2
