Repository OpenRA/OpenRA, pull requests merged in 2021-01, with the labels that each got.

#17989 Add support for net 5 for Windows
  .github/workflows/ci.yaml
  .github/workflows/packaging.yml
  INSTALL.md
  Makefile
  OpenRA.Game/Game.cs
  OpenRA.Game/ObjectCreator.cs
  OpenRA.Game/OpenRA.Game.csproj
  OpenRA.Game/Support/AssemblyLoader.cs
  OpenRA.Launcher/OpenRA.Launcher.csproj
  OpenRA.Mods.Cnc/OpenRA.Mods.Cnc.csproj
  OpenRA.Mods.Common/OpenRA.Mods.Common.csproj
  OpenRA.Mods.D2k/OpenRA.Mods.D2k.csproj
  OpenRA.Platforms.Default/OpenRA.Platforms.Default.csproj
  OpenRA.Platforms.Default/ThreadedGraphicsContext.cs
  OpenRA.Server/OpenRA.Server.csproj
  OpenRA.Test/OpenRA.Test.csproj
  OpenRA.Utility/OpenRA.Utility.csproj
  OpenRA.WindowsLauncher/OpenRA.WindowsLauncher.csproj
  OpenRA.sln
  launch-dedicated.sh
  launch-game.sh
  make.ps1
  packaging/.itch.toml
  packaging/functions.sh
  packaging/linux/buildpackage.sh
  packaging/linux/openra-server.appimage.in
  packaging/linux/openra-server.in
  packaging/linux/openra-utility.appimage.in
  packaging/linux/openra.appimage.in
  packaging/linux/openra.in
  packaging/macos/buildpackage.sh
  packaging/macos/launcher-mono.m
  packaging/macos/launcher.m
  packaging/windows/OpenRA.nsi
  packaging/windows/buildpackage.sh
  packaging/windows/fixlauncher.py
  utility.sh
Labels: PR: Needs +2

#18991 Add a friendly type name for Nullable<T>.
  OpenRA.Mods.Common/Util.cs
Labels: PR: For stable, PR: Needs +2

#18989 Prevent Health: 100 from being added to actors.
  OpenRA.Mods.Common/Traits/World/EditorActorPreview.cs
Labels: PR: For stable, PR: Needs +2

#18987 Start rally point lines at the spawn position instead of the exit cell.
  OpenRA.Mods.Common/Effects/RallyPointIndicator.cs
Labels: PR: For stable, PR: Needs +2

#18988 Fix exit priority ordering.
  OpenRA.Mods.Common/Traits/Buildings/Exit.cs
Labels: PR: For stable, PR: Needs +2

#18984 Game no longer crashes when TextFieldWidget sends Enter key press and onSelect action is null.
  OpenRA.Mods.Common/Widgets/Logic/MapChooserLogic.cs
Labels: PR: For stable, PR: Needs +2

#18996 Disable AttackPopupTurreted state changes when paused.
  OpenRA.Mods.Cnc/Traits/Attack/AttackPopupTurreted.cs
Labels: PR: For stable, PR: Needs +2

#18968 Fixed error NU1101: Unable to find package
  .github/workflows/ci.yaml
Labels: PR: For stable, PR: Needs +2

#19017 TD Playtest Balance Tweaks
  mods/cnc/rules/aircraft.yaml
  mods/cnc/rules/defaults.yaml
  mods/cnc/rules/vehicles.yaml
  mods/cnc/weapons/missiles.yaml
  mods/cnc/weapons/smallcaliber.yaml
Labels: PR: For stable, PR: Needs +2

#19005 Group bot AttackMove orders.
  OpenRA.Mods.Common/Traits/BotModules/Squads/States/GroundStates.cs
  OpenRA.Mods.Common/Traits/BotModules/Squads/States/NavyStates.cs
  OpenRA.Mods.Common/Traits/BotModules/Squads/States/ProtectionStates.cs
Labels: PR: For stable, PR: Needs +2

#18973 Add a setting to pause the shellmap.
  OpenRA.Game/Settings.cs
  OpenRA.Game/World.cs
  OpenRA.Mods.Common/Scripting/Global/MapGlobal.cs
  OpenRA.Mods.Common/Widgets/Logic/SettingsLogic.cs
  mods/common/chrome/settings.yaml
  mods/d2k/maps/shellmap/d2k-shellmap.lua
Labels: PR: For stable, PR: Needs +2

#19009 Avoid BuildUnit crash if the item is invalidated before the task runs.
  OpenRA.Mods.Common/Traits/Player/ProductionQueue.cs
Labels: PR: For stable, PR: Needs +2

#18943 Add Aftermath mission Shock Therapy
  mods/ra/maps/shock-therapy/map.bin
  mods/ra/maps/shock-therapy/map.png
  mods/ra/maps/shock-therapy/map.yaml
  mods/ra/maps/shock-therapy/rules.yaml
  mods/ra/maps/shock-therapy/shock-therapy.lua
  mods/ra/missions.yaml
Labels: PR: Needs +2

#18773 Removed hard-coded .vqa assumptions from the engine
  OpenRA.Game/Graphics/Video.cs
  OpenRA.Game/Graphics/VideoLoader.cs
  OpenRA.Game/Manifest.cs
  OpenRA.Game/ModData.cs
  OpenRA.Mods.Cnc/FileFormats/VqaReader.cs
  OpenRA.Mods.Cnc/VideoLoaders/VqaLoader.cs
  OpenRA.Mods.Common/Scripting/Global/MediaGlobal.cs
  OpenRA.Mods.Common/Scripting/Media.cs
  OpenRA.Mods.Common/Widgets/Logic/AssetBrowserLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/MissionBrowserLogic.cs
  OpenRA.Mods.Common/Widgets/VideoPlayerWidget.cs
  mods/cnc/chrome/assetbrowser.yaml
  mods/cnc/chrome/ingame.yaml
  mods/cnc/chrome/missionbrowser.yaml
  mods/cnc/mod.yaml
  mods/common/chrome/assetbrowser.yaml
  mods/common/chrome/ingame-fmvplayer.yaml
  mods/common/chrome/ingame-observer.yaml
  mods/common/chrome/missionbrowser.yaml
  mods/d2k/chrome/ingame-observer.yaml
  mods/d2k/chrome/ingame-player.yaml
  mods/d2k/chrome/missionbrowser.yaml
  mods/d2k/mod.yaml
  mods/ra/chrome/ingame-observer.yaml
  mods/ra/chrome/ingame-player.yaml
  mods/ra/mod.yaml
  mods/ts/chrome/ingame-observer.yaml
  mods/ts/chrome/ingame-player.yaml
  mods/ts/mod.yaml
Labels: PR: Needs +2

#19004 Updated SDL 2 nuget package to match the platform
  OpenRA.WindowsLauncher/OpenRA.WindowsLauncher.csproj
Labels: PR: For stable, PR: Needs +2

#19022 Fixed itch deployment downloading from the wrong URL
  .github/workflows/itch.yml
Labels: PR: For stable, PR: Needs +2

#19031 Switch make.ps1 to downloading from our GeoIP data mirror.
  make.ps1
Labels: PR: For stable, PR: Needs +2

#19032 Cancel support power targeting if power cannot be activated.
  OpenRA.Mods.Cnc/Traits/SupportPowers/AttackOrderPower.cs
  OpenRA.Mods.Cnc/Traits/SupportPowers/ChronoshiftPower.cs
  OpenRA.Mods.Common/Traits/SupportPowers/GrantExternalConditionPower.cs
  OpenRA.Mods.Common/Traits/SupportPowers/SelectDirectionalTarget.cs
  OpenRA.Mods.Common/Traits/SupportPowers/SupportPowerManager.cs
Labels: PR: For stable

#18586 Let harvesters only search for refineries when needing to unload.
  OpenRA.Mods.Common/Activities/FindAndDeliverResources.cs
  OpenRA.Mods.Common/Traits/Harvester.cs
Labels: PR: Is Dependency, PR: Needs +2

#19041 Update apt metadata before installing dependencies.
  .github/workflows/packaging.yml
Labels: PR: For stable, PR: Needs +2

#19045 Fix missing System.Threading.Tasks.Parallel in packaged net5 builds.
  OpenRA.Launcher/OpenRA.Launcher.csproj
  OpenRA.WindowsLauncher/OpenRA.WindowsLauncher.csproj
Labels: PR: Needs +2

#19056 Remove ScriptTriggers from indestructible map deco actors
  mods/cnc/rules/defaults.yaml
  mods/ra/rules/defaults.yaml
Labels: PR: Needs +2

#19051 Fix D2k radar and power disable/enable using wrong sound effects.
  mods/d2k/audio/notifications.yaml
Labels: PR: For stable, PR: Needs +2

#18972 Fixed vehicle explosion and missile impact sounds in Tiberian Dawn
  mods/cnc/rules/vehicles.yaml
  mods/cnc/weapons/explosions.yaml
  mods/cnc/weapons/missiles.yaml
Labels: PR: For stable, PR: Needs +2

#19037 Revert changes that is messing with Resharper
  .editorconfig
Labels: PR: Needs +2

#19061 Fix Sardarkaur not attacking while attack-moving.
  mods/d2k/weapons/smallguns.yaml
Labels: PR: For stable, PR: Needs +2

#19057 Fix `make check` ignoring TARGETPLATFORM override.
  Makefile
Labels: PR: For stable, PR: Needs +2

#19018 Use pattern matching in FieldSaver
  OpenRA.Game/FieldSaver.cs
  OpenRA.Game/Primitives/Rectangle.cs
Labels: PR: Needs +2

#19030 Fix AutoTarget.ChooseTarget ignoring AttackBase.TargetFrozenActors.
  OpenRA.Mods.Common/Traits/AutoTarget.cs
Labels: PR: For stable, PR: Needs +2

#19010 Add Map and server name to discord details
  OpenRA.Mods.Common/Widgets/Logic/Lobby/LobbyLogic.cs
Labels: PR: For stable, PR: Needs +2

#19059 Add shadow rendering for resource sprites.
  OpenRA.Mods.Common/Traits/World/ResourceRenderer.cs
Labels: PR: Is Dependency, PR: Needs +2

#19078 Change hospital owner in Nod07b
  mods/cnc/maps/nod07b/map.yaml
Labels: PR: For stable, PR: Needs +2

#19083 Increase map chooser dialog size to match the lobby.
  mods/cnc/chrome/mapchooser.yaml
  mods/common/chrome/map-chooser.yaml
Labels: PR: For stable, PR: Needs +2

#19076 Make Contrail conditional and public
  OpenRA.Mods.Common/Traits/Render/Contrail.cs
Labels: PR: Needs +2

#19095 Change renderables to class to avoid boxing
  OpenRA.Game/Graphics/SpriteRenderable.cs
  OpenRA.Game/Graphics/TargetLineRenderable.cs
  OpenRA.Game/Graphics/UISpriteRenderable.cs
  OpenRA.Mods.Cnc/Graphics/TeslaZapRenderable.cs
  OpenRA.Mods.Common/Graphics/BeamRenderable.cs
  OpenRA.Mods.Common/Graphics/CircleAnnotationRenderable.cs
  OpenRA.Mods.Common/Graphics/ContrailRenderable.cs
  OpenRA.Mods.Common/Graphics/DetectionCircleAnnotationRenderable.cs
  OpenRA.Mods.Common/Graphics/IsometricSelectionBarsAnnotationRenderable.cs
  OpenRA.Mods.Common/Graphics/IsometricSelectionBoxAnnotationRenderable.cs
  OpenRA.Mods.Common/Graphics/LineAnnotationRenderable.cs
  OpenRA.Mods.Common/Graphics/ModelRenderable.cs
  OpenRA.Mods.Common/Graphics/PolygonAnnotationRenderable.cs
  OpenRA.Mods.Common/Graphics/RailgunRenderable.cs
  OpenRA.Mods.Common/Graphics/RangeCircleAnnotationRenderable.cs
  OpenRA.Mods.Common/Graphics/SelectionBarsAnnotationRenderable.cs
  OpenRA.Mods.Common/Graphics/SelectionBoxAnnotationRenderable.cs
  OpenRA.Mods.Common/Graphics/TextAnnotationRenderable.cs
  OpenRA.Mods.Common/Graphics/UIModelRenderable.cs
  OpenRA.Mods.Common/Graphics/UITextRenderable.cs
Labels: PR: Needs +2

#19036 Fix bot-controlled aircraft stalling above cloaked targets.
  OpenRA.Mods.Common/Activities/Air/FlyAttack.cs
Labels: PR: For stable, PR: Needs +2

#19000 Remove first-client check from LobbySettingsNotification.
  OpenRA.Mods.Common/ServerTraits/LobbySettingsNotification.cs
Labels: PR: For stable, PR: Needs +2

#19007 Keep Discord join button active for spectators.
  OpenRA.Mods.Common/Widgets/Logic/Lobby/LobbyLogic.cs
Labels: PR: For stable, PR: Needs +2

#19085 Suppress error messages from make.ps1 clean.
  make.ps1
Labels: PR: For stable, PR: Needs +2

#19096 Fix RA infantry death anims playing too fast
  mods/ra/sequences/infantry.yaml
Labels: PR: For stable, PR: Needs +2

#18999 Restore missing versioned source code package.
  .github/workflows/packaging.yml
Labels: PR: Conceptual concerns, PR: For stable, PR: Needs +2

#19099 Prevent AttackPopupTurreted.TickIdle from running while disabled.
  OpenRA.Mods.Cnc/Traits/Attack/AttackPopupTurreted.cs
Labels: PR: For stable

#19069 Remove SpawnActorOnDeath from civilian structures
  mods/ra/maps/monster-tank-madness/rules.yaml
  mods/ra/maps/soviet-08a/rules.yaml
  mods/ra/maps/soviet-08b/rules.yaml
  mods/ra/rules/civilian.yaml
  mods/ra/rules/defaults.yaml
Labels: PR: For stable, PR: Needs +2

#19100 Fix Concrete placement on invalid terrain.
  OpenRA.Mods.D2k/Traits/Buildings/D2kBuilding.cs
Labels: PR: For stable, PR: Needs +2

#19102 Remove the 'docs' target from the windows make file
  make.ps1
Labels: PR: For stable, PR: Needs +2

#19105 Fix crash in Allies 05a on SamBarrel kill
  mods/ra/maps/allies-05a/allies05a.lua
Labels: PR: For stable, PR: Needs +2

#19113 Fix the gun sounds not playing in Allies05a
  mods/ra/maps/allies-05a/weapons.yaml
Labels: PR: For stable, PR: Needs +2
