Repository OpenRA/OpenRA, pull requests merged in 2022-12, with the labels that each got.

#20054 Fixed self contained dotnet builds getting executed by Mono
  packaging/linux/openra-server.in
  packaging/linux/openra.in
Labels: PR: For stable

#20500 Remove a stray $ from infront of the version string when writing logs
  OpenRA.Game/Support/ExceptionHandler.cs
Labels: PR: Needs +2, PR: For stable

#20505 Fix carryables vanishing when another unit is picked up
  OpenRA.Mods.Common/Activities/PickupUnit.cs
Labels: PR: Needs +2, PR: For stable

#20503 Fixed missing libfuse2 in Ubuntu 22.04 for AppImage creation
  .github/workflows/packaging.yml
Labels: PR: Needs +2

#20524 Update D2k map pool
  mods/d2k/maps/side-step.oramap
  mods/d2k/maps/source.oramap
  mods/d2k/maps/spice-mesa.oramap
  mods/d2k/maps/stone-plateaus.oramap
  mods/d2k/maps/sunstroke.oramap
Labels: PR: Needs +2, PR: For stable

#20523 Fix attack move lines not showing up for undeploy on force move units
  OpenRA.Mods.Common/Activities/DeployForGrantedCondition.cs
Labels: PR: Needs +2

#20532 Fix syncreport crash caused by getting LocalClient index from ReplayConnection
  OpenRA.Game/Network/SyncReport.cs
Labels: PR: Needs +2

#20522 Don't cancel attack move cursor when holding shift
  OpenRA.Mods.Common/Traits/AttackMove.cs
Labels: PR: Needs +2

#20513 Fix map editor sliders stealing focus
  OpenRA.Mods.Common/Widgets/Logic/Editor/ActorEditLogic.cs
Labels: PR: Needs +2

#20544 Fix error in `PlayerResources` trait documentation
  OpenRA.Mods.Common/Traits/Player/PlayerResources.cs
Labels: PR: Needs +2

#20558 Fix the actor edit panel not always getting closed properly
  OpenRA.Mods.Common/Widgets/Logic/Editor/ActorEditLogic.cs
Labels: PR: Needs +2, PR: For stable

#20506 Fixed documentation deployment
  .github/workflows/documentation.yml
Labels: PR: Needs +2, PR: For stable

#20560 Don't cancel guard cursor when holding shift
  OpenRA.Mods.Common/Orders/GuardOrderGenerator.cs
Labels: PR: Needs +2

#20512 Fix Devil's Tongue attacking while submerged
  mods/ts/rules/nod-vehicles.yaml
Labels: PR: Needs +2

#20497 Added conditional support to RenderShroud/JammerCircle
  OpenRA.Mods.Common/Traits/Render/RenderJammerCircle.cs
  OpenRA.Mods.Common/Traits/Render/RenderShroudCircle.cs
Labels: PR: Needs +2

#20435 GitHub Workflows security hardening
  .github/workflows/ci.yml
  .github/workflows/documentation.yml
  .github/workflows/itch.yml
  .github/workflows/packaging.yml
Labels: PR: Needs +2

#20561 Prioritise primary buildings in CycleBasesHotkeyLogic.
  OpenRA.Mods.Common/Widgets/Logic/Ingame/Hotkeys/CycleBasesHotkeyLogic.cs
Labels: PR: Needs +2

#20499 Fix PathFinderOverlay crash when deselecting actor moving along waypoints
  OpenRA.Mods.Common/Traits/World/PathFinderOverlay.cs
Labels: PR: Needs +2, PR: For stable

#20570 Bubble unhandled double-click events to OnClick.
  OpenRA.Mods.Common/Widgets/ButtonWidget.cs
Labels: PR: Needs +2

#20567 Run the CI workflow on PRs targeting prep
  .github/workflows/ci.yml
Labels: PR: Needs +2, PR: For stable

#20572 Change tile 9 to Rough TerrainType
  mods/d2k/tilesets/arrakis.yaml
Labels: PR: Needs +2

#20563 Fix contrail using the wrong colors
  OpenRA.Mods.Common/Graphics/ContrailRenderable.cs
  OpenRA.Mods.Common/Projectiles/Bullet.cs
  OpenRA.Mods.Common/Projectiles/Missile.cs
  OpenRA.Mods.Common/Traits/Render/Contrail.cs
Labels: PR: Needs +2, PR: For stable

#20566 Added carryalls to spectator Economy statistics
  OpenRA.Mods.Common/Widgets/Logic/Ingame/ObserverStatsLogic.cs
  mods/d2k/chrome/ingame-observer.yaml
Labels: PR: Needs +2, PR: For stable

#20509 Remove sniper
  mods/ra/maps/ant-01/rules.yaml
  mods/ra/maps/fort-lonestar/map.yaml
  mods/ra/maps/fort-lonestar/rules.yaml
  mods/ra/maps/fort-lonestar/sequences.yaml
  mods/ra/maps/fort-lonestar/sniper.shp
  mods/ra/maps/fort-lonestar/snipericon.shp
  mods/ra/maps/fort-lonestar/weapons.yaml
  mods/ra/rules/infantry.yaml
  mods/ra/sequences/infantry.yaml
  mods/ra/weapons/smallcaliber.yaml
Labels: PR: Needs +2

#20576 Fix MiniYaml source locations being lost when merging.
  OpenRA.Game/MiniYaml.cs
Labels: PR: Needs +2, PR: For stable

#20579 Fix map actors not being spawned with the correct owner
  OpenRA.Mods.Common/Traits/World/SpawnMapActors.cs
Labels: PR: Needs +2, PR: For stable

#20568 Fix pseudo-fullscreen window size on macs with a notch.
  OpenRA.Platforms.Default/Sdl2PlatformWindow.cs
  packaging/macos/Info.plist.in
Labels: PR: Needs +2, PR: For stable

#20578 Let the documentation workflow fetch the required git branch
  .github/workflows/documentation.yml
Labels: PR: Needs +2, PR: For stable

#20575 Removed hardcoded Aircraft ignoring in AI squad manager
  OpenRA.Mods.Common/Traits/BotModules/SquadManagerBotModule.cs
  mods/cnc/rules/ai.yaml
  mods/d2k/rules/ai.yaml
  mods/ra/maps/soviet-05/rules.yaml
  mods/ra/rules/ai.yaml
  mods/ts/rules/ai.yaml
Labels: PR: Needs +2

#20587 Downgrade OpenAL-soft to 1.10.1 and fix Linux audio backends
  OpenRA.Platforms.Default/OpenRA.Platforms.Default.csproj
Labels: PR: Needs +2, PR: For stable

#20588 Specify targetable offsets for the repair pad in Dune 2000
  mods/d2k/rules/structures.yaml
Labels: PR: Needs +2

#20584 Enforce use of 'var' instead of explicit type
  .editorconfig
  OpenRA.Game/Graphics/Palette.cs
  OpenRA.Game/Map/MapPreview.cs
  OpenRA.Game/Network/SyncReport.cs
  OpenRA.Game/Scripting/ScriptTypes.cs
  OpenRA.Mods.Cnc/FileFormats/LZOCompression.cs
  OpenRA.Mods.Cnc/UtilityCommands/ImportTSMapCommand.cs
  OpenRA.Mods.Common/Projectiles/Missile.cs
  OpenRA.Mods.Common/Scripting/Global/MediaGlobal.cs
  OpenRA.Mods.Common/TargetExtensions.cs
  OpenRA.Mods.Common/Traits/AutoTarget.cs
  OpenRA.Mods.Common/Traits/BotModules/BotModuleLogic/BaseBuilderQueueManager.cs
  OpenRA.Mods.Common/Traits/Mobile.cs
  OpenRA.Mods.Common/UtilityCommands/Extensions.cs
  OpenRA.Mods.Common/UtilityCommands/Rgba2Hex.cs
  OpenRA.Mods.Common/Widgets/ModelWidget.cs
Labels: PR: Needs +2

#20385 package-all.sh: Don't use parameter expansion for paths
  packaging/package-all.sh
Labels: PR: Needs +2

#20573 Allow mods to customise the default rendering scale.
  OpenRA.Game/Graphics/Viewport.cs
  OpenRA.Game/WorldViewportSizes.cs
  OpenRA.Mods.Common/Traits/World/TerrainRenderer.cs
  OpenRA.Mods.Common/Widgets/ActorPreviewWidget.cs
  OpenRA.Mods.Common/Widgets/Logic/Editor/LayerSelectorLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Editor/TileSelectorLogic.cs
  OpenRA.Mods.Common/Widgets/ResourcePreviewWidget.cs
  OpenRA.Mods.Common/Widgets/TerrainTemplatePreviewWidget.cs
Labels: PR: Needs +2
