Repository OpenRA/OpenRA, pull requests merged in 2022-11, with the labels that each got.

#20404 Order maps by date
  AUTHORS
  OpenRA.Game/Map/MapPreview.cs
  OpenRA.Mods.Common/Widgets/Logic/MapChooserLogic.cs
  mods/cnc/chrome/mapchooser.yaml
  mods/common/chrome/map-chooser.yaml
  mods/common/languages/en.ftl
Labels: PR: Needs +2

#20417 Removed dubFinder style sheet
  dupFinder.xslt
Labels: PR: Needs +2

#20420 Fix RenameContrailProperties UpdateRule
  OpenRA.Mods.Common/UpdateRules/Rules/20210321/RenameContrailProperties.cs
Labels: PR: Needs +2

#20430 Fixed a crash when flood filling tiles outside of the map
  OpenRA.Mods.Common/EditorBrushes/EditorTileBrush.cs
Labels: PR: Needs +2

#20432 Fixed multiplayer spawn being allowed outside of the map in the editor
  OpenRA.Mods.Common/Traits/World/EditorActorPreview.cs
Labels: PR: Needs +2

#20438 Add a .zsync suffix to appimagecheck URL to pass appimaged checks
  packaging/linux/buildpackage.sh
Labels: PR: Needs +2

#20403 Fix carryall not removing influence when cancelling land activity
  OpenRA.Mods.Common/Activities/PickupUnit.cs
Labels: PR: Needs +2

#20431 Use Stop button on (production) buildings to reset rally point fixes …
  OpenRA.Mods.Common/Traits/Buildings/RallyPoint.cs
  mods/cnc/chrome/ingame.yaml
  mods/cnc/rules/structures.yaml
  mods/d2k/chrome/ingame-player.yaml
  mods/d2k/rules/structures.yaml
  mods/ra/chrome/ingame-player.yaml
  mods/ra/maps/soviet-01/rules.yaml
  mods/ra/rules/structures.yaml
  mods/ts/chrome/ingame-player.yaml
  mods/ts/rules/gdi-structures.yaml
  mods/ts/rules/nod-structures.yaml
Labels: PR: Needs +2

#20421 Nerf player experience
  mods/cnc/rules/defaults.yaml
  mods/cnc/rules/infantry.yaml
  mods/cnc/rules/structures.yaml
  mods/d2k/rules/defaults.yaml
  mods/d2k/rules/infantry.yaml
  mods/d2k/rules/structures.yaml
  mods/ra/maps/oil-spill/rules.yaml
  mods/ra/rules/campaign-rules.yaml
  mods/ra/rules/defaults.yaml
  mods/ra/rules/infantry.yaml
  mods/ra/rules/structures.yaml
  mods/ts/rules/defaults.yaml
  mods/ts/rules/gdi-structures.yaml
  mods/ts/rules/nod-infantry.yaml
  mods/ts/rules/nod-structures.yaml
  mods/ts/rules/shared-infantry.yaml
Labels: PR: Needs +2

#20422 Update AUTHORS
  AUTHORS
Labels: PR: Needs +2

#20399 Pathing considers reachability of source cells consistently.
  OpenRA.Mods.Common/Pathfinder/HierarchicalPathFinder.cs
  OpenRA.Mods.Common/Pathfinder/PathSearch.cs
  OpenRA.Mods.Common/Traits/Buildings/TransformsIntoMobile.cs
  OpenRA.Mods.Common/Traits/Mobile.cs
  OpenRA.Mods.Common/Traits/World/Locomotor.cs
  OpenRA.Mods.Common/Traits/World/PathFinder.cs
Labels: PR: Needs +2

#19534 SpriteRenderer, do not copy vertex array data each flush.
  OpenRA.Game/Graphics/PlatformInterfaces.cs
  OpenRA.Game/Graphics/SpriteRenderer.cs
  OpenRA.Game/Renderer.cs
  OpenRA.Platforms.Default/Sdl2GraphicsContext.cs
  OpenRA.Platforms.Default/ThreadedGraphicsContext.cs
  OpenRA.Platforms.Default/VertexBuffer.cs
Labels: PR: Needs +2

#20452 Fix Locomotor IsMoving checks.
  OpenRA.Mods.Common/Traits/World/Locomotor.cs
Labels: PR: Needs +2

#20458 Remove dead code inside SupportPower.cs
  OpenRA.Mods.Common/Traits/SupportPowers/SupportPower.cs
Labels: PR: Needs +2

#20455 fix misclicks through sidebar
  mods/cnc/chrome/ingame.yaml
  mods/ra/chrome/ingame-player.yaml
Labels: PR: Needs +2, PR: For stable

#20406 Issue20373 aicraft hangs midair
  OpenRA.Mods.Common/Activities/Air/ReturnToBase.cs
Labels: PR: Needs +2

#20423 Dispose DependencyContextJsonReader after using
  OpenRA.Game/Support/AssemblyLoader.cs
Labels: PR: Needs +2

#20135 Move AbortOnResupply from AttackAircraft to AttackFollow
  OpenRA.Mods.Common/Traits/Air/AttackAircraft.cs
  OpenRA.Mods.Common/Traits/Attack/AttackFollow.cs
Labels: PR: Needs +2

#20244 Introduce MinDistance to AreaBeam projectile
  OpenRA.Mods.Common/Projectiles/AreaBeam.cs
  mods/d2k/weapons/other.yaml
Labels: PR: Needs +2, PR: For stable

#20464 Manually add game speeds to the linter.
  OpenRA.Mods.Common/Lint/CheckTranslationReference.cs
Labels: PR: Needs +2, PR: For stable

#20470 Fixed notarisation stalling the build process
  packaging/macos/buildpackage.sh
Labels: PR: Needs +2, PR: For stable

#20471 ExceptionHandler, fix npe.
  OpenRA.Game/Support/ExceptionHandler.cs
Labels: PR: Needs +2, PR: For stable

#20369 Weapon shouldn't check warheads in IsValidAgainst
  OpenRA.Game/GameRules/WeaponInfo.cs
Labels: PR: Needs +2

#20477 Fixed error message not mentioning the host from which the download failed
  OpenRA.Mods.Common/Widgets/Logic/Installation/DownloadPackageLogic.cs
Labels: PR: For stable

#20465 HarvesterBotModule should not command harvesters that cannot be ordered
  OpenRA.Mods.Common/Traits/BotModules/HarvesterBotModule.cs
Labels: PR: Needs +2

#20474 Syncreport outputs some more infomation
  OpenRA.Game/Network/SyncReport.cs
Labels: PR: Needs +2

#20484 Fix display bounds when running on macbooks with a notch.
  packaging/macos/Info.plist.in
Labels: PR: Needs +2, PR: For stable

#20487 Updated Apple notarisation to XCode 13
  .github/workflows/packaging.yml
  packaging/macos/buildpackage.sh
Labels: PR: Needs +2

#20486 Serialize orders for all clients
  OpenRA.Game/Network/Connection.cs
  OpenRA.Game/Network/OrderIO.cs
Labels: PR: Needs +2, PR: For stable
