Repository OpenRA/OpenRA, pull requests merged in 2022-10, with the labels that each got.

#20306 Removed unnecessary value assignments
  .editorconfig
  OpenRA.Game/WDist.cs
  OpenRA.Mods.Cnc/FileFormats/BlowfishKeyProvider.cs
  OpenRA.Mods.Cnc/FileFormats/WsaVideo.cs
  OpenRA.Mods.Cnc/Graphics/TeslaZapRenderable.cs
  OpenRA.Mods.Cnc/Traits/Disguise.cs
  OpenRA.Mods.Cnc/UtilityCommands/ImportTSMapCommand.cs
  OpenRA.Mods.Cnc/VideoLoaders/WsaLoader.cs
  OpenRA.Mods.Common/Activities/Enter.cs
  OpenRA.Mods.Common/Projectiles/Missile.cs
  OpenRA.Mods.Common/Traits/BotModules/Squads/States/AirStates.cs
  OpenRA.Mods.Common/Traits/Carryall.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20200503/MoveClassicFacingFudge.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20200503/RenameSelfHealing.cs
  OpenRA.Mods.Common/UtilityCommands/DumpSequenceSheetsCommand.cs
  OpenRA.Mods.Common/UtilityCommands/ImportLegacyMapCommand.cs
  OpenRA.Mods.Common/UtilityCommands/UpdateMapCommand.cs
  OpenRA.Mods.Common/UtilityCommands/UpdateModCommand.cs
  OpenRA.Platforms.Default/Sdl2Input.cs
Labels: PR: Needs +2

#20301 Use SDL.SDL_OpenURL instead of Process.Start to open FAQ and Logs
  OpenRA.WindowsLauncher/Program.cs
Labels: PR: Needs +2

#20291 Add highlighted state to GetCachedStatefulImage
  OpenRA.Mods.Common/Widgets/CheckboxWidget.cs
  OpenRA.Mods.Common/Widgets/DropDownButtonWidget.cs
  OpenRA.Mods.Common/Widgets/ProductionTabsWidget.cs
  OpenRA.Mods.Common/Widgets/ScrollPanelWidget.cs
  OpenRA.Mods.Common/Widgets/WidgetUtils.cs
  mods/cnc/chrome.yaml
  mods/d2k/chrome.yaml
  mods/ra/chrome.yaml
  mods/ts/chrome.yaml
Labels: PR: Needs +2, PR: Is Dependency

#20295 Improve translation of power/silo usage tooltip
  OpenRA.Mods.Common/Widgets/Logic/Ingame/IngameCashCounterLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Ingame/IngamePowerBarLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Ingame/IngamePowerCounterLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Ingame/IngameSiloBarLogic.cs
  OpenRA.Mods.Common/Widgets/ResourceBarWidget.cs
  mods/common/languages/en.ftl
Labels: PR: Needs +2

#18746 Added observer vision stats
  OpenRA.Game/Traits/Player/Shroud.cs
  OpenRA.Mods.Common/Widgets/Logic/Ingame/ObserverStatsLogic.cs
  mods/cnc/chrome/ingame.yaml
  mods/common/chrome/ingame-observer.yaml
  mods/d2k/chrome/ingame-observer.yaml
  mods/ra/chrome/ingame-observer.yaml
  mods/ts/chrome/ingame-observer.yaml
Labels: PR: Needs +2

#20041 Fixed man pages missing install rule
  Makefile
Labels: PR: Needs +2

#20334 Fix subterranean units teleporting to surface and jump jets to ground
  OpenRA.Mods.Common/Activities/Move/Move.cs
Labels: PR: Needs +2

#20238 Fix MapCache mapUpdates
  OpenRA.Game/Map/MapCache.cs
Labels: PR: Needs +2

#20070 MacOS buildpackage: Fix deduplication
  packaging/macos/buildpackage.sh
Labels: PR: Needs +2

#20356 Add a workaround for unbinding script members on Mono
  OpenRA.Game/Scripting/ScriptObjectWrapper.cs
Labels: PR: Needs +2

#20365 Fix dinos not being able to crush crates
  mods/cnc/rules/world.yaml
Labels: PR: Needs +2

#20353 Update the TD map pool
  mods/cnc/maps/a-new-winter.oramap
  mods/cnc/maps/armageddon.oramap
  mods/cnc/maps/blue-mountains.oramap
  mods/cnc/maps/crackpoint.oramap
  mods/cnc/maps/desert-mandarins.oramap
  mods/cnc/maps/lockdown.oramap
  mods/cnc/maps/lost-souls.oramap
  mods/cnc/maps/matchpoint.oramap
  mods/cnc/maps/model-150.oramap
  mods/cnc/maps/mountain-town-madness.oramap
  mods/cnc/maps/reasonable-doubt.oramap
  mods/cnc/maps/tiberian-war.oramap
  mods/cnc/maps/tiberium-forest.oramap
  mods/cnc/maps/tiberium-rift.oramap
  mods/cnc/maps/war-zone-x.oramap
Labels: PR: Needs +2

#20374 Fixed SupportPowers ClockAnimation being ignored
  OpenRA.Mods.Common/Widgets/SupportPowersWidget.cs
Labels: PR: Needs +2

#20368 Fix a typo in the undefined MapFormat exception message
  OpenRA.Game/Map/Map.cs
Labels: PR: Needs +2

#20363 Allow cash ticking sound to overlap
  OpenRA.Game/GameRules/SoundInfo.cs
  OpenRA.Game/Sound/Sound.cs
  mods/cnc/audio/notifications.yaml
  mods/d2k/audio/notifications.yaml
  mods/ra/audio/notifications.yaml
  mods/ts/audio/sounds-generic.yaml
Labels: PR: Needs +2

#20379 Fixed /givecash defaulting to 20000 $ when entering invalid values
  OpenRA.Mods.Common/Commands/DevCommands.cs
Labels: PR: Needs +2

#20316 Refactor WidgetUtils.BindButtonIcon
  OpenRA.Mods.Common/Widgets/ImageWidget.cs
  OpenRA.Mods.Common/Widgets/WidgetUtils.cs
  mods/cnc/chrome.yaml
  mods/d2k/chrome.yaml
  mods/ra/chrome.yaml
  mods/ts/chrome.yaml
Labels: PR: Needs +2, PR: Is Dependency

#20375 TD Fall 2022 Balance
  mods/cnc/rules/aircraft.yaml
  mods/cnc/rules/defaults.yaml
  mods/cnc/rules/infantry.yaml
  mods/cnc/rules/structures.yaml
  mods/cnc/rules/vehicles.yaml
  mods/cnc/weapons/ballistics.yaml
  mods/cnc/weapons/explosions.yaml
  mods/cnc/weapons/missiles.yaml
  mods/cnc/weapons/other.yaml
  mods/cnc/weapons/smallcaliber.yaml
  mods/cnc/weapons/superweapons.yaml
Labels: PR: Needs +2

#20378 Updated the documentation site
  packaging/format-docs.py
Labels: PR: Needs +2

#20382 Fix ProductionPalette ClockAnimation and NotBuildableAnimation being ignored
  OpenRA.Mods.Common/Widgets/ProductionPaletteWidget.cs
Labels: PR: Needs +2

#20283 Refactor image search functions to use Get and TryGet terminology
  OpenRA.Game/Graphics/ChromeProvider.cs
  OpenRA.Mods.Common/Widgets/ImageWidget.cs
  OpenRA.Mods.Common/Widgets/ScrollItemWidget.cs
  OpenRA.Mods.Common/Widgets/WidgetUtils.cs
Labels: PR: Needs +2

#20377 Update Tiberium Forest
  mods/cnc/maps/tiberium-forest.oramap
Labels: PR: Needs +2

#20342 Adapted the documentation build to the new repository structure
  .github/workflows/documentation.yml
Labels: PR: Needs +2

#20396 Fix TD missions file not being referenced using package syntax
  mods/cnc/mod.yaml
Labels: PR: Needs +2

#20393 Exposed game speeds to localisation
  OpenRA.Mods.Common/Traits/World/MapOptions.cs
  OpenRA.Mods.Common/Widgets/Logic/MissionBrowserLogic.cs
  mods/cnc/mod.yaml
  mods/common/languages/en.ftl
  mods/d2k/mod.yaml
  mods/ra/mod.yaml
  mods/ts/mod.yaml
Labels: PR: Needs +2

#20383 Add mouse scroll to ProductionPaletteWidget
  OpenRA.Mods.Common/Widgets/ProductionPaletteWidget.cs
Labels: PR: Needs +2, PR: Fixup requested

#20391 Add OpenRA and OS language to exception messages
  OpenRA.Game/Support/ExceptionHandler.cs
Labels: PR: Needs +2

#20389 Use MacOS 11 for release packaging
  .github/workflows/packaging.yml
Labels: PR: Needs +2

#20401 Fix Aircraft not updating influence when changing height
  OpenRA.Mods.Common/Activities/Air/TakeOff.cs
  OpenRA.Mods.Common/Traits/Air/Aircraft.cs
Labels: PR: Needs +2

#20319 Fix for turret tracking invisible pillbox
  OpenRA.Mods.Common/Traits/Attack/AttackFollow.cs
Labels: PR: Needs +2

#20344 Fix infinite worm re-spawn in campaign
  mods/d2k/rules/campaign-rules.yaml
Labels: PR: Needs +2

#20349 Allow weapons with no damage warheads to be fired
  OpenRA.Mods.Common/Traits/Attack/AttackBase.cs
Labels: PR: Needs +2

#20340 Fix RA anti-ground missiles damaging air units and vice versa
  mods/ra/weapons/missiles.yaml
Labels: PR: Needs +2

#20392 Fix replay player disconnect handling
  OpenRA.Game/Network/ReplayConnection.cs
Labels: PR: Needs +2
