Repository OpenRA/OpenRA, pull requests merged in 2022-07, with the labels that each got.

#20097 Rectangle equals, trivial optimization.
  OpenRA.Game/Primitives/Rectangle.cs
Labels: PR: Needs +2

#20099 PathSearch, make TargetPredicate a readonly private field.
  OpenRA.Mods.Common/Pathfinder/PathSearch.cs
Labels: PR: Needs +2

#20095 Add a lint check for maps without playable player
  OpenRA.Mods.Common/Lint/CheckPlayers.cs
Labels: PR: Needs +2

#20069 Makefile: More robust check-scripts
  Makefile
Labels: PR: Needs +2

#20110 Nerf supply truck XP gain
  mods/cnc/rules/vehicles.yaml
  mods/ra/rules/vehicles.yaml
Labels: PR: Needs +2

#20076 Add an option to disable chat in replays
  OpenRA.Game/Network/UnitOrders.cs
  OpenRA.Game/Settings.cs
  OpenRA.Game/TextNotification.cs
  OpenRA.Game/TextNotificationsManager.cs
  OpenRA.Mods.Common/Widgets/Logic/Ingame/IngameChatLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Ingame/IngameTransientNotificationsLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Settings/DisplaySettingsLogic.cs
  mods/cnc/chrome/settings-display.yaml
  mods/common/chrome/settings-display.yaml
Labels: PR: Needs +2, PR: Is Dependency

#20108 Changed `anypower` tag name to Any Power Generation to reduce confusion.
  mods/cnc/rules/structures.yaml
  mods/ra/rules/structures.yaml
  mods/ts/rules/shared-structures.yaml
Labels: PR: Rebase me!, PR: Needs +2

#20006 Fixed a crash when loading empty video files
  OpenRA.Mods.Cnc/VideoLoaders/VqaLoader.cs
  OpenRA.Mods.Cnc/VideoLoaders/WsaLoader.cs
  OpenRA.Mods.Common/Scripting/Global/MediaGlobal.cs
  OpenRA.Mods.Common/Widgets/Logic/MissionBrowserLogic.cs
  OpenRA.Mods.Common/Widgets/VideoPlayerWidget.cs
Labels: PR: Needs +2

#20111 Added a missing SequenceReferenceAttribute
  OpenRA.Mods.Common/Traits/Palettes/PaletteFromEmbeddedSpritePalette.cs
Labels: PR: Needs +2

#20044 Palette enhancements
  OpenRA.Mods.Common/Traits/Palettes/ColorPickerPalette.cs
  OpenRA.Mods.Common/Traits/Palettes/FixedColorPalette.cs
  OpenRA.Mods.Common/Traits/Palettes/IndexedPlayerPalette.cs
  OpenRA.Mods.Common/Traits/Palettes/PaletteFromFile.cs
  OpenRA.Mods.Common/Traits/Palettes/PaletteFromGrayscale.cs
  OpenRA.Mods.Common/Traits/Palettes/PaletteFromRGBA.cs
  OpenRA.Mods.Common/Traits/Palettes/PlayerColorPalette.cs
Labels: PR: Changes requested, PR: Needs +2

#20081 Refactor checkbox
  OpenRA.Mods.Common/Widgets/CheckboxWidget.cs
  OpenRA.Mods.Common/Widgets/Logic/Ingame/GameInfoObjectivesLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Ingame/GameInfoStatsLogic.cs
  mods/cnc/chrome.yaml
  mods/cnc/chrome/lobby-players.yaml
  mods/cnc/metrics.yaml
  mods/common/chrome/lobby-players.yaml
  mods/common/metrics.yaml
  mods/d2k/chrome.yaml
  mods/d2k/chrome/lobby-players.yaml
  mods/modcontent/metrics.yaml
  mods/ra/chrome.yaml
  mods/ts/chrome.yaml
Labels: PR: Needs +2, PR: Is Dependency

#20139 Make ornithopter targetable by anti-air units
  mods/d2k/rules/aircraft.yaml
Labels: PR: Needs +2

#20144 Make support power fakes infiltratable
  mods/ra/rules/fakes.yaml
Labels: PR: Needs +2

#20134 Fix a crash when there is no briefing text
  OpenRA.Mods.Common/Widgets/Logic/Ingame/GameInfoBriefingLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/MissionBrowserLogic.cs
Labels: PR: Needs +2

#19752 Netcode time sync
  OpenRA.Game/Server/OrderBuffer.cs
  OpenRA.Game/Server/Server.cs
Labels: PR: Needs +2

#20147 Fix tab completion to work for all available commands.
  OpenRA.Mods.Common/Widgets/Logic/Ingame/IngameChatLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/TabCompletionLogic.cs
Labels: PR: Needs +2

#20137 Align weapons to better match original d2k
  mods/d2k/rules/structures.yaml
  mods/d2k/weapons/largeguns.yaml
  mods/d2k/weapons/missiles.yaml
  mods/d2k/weapons/other.yaml
  mods/d2k/weapons/smallguns.yaml
Labels: PR: Needs +2
