Repository OpenRA/OpenRA, pull requests merged in 2023-08, with the labels that each got.

#20984 Fix RA assets installation from the Steam C&C:R version
  mods/ra/installer/origin.yaml
  mods/ra/installer/steam.yaml
Labels: PR: Needs +2, PR: For stable

#20140 Fly, use rotating buffer over list to store last 5 positions.
  OpenRA.Game/Primitives/RingBuffer.cs
  OpenRA.Game/WAngle.cs
  OpenRA.Mods.Common/Activities/Air/Fly.cs
  OpenRA.Mods.Common/Util.cs
Labels: PR: Needs +2

#20985 Fix lua sanity check crashing on dedicated servers
  OpenRA.Mods.Common/Lint/CheckLuaScript.cs
Labels: PR: For stable

#19364 Add Soviet13b
  mods/ra/maps/soviet-13b/map.bin
  mods/ra/maps/soviet-13b/map.png
  mods/ra/maps/soviet-13b/map.yaml
  mods/ra/maps/soviet-13b/rules.yaml
  mods/ra/maps/soviet-13b/soviet13b-AI.lua
  mods/ra/maps/soviet-13b/soviet13b.lua
  mods/ra/missions.yaml
Labels: PR: Needs +2

#20986 Fix misaligned TD combat observer tab
  mods/cnc/chrome/ingame.yaml
Labels: PR: For stable

#20841 Fix aircraft jittering
  OpenRA.Mods.Common/Activities/Air/Fly.cs
  OpenRA.Mods.Common/Traits/Air/Aircraft.cs
Labels: PR: For stable

#20836 Grant condition to units closest to the crate
  OpenRA.Mods.Common/Traits/Crates/GrantExternalConditionCrateAction.cs
Labels: PR: For stable

#20338 Give husks the ability to crush
  OpenRA.Mods.Common/Traits/Husk.cs
  mods/cnc/rules/defaults.yaml
  mods/d2k/rules/defaults.yaml
  mods/d2k/rules/husks.yaml
  mods/ra/rules/defaults.yaml
  mods/ra/rules/husks.yaml
Labels: PR: Needs +2

#20989 Fix low power notification never triggering
  OpenRA.Mods.Common/Traits/Power/Player/PowerManager.cs
Labels: PR: For stable

#20990 Fixed a crash after changing the display scale
  OpenRA.Mods.Common/Widgets/Logic/Settings/DisplaySettingsLogic.cs
Labels: PR: For stable

#20849 Fix crate spawned actors not crushing crushable actors and spawning inside other actors.
  OpenRA.Mods.Common/Traits/Crates/DuplicateUnitCrateAction.cs
  OpenRA.Mods.Common/Traits/Crates/GiveUnitCrateAction.cs
Labels: PR: Needs +2

#20493 Allow queueing up scatter and move Nudge to an activity
  OpenRA.Mods.Cnc/Traits/MadTank.cs
  OpenRA.Mods.Common/Activities/Move/Nudge.cs
  OpenRA.Mods.Common/Scripting/Properties/MobileProperties.cs
  OpenRA.Mods.Common/Traits/Air/Aircraft.cs
  OpenRA.Mods.Common/Traits/Crushable.cs
  OpenRA.Mods.Common/Traits/EjectOnDeath.cs
  OpenRA.Mods.Common/Traits/Mobile.cs
  OpenRA.Mods.Common/Widgets/Logic/Ingame/CommandBarLogic.cs
Labels: PR: Needs +2

#20981 Delay AI's radar dome by 2-3 minutes
  mods/ra/rules/ai.yaml
Labels: PR: Needs +2

#20931 Make Bullet projectile extensible
  OpenRA.Mods.Common/Projectiles/Bullet.cs
Labels: PR: Needs +2, PR: Fixup requested

#21016 Automatically order units away when trying to deploy transform
  OpenRA.Mods.Common/AIUtils.cs
  OpenRA.Mods.Common/Orders/PlaceBuildingOrderGenerator.cs
  OpenRA.Mods.Common/Traits/Transforms.cs
Labels: PR: Needs +2

#21028 Cache uniform locations
  OpenRA.Platforms.Default/Shader.cs
Labels: PR: Needs +2

#20999 Add text fix, minor polish to Controlled Burn
  mods/ra/maps/sarin-gas-3-controlled-burn/controlledburn-AI.lua
  mods/ra/maps/sarin-gas-3-controlled-burn/controlledburn.lua
  mods/ra/maps/sarin-gas-3-controlled-burn/rules.yaml
Labels: PR: Needs +2, PR: For stable
