Repository OpenRA/OpenRA, pull requests merged in 2023-02, with the labels that each got.

#20651 Fixed Makefile check of MacOS architecture
  Makefile
Labels: PR: Needs +2, PR: For stable

#20652 Improve logging in DownloadPackageLogic
  OpenRA.Mods.Common/Widgets/Logic/Installation/DownloadPackageLogic.cs
Labels: PR: Needs +2

#20650 Adjust D2k encyclopedia descriptions for light and heavily armored units
  mods/d2k/rules/vehicles.yaml
Labels: PR: Needs +2, PR: For stable

#20637 Reduce impact of max order length checks
  OpenRA.Game/Server/Connection.cs
Labels: PR: Needs +2, PR: For stable

#20672 Remove redundant jumps and other style nits from the update rules
  OpenRA.Mods.Common/UpdateRules/Rules/20200202/RemoveInitialFacingHardcoding.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20200503/ChangeTargetLineDelayToMilliseconds.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20200503/RemoveTurnToDock.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20200503/SplitDamagedByTerrain.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20210321/ReplaceCrateSecondsWithTicks.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20221203/ExplicitSequenceFilenames.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20221203/ProductionTabsWidgetAddTabButtonCollection.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20221203/TextNotificationsDisplayWidgetRemoveTime.cs
Labels: PR: Needs +2

#20662 Remove dependency on VCRUNTIME140.dll.
  OpenRA.Game/OpenRA.Game.csproj
Labels: PR: Needs +2, PR: For stable

#20678 Change the way the output directory is set during packaging
  packaging/functions.sh
Labels: PR: Needs +2, PR: For stable

#20669 Minor D2k encyclopedia UI polish
  mods/d2k/chrome/encyclopedia.yaml
Labels: PR: Needs +2, PR: For stable

#20571 Return invalid path instead of crashing on HPF failing
  OpenRA.Mods.Common/Pathfinder/HierarchicalPathFinder.cs
Labels: PR: For stable

#20647 Add MacOS Utility executable
  packaging/macos/buildpackage.sh
  packaging/macos/utility.m
Labels: PR: Needs +2, PR: For stable

#20679 Polish encyclopedia descriptions
  mods/d2k/rules/infantry.yaml
  mods/d2k/rules/misc.yaml
  mods/d2k/rules/structures.yaml
  mods/d2k/rules/vehicles.yaml
Labels: PR: Needs +2

#20674 Allow mods to control how looped sounds are used.
  OpenRA.Game/Sound/Sound.cs
  OpenRA.Game/Sound/SoundDevice.cs
  OpenRA.Platforms.Default/DummySoundEngine.cs
  OpenRA.Platforms.Default/OpenAlSoundEngine.cs
Labels: PR: Needs +2

#20628 Remove TiberianSunRefinery
  OpenRA.Mods.Cnc/Activities/VoxelHarvesterDockSequence.cs
  OpenRA.Mods.Cnc/Traits/Buildings/TiberianSunRefinery.cs
  OpenRA.Mods.Cnc/Traits/Render/WithVoxelUnloadBody.cs
  OpenRA.Mods.Common/Activities/HarvesterDockSequence.cs
  OpenRA.Mods.Common/Activities/SpriteHarvesterDockSequence.cs
  OpenRA.Mods.Common/Traits/Buildings/Refinery.cs
  OpenRA.Mods.Common/Traits/Render/WithDockingAnimation.cs
  OpenRA.Mods.Common/Traits/Render/WithDockingOverlay.cs
  OpenRA.Mods.Common/TraitsInterfaces.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20221203/RemoveTSRefinery.cs
  OpenRA.Mods.Common/UpdateRules/UpdatePath.cs
  mods/ts/rules/nod-structures.yaml
  mods/ts/rules/shared-structures.yaml
Labels: PR: Needs +2

#20627 Fix not all ammo pools getting rearmed during RearmTick
  OpenRA.Mods.Common/Traits/Rearmable.cs
Labels: PR: Needs +2

#20684 Fixed displayed audio length in the AssetBrowser
  OpenRA.Mods.Common/Widgets/Logic/AssetBrowserLogic.cs
Labels: PR: Needs +2

#20685 Make minor AssetBrowser fixes
  OpenRA.Mods.Common/Widgets/Logic/AssetBrowserLogic.cs
Labels: PR: Needs +2, PR: For stable

#20687 TD Map Pool Update
  mods/cnc/maps/matchpoint.oramap
  mods/cnc/maps/tiberium-rift.oramap
Labels: PR: For stable

#20686 Change click sound InterruptType to Overlap
  mods/cnc/audio/notifications.yaml
  mods/d2k/audio/notifications.yaml
  mods/ra/audio/notifications.yaml
  mods/ts/audio/sounds-generic.yaml
Labels: PR: Needs +2, PR: For stable

#20706 Add PrefersNonDefaultGPU flag to Desktop Entry
  packaging/linux/openra.desktop.in
Labels: PR: Needs +2

#20708 Fix colors in gamma space being treated as if they were in lineer space
  OpenRA.Game/Graphics/PlayerColorRemap.cs
  OpenRA.Mods.Common/Traits/Palettes/ColorPickerPalette.cs
  OpenRA.Mods.Common/Traits/Palettes/FixedColorPalette.cs
  OpenRA.Mods.Common/Traits/Palettes/PlayerColorPalette.cs
Labels: PR: Needs +2, PR: For stable
