Repository OpenRA/OpenRA, pull requests merged in 2023-03, with the labels that each got.

#20711 Enforce code rule IDE0048
  .editorconfig
  OpenRA.Game/Map/Map.cs
  OpenRA.Game/Primitives/PriorityQueue.cs
  OpenRA.Game/Traits/Player/Shroud.cs
  OpenRA.Mods.Cnc/FileFormats/BlowfishKeyProvider.cs
  OpenRA.Mods.Cnc/FileFormats/LZOCompression.cs
  OpenRA.Mods.Cnc/FileSystem/MixFile.cs
  OpenRA.Mods.Common/EditorBrushes/EditorTileBrush.cs
  OpenRA.Mods.Common/FileFormats/WavReader.cs
  OpenRA.Mods.Common/Graphics/DefaultSpriteSequence.cs
  OpenRA.Mods.Common/Pathfinder/HierarchicalPathFinder.cs
  OpenRA.Mods.Common/Traits/BotModules/BotModuleLogic/BaseBuilderQueueManager.cs
  OpenRA.Mods.Common/Traits/BotModules/SupportPowerBotModule.cs
  OpenRA.Mods.Common/Traits/Crates/GiveCashCrateAction.cs
  OpenRA.Mods.Common/Widgets/LineGraphWidget.cs
  OpenRA.Mods.Common/Widgets/Logic/Editor/LayerSelectorLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Ingame/ClassicProductionLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Ingame/ProductionTooltipLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/ServerListLogic.cs
  OpenRA.Mods.Common/Widgets/ScrollPanelWidget.cs
  OpenRA.Mods.Common/Widgets/SliderWidget.cs
  OpenRA.Mods.Common/Widgets/TextFieldWidget.cs
  OpenRA.Mods.D2k/UtilityCommands/D2kMapImporter.cs
Labels: PR: Needs +2

#20704 When running a server, don't load minimap previews into memory.
  OpenRA.Game/Map/MapCache.cs
  OpenRA.Game/Map/MapPreview.cs
  OpenRA.Server/Program.cs
Labels: PR: Needs +2, PR: For stable

#20717 Updated Mono.Nat, SharpZipLib and Linguini
  OpenRA.Game/OpenRA.Game.csproj
Labels: PR: Needs +2

#20718 Fix some whitespace formatting issues
  OpenRA.Game/FieldLoader.cs
  OpenRA.Game/Graphics/SheetBuilder.cs
  OpenRA.Game/Map/MapGrid.cs
  OpenRA.Game/Support/VariableExpression.cs
  OpenRA.Game/Traits/World/DebugVisualizations.cs
  OpenRA.Mods.Cnc/Traits/Render/WithVoxelWalkerBody.cs
  OpenRA.Mods.Cnc/Traits/TDGunboat.cs
  OpenRA.Mods.Common/FileFormats/Blast.cs
  OpenRA.Mods.Common/FileFormats/InstallShieldCABCompression.cs
  OpenRA.Mods.Common/Graphics/IsometricSelectionBarsAnnotationRenderable.cs
  OpenRA.Mods.Common/Pathfinder/CellInfoLayerPool.cs
  OpenRA.Mods.Common/Projectiles/Missile.cs
  OpenRA.Mods.Common/Traits/Buildings/BuildingUtils.cs
  OpenRA.Mods.Common/Traits/Player/HarvesterAttackNotifier.cs
  OpenRA.Mods.Common/Traits/Render/WithDamageOverlay.cs
  OpenRA.Mods.Common/Traits/World/MapOptions.cs
  OpenRA.Mods.Common/Widgets/ColorMixerWidget.cs
  OpenRA.Mods.Common/Widgets/LineGraphWidget.cs
  OpenRA.Mods.Common/Widgets/Logic/Ingame/IngameMenuLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Lobby/MapPreviewLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/ReplayBrowserLogic.cs
  OpenRA.Platforms.Default/Sdl2PlatformWindow.cs
Labels: PR: Needs +2

#20719 Spelling fixes
  OpenRA.Game/Map/MapCache.cs
  OpenRA.Game/Scripting/ScriptMemberWrapper.cs
  OpenRA.Game/Settings.cs
  OpenRA.Game/WRot.cs
  OpenRA.Mods.Common/Scripting/Properties/CaptureProperties.cs
  OpenRA.Mods.Common/Traits/Air/Aircraft.cs
  OpenRA.Mods.Common/Traits/Harvester.cs
  OpenRA.Mods.Common/Traits/World/LegacyBridgeLayer.cs
  OpenRA.Mods.Common/Traits/World/ShroudRenderer.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20210321/RenameContrailProperties.cs
  OpenRA.Mods.Common/Widgets/Logic/MainMenuLogic.cs
  mods/common/languages/en.ftl
Labels: PR: Needs +2

#19985 Added Launch parameters to Settings documentation
  OpenRA.Mods.Common/UtilityCommands/ExtractSettingsDocsCommand.cs
Labels: PR: Needs +2

#20729 Moved JumpJet traits to the C&C library
  OpenRA.Mods.Cnc/Traits/Conditions/GrantConditionOnJumpjetLayer.cs
  OpenRA.Mods.Cnc/Traits/World/JumpjetActorLayer.cs
  OpenRA.Mods.Cnc/Traits/World/JumpjetLocomotor.cs
Labels: PR: Needs +2

#20730 Remove workaround for old versions of mono.
  OpenRA.Game/Primitives/ObservableCollection.cs
  OpenRA.Game/Primitives/ObservableDictionary.cs
  OpenRA.Game/Primitives/ObservableList.cs
Labels: PR: Needs +2

#20728 Renamed GiveMcvCrateAction to GiveBaseBuilderCrateAction
  OpenRA.Mods.Common/Traits/Crates/GiveMcvCrateAction.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20221203/RenameMcvCrateAction.cs
  OpenRA.Mods.Common/UpdateRules/UpdatePath.cs
  mods/cnc/rules/misc.yaml
  mods/d2k/rules/misc.yaml
  mods/ra/maps/fort-lonestar/rules.yaml
  mods/ra/rules/misc.yaml
  mods/ts/rules/misc.yaml
Labels: PR: Needs +2

#20727 Enforce code style rule IDE0053
  .editorconfig
  OpenRA.Game/FieldLoader.cs
  OpenRA.Game/Game.cs
  OpenRA.Game/Server/Server.cs
  OpenRA.Mods.Common/DiscordService.cs
  OpenRA.Mods.Common/Effects/FlashTarget.cs
  OpenRA.Mods.Common/Traits/Buildings/FreeActor.cs
  OpenRA.Mods.Common/Traits/Cargo.cs
  OpenRA.Mods.Common/Traits/Conditions/GrantConditionOnDeploy.cs
  OpenRA.Mods.Common/Traits/Player/MissionObjectives.cs
  OpenRA.Mods.Common/Traits/ReloadAmmoPool.cs
  OpenRA.Mods.Common/Traits/SupportPowers/AirstrikePower.cs
  OpenRA.Mods.Common/Traits/SupportPowers/NukePower.cs
  OpenRA.Mods.Common/Traits/SupportPowers/ParatroopersPower.cs
  OpenRA.Mods.Common/Traits/World/EditorActorLayer.cs
  OpenRA.Mods.Common/UtilityCommands/ExtractZeroBraneStudioLuaAPI.cs
  OpenRA.Mods.Common/Widgets/ConfirmationDialogs.cs
  OpenRA.Mods.Common/Widgets/Logic/AssetBrowserLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Editor/MapEditorTabsLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Editor/NewMapLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/GameSaveBrowserLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/MainMenuLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/MissionBrowserLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/MusicPlayerLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/ReplayBrowserLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Settings/HotkeysSettingsLogic.cs
  OpenRA.Mods.Common/Widgets/ScrollPanelWidget.cs
  OpenRA.Platforms.Default/ThreadedGraphicsContext.cs
Labels: PR: Needs +2

#20721 Add support for dark player colors
  OpenRA.Game/Graphics/HardwarePalette.cs
  OpenRA.Game/Graphics/PlayerColorRemap.cs
  OpenRA.Game/Graphics/WorldRenderer.cs
  glsl/combined.frag
Labels: PR: For stable

#20736 Fix return fire logic ignoring AutoAttack priotities
  OpenRA.Mods.Common/Traits/AutoTarget.cs
Labels: PR: Needs +2, PR: For stable

#20737 Update AUTHORS
  AUTHORS
Labels: PR: Needs +2

#20655 Make Wanders and AttackWander queue activities instead of resolving orders
  OpenRA.Mods.Common/Traits/AttackWander.cs
  OpenRA.Mods.Common/Traits/Wanders.cs
Labels: PR: Needs +2

#20527 Add a CanDeploy check to Transform at FrameEndTask
  OpenRA.Mods.Common/Activities/Transform.cs
Labels: PR: Needs +2

#20677 Fix empty mission objectives getting translated
  mods/common/scripts/utils.lua
Labels: PR: Needs +2

#20722 Add player names to support weapon timers
  OpenRA.Mods.Common/Widgets/SupportPowerTimerWidget.cs
Labels: PR: Needs +2, PR: For stable

#20740 Fix modcontent's chrome-3x.png
  mods/modcontent/chrome-3x.png
Labels: PR: Needs +2

#20657 ProductionPaletteWidget: make queued count customizable
  OpenRA.Mods.Common/Widgets/ProductionPaletteWidget.cs
Labels: PR: Needs +2

#20696 Enforce code rule IDE0032
  .editorconfig
  OpenRA.Game/FileSystem/Folder.cs
  OpenRA.Game/FileSystem/ZipFile.cs
  OpenRA.Game/Graphics/SheetBuilder.cs
  OpenRA.Game/Graphics/SpriteRenderable.cs
  OpenRA.Game/Graphics/UISpriteRenderable.cs
  OpenRA.Game/Graphics/Viewport.cs
  OpenRA.Game/Map/CellRegion.cs
  OpenRA.Game/Map/MapCoordsRegion.cs
  OpenRA.Game/Map/ProjectedCellRegion.cs
  OpenRA.Game/Network/Connection.cs
  OpenRA.Game/Network/Order.cs
  OpenRA.Game/Network/TickTime.cs
  OpenRA.Game/Renderer.cs
  OpenRA.Game/Sound/Sound.cs
  OpenRA.Game/Traits/Player/FrozenActorLayer.cs
  OpenRA.Game/Traits/Target.cs
  OpenRA.Mods.Cnc/Graphics/TeslaZapRenderable.cs
  OpenRA.Mods.Cnc/Traits/TDGunboat.cs
  OpenRA.Mods.Common/AudioLoaders/Mp3Loader.cs
  OpenRA.Mods.Common/Graphics/BeamRenderable.cs
  OpenRA.Mods.Common/Graphics/CircleAnnotationRenderable.cs
  OpenRA.Mods.Common/Graphics/ContrailRenderable.cs
  OpenRA.Mods.Common/Graphics/DetectionCircleAnnotationRenderable.cs
  OpenRA.Mods.Common/Graphics/IsometricSelectionBarsAnnotationRenderable.cs
  OpenRA.Mods.Common/Graphics/IsometricSelectionBoxAnnotationRenderable.cs
  OpenRA.Mods.Common/Graphics/LineAnnotationRenderable.cs
  OpenRA.Mods.Common/Graphics/ModelRenderable.cs
  OpenRA.Mods.Common/Graphics/PolygonAnnotationRenderable.cs
  OpenRA.Mods.Common/Graphics/RailgunRenderable.cs
  OpenRA.Mods.Common/Graphics/RangeCircleAnnotationRenderable.cs
  OpenRA.Mods.Common/Graphics/SelectionBarsAnnotationRenderable.cs
  OpenRA.Mods.Common/Graphics/SelectionBoxAnnotationRenderable.cs
  OpenRA.Mods.Common/Graphics/TextAnnotationRenderable.cs
  OpenRA.Mods.Common/Graphics/UIModelRenderable.cs
  OpenRA.Mods.Common/Graphics/UITextRenderable.cs
  OpenRA.Mods.Common/Terrain/DefaultTileCache.cs
  OpenRA.Mods.Common/Traits/Air/Aircraft.cs
  OpenRA.Mods.Common/Traits/Armament.cs
  OpenRA.Mods.Common/Traits/AutoTarget.cs
  OpenRA.Mods.Common/Traits/BotModules/BaseBuilderBotModule.cs
  OpenRA.Mods.Common/Traits/Conditions/GrantConditionOnDeploy.cs
  OpenRA.Mods.Common/Traits/Husk.cs
  OpenRA.Mods.Common/Traits/Mobile.cs
  OpenRA.Mods.Common/Traits/Player/ProductionQueue.cs
  OpenRA.Mods.Common/Traits/Player/TechTree.cs
  OpenRA.Mods.Common/Traits/SupportPowers/SpawnActorPower.cs
  OpenRA.Mods.Common/Traits/SupportPowers/SupportPowerManager.cs
  OpenRA.Mods.Common/Traits/World/ActorMap.cs
  OpenRA.Mods.Common/Widgets/VideoPlayerWidget.cs
  OpenRA.Platforms.Default/Sdl2PlatformWindow.cs
  OpenRA.Platforms.Default/ThreadedGraphicsContext.cs
Labels: PR: Needs +2

#20747 Remove annoying autocomplete suffix
  OpenRA.Mods.Common/Widgets/Logic/TabCompletionLogic.cs
Labels: PR: Needs +2, PR: For stable

#20726 Enforce additional style rules.
  .editorconfig
  Directory.Build.props
  Makefile
  OpenRA.ruleset
  make.ps1
Labels: PR: Needs +2, PR: Fixup requested

#20752 Enforce StyleCop rules
  .editorconfig
  OpenRA.Game/Actor.cs
  OpenRA.Game/ExternalMods.cs
  OpenRA.Game/FileSystem/FileSystem.cs
  OpenRA.Game/GameRules/WeaponInfo.cs
  OpenRA.Game/Graphics/Model.cs
  OpenRA.Game/Graphics/RgbaColorRenderer.cs
  OpenRA.Game/Graphics/SpriteLoader.cs
  OpenRA.Game/Graphics/Util.cs
  OpenRA.Game/Graphics/Viewport.cs
  OpenRA.Game/Input/HotkeyReference.cs
  OpenRA.Game/MPos.cs
  OpenRA.Game/Manifest.cs
  OpenRA.Game/Map/CellLayer.cs
  OpenRA.Game/Map/CellLayerBase.cs
  OpenRA.Game/Map/Map.cs
  OpenRA.Game/Map/MapCache.cs
  OpenRA.Game/Map/MapPreview.cs
  OpenRA.Game/Map/PlayerReference.cs
  OpenRA.Game/Network/GameServer.cs
  OpenRA.Game/Network/OrderManager.cs
  OpenRA.Game/Player.cs
  OpenRA.Game/WAngle.cs
  OpenRA.Game/WPos.cs
  OpenRA.Game/WRot.cs
  OpenRA.Game/Widgets/Widget.cs
  OpenRA.Game/World.cs
  OpenRA.Mods.Cnc/FileFormats/CRC32.cs
  OpenRA.Mods.Cnc/FileSystem/MegFile.cs
  OpenRA.Mods.Common/Activities/Enter.cs
  OpenRA.Mods.Common/Activities/FindAndDeliverResources.cs
  OpenRA.Mods.Common/Pathfinder/CellInfo.cs
  OpenRA.Mods.Common/Pathfinder/PathSearch.cs
  OpenRA.Mods.Common/TargetExtensions.cs
  OpenRA.Mods.Common/Traits/BotModules/BotModuleLogic/SupportPowerDecision.cs
  OpenRA.Mods.Common/Traits/Carryall.cs
  OpenRA.Mods.Common/UpdateRules/UpdateRule.cs
  OpenRA.Mods.Common/UpdateRules/UpdateUtils.cs
  OpenRA.Mods.Common/Util.cs
  OpenRA.Mods.Common/UtilityCommands/Utilities.cs
  OpenRA.Mods.Common/Widgets/Logic/Ingame/CommandBarLogic.cs
  OpenRA.Mods.Common/WorldExtensions.cs
Labels: PR: Needs +2

#20756 ProductionQueue: make PauseProduction, CancelProduction virtual
  OpenRA.Mods.Common/Traits/Player/ProductionQueue.cs
Labels: PR: Needs +2

#20757 RepairableBuilding: play/display notification when repair process is aborted
  OpenRA.Mods.Common/Traits/Buildings/RepairableBuilding.cs
Labels: PR: Needs +2

#19491 Added particle smoke effects
  OpenRA.Mods.Common/Effects/FloatingSprite.cs
  OpenRA.Mods.Common/Traits/Render/FloatingSpriteEmitter.cs
  OpenRA.Mods.Common/Util.cs
  mods/d2k/rules/defaults.yaml
  mods/d2k/rules/palettes.yaml
  mods/d2k/rules/vehicles.yaml
  mods/d2k/sequences/misc.yaml
Labels: PR: Needs +2

#20760 Rework PriorityQueue for performance.
  OpenRA.Game/Primitives/PriorityQueue.cs
  OpenRA.Mods.Common/Pathfinder/IPathGraph.cs
  OpenRA.Mods.Common/Pathfinder/PathSearch.cs
  OpenRA.Test/OpenRA.Game/PriorityQueueTest.cs
Labels: PR: Needs +2

#20734 Add Interactable lint test
  OpenRA.Mods.Common/Lint/CheckInteractable.cs
Labels: PR: Needs +2, PR: For stable

#20748 Add a quit button to connection lost panel
  OpenRA.Mods.Common/Widgets/Logic/ConnectionLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/DisconnectWatcherLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Ingame/IngameMenuLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Lobby/LobbyLogic.cs
  mods/cnc/chrome/connection.yaml
  mods/common/chrome/connection.yaml
Labels: PR: Needs +2, PR: For stable

#20609 Updated ExtractEmmyLuaAPI command to fix issues
  OpenRA.Mods.Common/UtilityCommands/ExtractEmmyLuaAPI.cs
Labels: PR: Needs +2

#20664 Polish the save dialogue
  OpenRA.Mods.Common/Widgets/Logic/GameSaveBrowserLogic.cs
Labels: PR: Needs +2, PR: Unaddressed comment(s)

#20775 fix two crashes in hotkey menu, trying to select not visible widgets
  OpenRA.Mods.Common/Widgets/Logic/Settings/HotkeysSettingsLogic.cs
Labels: PR: Needs +2, PR: For stable
