Repository OpenRA/OpenRA, pull requests merged in 2023-01, with the labels that each got.

#20537 Fixed exception about invalid cursors not mentioning the cursor name
  OpenRA.Game/Graphics/CursorSequence.cs
Labels: PR: Needs +2

#20596 Remove custom network frame counting from ReplayConnection
  OpenRA.Game/Network/ReplayConnection.cs
Labels: PR: Needs +2, PR: For stable

#20589 Bump checkout and setup .NET action
  .github/workflows/ci.yml
  .github/workflows/documentation.yml
  .github/workflows/packaging.yml
Labels: PR: Needs +2

#20602 Implemented WestwoodCompression for AUD files.
  OpenRA.Mods.Cnc/AudioLoaders/AudLoader.cs
  OpenRA.Mods.Cnc/FileFormats/AudReader.cs
  OpenRA.Mods.Common/FileFormats/ImaAdpcmReader.cs
  OpenRA.Mods.Common/FileFormats/WestwoodCompressedReader.cs
Labels: PR: Needs +2

#20607 Clarify the wording and explain the meaning of some labels in settings
  mods/cnc/chrome/settings-audio.yaml
  mods/cnc/chrome/settings-display.yaml
  mods/common/chrome/settings-audio.yaml
  mods/common/chrome/settings-display.yaml
Labels: PR: Needs +2, PR: For stable

#20612 Update Program.cs
  OpenRA.Utility/Program.cs
Labels: PR: Needs +2

#20610 Fix for Windows uninstaller to remove reg entries from the 64 bit registry
  packaging/windows/OpenRA.nsi
Labels: PR: Needs +2, PR: For stable

#20611 Looped sounds can now be unlooped to avoid cut-offs.
  OpenRA.Game/Sound/Sound.cs
Labels: PR: Needs +2

#20615 Fix Locomotor cache coherency for disabled or paused mobile actors.
  OpenRA.Mods.Common/Traits/World/Locomotor.cs
Labels: PR: Needs +2, PR: For stable

#20172 Move RearmTick to Rearmable
  OpenRA.Mods.Common/Activities/Resupply.cs
  OpenRA.Mods.Common/Traits/Rearmable.cs
Labels: PR: Needs +2

#20624 Add the expected parameter(s) to the ExtractFilesCommand description
  OpenRA.Mods.Common/UtilityCommands/ExtractFilesCommand.cs
Labels: PR: Needs +2

#20629 Add support for Flatpak Steam installs.
  OpenRA.Mods.Common/Installer/SourceResolvers/SteamSourceResolver.cs
Labels: PR: Needs +2

#20634 Move RenameEngineerRepair to its proper folder
  OpenRA.Mods.Common/UpdateRules/Rules/20221203/RenameEngineerRepair.cs
Labels: PR: Needs +2

#20633 Fixed RA parabomb/paradrop support power tooltips
  mods/ra/rules/misc.yaml
  mods/ra/rules/structures.yaml
Labels: PR: Needs +2, PR: For stable

#20630 Only update changed files when saving maps.
  OpenRA.Game/Map/Map.cs
  OpenRA.Mods.Common/UpdateRules/UpdateUtils.cs
Labels: PR: Needs +2

#20520 Optimise TakeCover to have clear states
  OpenRA.Mods.Common/Traits/Infantry/TakeCover.cs
Labels: PR: Needs +2

#20618 Add an option to check if an actor can be captured via Lua
  OpenRA.Mods.Common/Scripting/Properties/CaptureProperties.cs
Labels: PR: Needs +2, PR: For stable

#20174 Clean up DockSequence
  OpenRA.Mods.Cnc/Activities/VoxelHarvesterDockSequence.cs
  OpenRA.Mods.Cnc/Traits/Buildings/TiberianSunRefinery.cs
  OpenRA.Mods.Common/Activities/HarvesterDockSequence.cs
  OpenRA.Mods.Common/Activities/SpriteHarvesterDockSequence.cs
  OpenRA.Mods.Common/Traits/Buildings/Refinery.cs
Labels: PR: Needs +2, PR: Is Dependency
