Repository OpenRA/OpenRA, pull requests merged in 2023-07, with the labels that each got.

#20939 Fix slow saving of map previews.
  OpenRA.Game/Map/Map.cs
Labels: PR: Needs +2

#20937 Fix a crash when RallyPoint creates RallyPointIndicator
  OpenRA.Mods.Common/Traits/Buildings/RallyPoint.cs
Labels: PR: Needs +2

#20935 Fix combined sequences using frames being broken
  OpenRA.Mods.Common/Graphics/DefaultSpriteSequence.cs
Labels: PR: Needs +2

#20159 PerfTickLogger, reduce overhead of logging long ticks.
  OpenRA.Game/Support/PerfTickLogger.cs
  OpenRA.Game/Support/PerfTimer.cs
  OpenRA.Game/TraitDictionary.cs
  OpenRA.Game/Traits/ActivityUtils.cs
  OpenRA.Game/WorldUtils.cs
Labels: PR: Needs +2

#20940 Improve loading performance for loader/compression classes.
  OpenRA.Mods.Cnc/FileFormats/VqaVideo.cs
  OpenRA.Mods.Cnc/Graphics/VoxelLoader.cs
  OpenRA.Mods.Cnc/SpriteLoaders/TmpTSLoader.cs
  OpenRA.Mods.Common/FileFormats/RLEZerosCompression.cs
Labels: PR: Needs +2

#20953 Updated to OpenAL Soft version 1.23.1
  OpenRA.Platforms.Default/OpenRA.Platforms.Default.csproj
Labels: PR: Needs +2

#20960 Make Voiced trait conditional
  OpenRA.Mods.Common/Traits/Voiced.cs
Labels: PR: Needs +2, PR: Fixup requested

#20917 Include Linux DE in OS sysinfo string.
  OpenRA.Game/Platform.cs
Labels: PR: Needs +2

#20961 Make phase transport uncloak on loading cargo
  OpenRA.Mods.Cnc/Traits/Disguise.cs
  OpenRA.Mods.Common/Activities/RideTransport.cs
  OpenRA.Mods.Common/Activities/UnloadCargo.cs
  OpenRA.Mods.Common/Traits/Cloak.cs
  OpenRA.Mods.Common/TraitsInterfaces.cs
  mods/ra/rules/vehicles.yaml
Labels: PR: Needs +2

#20962 Add options in map chooser to order by map title and map size
  OpenRA.Mods.Common/Widgets/Logic/MapChooserLogic.cs
  mods/common/languages/en.ftl
Labels: PR: Needs +2

#20966 Ensure save file is closed after saving
  OpenRA.Game/Network/GameSave.cs
Labels: PR: Needs +2

#20490 Fix carryall not removing influence when cargo dies
  OpenRA.Mods.Common/Activities/PickupUnit.cs
  OpenRA.Mods.Common/Traits/AutoCarryall.cs
  OpenRA.Mods.Common/Traits/Carryall.cs
Labels: PR: Needs +2

#20949 fix: aircraft pause in sky when cruise at undulating ground
  OpenRA.Mods.Common/Traits/Air/Aircraft.cs
Labels: PR: Needs +2

#20897 WorldRenderer: use string.IsNullOrEmpty for check in Palette method
  OpenRA.Game/Graphics/WorldRenderer.cs
  OpenRA.Mods.Common/Traits/Cloak.cs
  OpenRA.Mods.Common/Traits/Render/WithBuildingRepairDecoration.cs
  OpenRA.Mods.Common/Traits/Render/WithIdleOverlay.cs
Labels: PR: Needs +2

#20915 Add a description for AttackBomber
  OpenRA.Mods.Common/Traits/Air/AttackBomber.cs
Labels: PR: Needs +2

#20106 Move PlayerExperience from Infiltrates to InfiltrateFor
  OpenRA.Mods.Cnc/Activities/Infiltrate.cs
  OpenRA.Mods.Cnc/Traits/Infiltration/InfiltrateForCash.cs
  OpenRA.Mods.Cnc/Traits/Infiltration/InfiltrateForDecoration.cs
  OpenRA.Mods.Cnc/Traits/Infiltration/InfiltrateForExploration.cs
  OpenRA.Mods.Cnc/Traits/Infiltration/InfiltrateForPowerOutage.cs
  OpenRA.Mods.Cnc/Traits/Infiltration/InfiltrateForSupportPower.cs
  OpenRA.Mods.Cnc/Traits/Infiltration/InfiltrateForSupportPowerReset.cs
  OpenRA.Mods.Cnc/Traits/Infiltration/InfiltrateForTransform.cs
  OpenRA.Mods.Cnc/Traits/Infiltration/Infiltrates.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20210321/RemoveExperienceFromInfiltrates.cs
  OpenRA.Mods.Common/UpdateRules/UpdatePath.cs
  mods/ra/rules/defaults.yaml
  mods/ra/rules/disable-player-experience.yaml
  mods/ra/rules/infantry.yaml
  mods/ra/rules/structures.yaml
  mods/ts/rules/gdi-structures.yaml
  mods/ts/rules/nod-structures.yaml
Labels: PR: Needs +2

#20968 LayMines: fixed occasional incorrect mine position when using BeginMinefield order
  OpenRA.Mods.Common/Activities/LayMines.cs
Labels: PR: Unaddressed comment(s)

#20974 Fix hunt incorrectly pathing to uncrushable targets
  OpenRA.Mods.Common/Activities/Hunt.cs
Labels: PR: Needs +2

#19363 Add Soviet13a
  mods/ra/languages/lua/en.ftl
  mods/ra/maps/soviet-13a/map.bin
  mods/ra/maps/soviet-13a/map.png
  mods/ra/maps/soviet-13a/map.yaml
  mods/ra/maps/soviet-13a/rules.yaml
  mods/ra/maps/soviet-13a/soviet13a-AI.lua
  mods/ra/maps/soviet-13a/soviet13a.lua
  mods/ra/missions.yaml
Labels: PR: Needs +2, PR: Fixup requested

#20979 Revert Hunt to move within 2 cells of the target
  OpenRA.Mods.Common/Activities/Hunt.cs
  OpenRA.Mods.Common/Scripting/Properties/CombatProperties.cs
Labels: PR: Needs +2

#20860 Make yaml node resolving optional
  OpenRA.Mods.Common/UpdateRules/Rules/20210321/UnhardcodeBaseBuilderBotModule.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20210321/UnhardcodeSquadManager.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20230225/ExplicitSequenceFilenames.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20230225/RemoveNegativeSequenceLength.cs
  OpenRA.Mods.Common/UpdateRules/UpdatePath.cs
  OpenRA.Mods.Common/UpdateRules/UpdateRule.cs
  OpenRA.Mods.Common/UpdateRules/UpdateUtils.cs
Labels: PR: Needs +2
