Repository OpenRA/OpenRA, pull requests merged in 2023-05, with the labels that each got.

#20840 Fixed a null reference exception upon empty Fluent strings
  OpenRA.Mods.Common/Lint/CheckTranslationReference.cs
Labels: PR: Needs +2

#20846 TechTree.GatherOwnedPrerequisites performance improvements.
  OpenRA.Mods.Cnc/Traits/SupportPowers/GrantPrerequisiteChargeDrainPower.cs
  OpenRA.Mods.Common/Traits/Player/ProvidesPrerequisite.cs
  OpenRA.Mods.Common/Traits/Player/ProvidesTechPrerequisite.cs
  OpenRA.Mods.Common/Traits/Player/TechTree.cs
Labels: PR: Needs +2

#20820 Chrome string translation preparations
  OpenRA.Mods.Common/Widgets/Logic/Ingame/IngameCashCounterLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Ingame/ProductionTooltipLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/MainMenuLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Settings/HotkeysSettingsLogic.cs
  mods/cnc/chrome/dialogs.yaml
  mods/cnc/chrome/ingame.yaml
  mods/cnc/chrome/settings-hotkeys.yaml
  mods/cnc/chrome/tooltips.yaml
  mods/common/chrome/connection.yaml
  mods/common/chrome/dropdowns.yaml
  mods/common/chrome/settings-hotkeys.yaml
  mods/common/chrome/tooltips.yaml
  mods/common/languages/en.ftl
  mods/d2k/chrome/dropdowns.yaml
  mods/d2k/chrome/ingame-player.yaml
  mods/d2k/chrome/tooltips.yaml
  mods/ra/chrome/ingame-player.yaml
  mods/ts/chrome/dropdowns.yaml
  mods/ts/chrome/ingame-player.yaml
  mods/ts/chrome/settings-hotkeys.yaml
Labels: PR: Needs +2, PR: Is Dependency

#20852 Cache the notifyAttacks in AttackGarrisoned
  OpenRA.Mods.Common/Traits/Attack/AttackGarrisoned.cs
Labels: PR: Needs +2

#20865 Small cleanup inside DefaultSpriteSequence.cs
  OpenRA.Mods.Common/Graphics/DefaultSpriteSequence.cs
Labels: PR: Needs +2

#20833 Add missing RA balance changes
  mods/ra/rules/aircraft.yaml
  mods/ra/rules/vehicles.yaml
Labels: PR: Needs +2

#20859 Fixed duplicate asset selection in asset browser.
  OpenRA.Mods.Common/Widgets/Logic/AssetBrowserLogic.cs
Labels: PR: Needs +2

#20866 Remove wrong definitions from TD's notifications.yaml
  mods/cnc/audio/notifications.yaml
Labels: PR: Needs +2

#18602 Enable the restart button for missions with script errors
  OpenRA.Mods.Common/Widgets/Logic/Ingame/IngameMenuLogic.cs
Labels: PR: Needs +2

#20839 Allow EMP cannon to EMP itself
  mods/ts/weapons/superweapons.yaml
Labels: PR: Needs +2

#20818 Add GDI Covert Operations - Twist of Fate - scg41ea
  mods/cnc/languages/lua/en.ftl
  mods/cnc/maps/twist-of-fate/map.bin
  mods/cnc/maps/twist-of-fate/map.png
  mods/cnc/maps/twist-of-fate/map.yaml
  mods/cnc/maps/twist-of-fate/rules.yaml
  mods/cnc/maps/twist-of-fate/twist-of-fate-AI.lua
  mods/cnc/maps/twist-of-fate/twist-of-fate.lua
  mods/cnc/maps/twist-of-fate/weapons.yaml
  mods/cnc/missions.yaml
Labels: PR: Needs +2

#20386 Add Autocrusher for baby visc
  OpenRA.Mods.Common/Traits/AutoCrusher.cs
  mods/ts/rules/critters.yaml
Labels: PR: Needs +2

#18802 Removed the need to wrap and sandbox scripts using Lua
  Makefile
  OpenRA.Game/Scripting/ScriptContext.cs
  OpenRA.Mods.Common/Scripting/CallLuaFunc.cs
  OpenRA.Mods.Common/Scripting/Global/MediaGlobal.cs
  OpenRA.Mods.Common/Scripting/Global/TriggerGlobal.cs
  OpenRA.Mods.Common/Scripting/LuaScript.cs
  OpenRA.Mods.Common/Scripting/ScriptTriggers.cs
  OpenRA.Mods.Common/Widgets/Logic/Ingame/ScriptErrorLogic.cs
  lua/sandbox.lua
  lua/scriptwrapper.lua
  lua/stacktraceplus.lua
  make.ps1
  mods/cnc/chrome/ingame-infoscripterror.yaml
  mods/cnc/mod.yaml
  mods/common/chrome/ingame-infoscripterror.yaml
Labels: PR: Needs +2, PR: Fixup requested

#19487 Add Allies10b
  mods/ra/languages/lua/en.ftl
  mods/ra/maps/allies-10b/allies10b.lua
  mods/ra/maps/allies-10b/map.bin
  mods/ra/maps/allies-10b/map.png
  mods/ra/maps/allies-10b/map.yaml
  mods/ra/maps/allies-10b/notifications.yaml
  mods/ra/maps/allies-10b/rules.yaml
  mods/ra/missions.yaml
Labels: PR: Needs +2

#20872 Fix a rare crash when actor in IBotRespondToAttack is dead
  OpenRA.Mods.Common/Traits/BotModules/BuildingRepairBotModule.cs
Labels: PR: Needs +2

#20881 Fix ScriptContext crashing without a Tick function
  OpenRA.Game/Scripting/ScriptContext.cs
Labels: PR: Needs +2

#20878 Remove reference to deleted lua directory
  packaging/functions.sh
Labels: PR: Needs +2

#20848 Adjust the ValidTargets of DuplicateUnitCrateAction in RA
  mods/ra/rules/misc.yaml
Labels: PR: Needs +2

#20843 Fix HierarchicalPathFinder pathing from inaccessible source locations.
  OpenRA.Mods.Common/Pathfinder/HierarchicalPathFinder.cs
  OpenRA.Mods.Common/Pathfinder/PathSearch.cs
Labels: PR: Needs +2

#20880 Remove references to the deleted Lua directory from Windows packaging
  packaging/windows/OpenRA.nsi
Labels: PR: Needs +2

#20868 Add causes for TargetInvocationException in TriggerGlobal
  OpenRA.Game/Scripting/ScriptMemberWrapper.cs
  OpenRA.Mods.Common/Scripting/Global/TriggerGlobal.cs
Labels: PR: Needs +2

#20876 Exposed editor brush texts to localisation
  OpenRA.Mods.Common/EditorBrushes/EditorActorBrush.cs
  OpenRA.Mods.Common/EditorBrushes/EditorCopyPasteBrush.cs
  OpenRA.Mods.Common/EditorBrushes/EditorDefaultBrush.cs
  OpenRA.Mods.Common/EditorBrushes/EditorResourceBrush.cs
  OpenRA.Mods.Common/EditorBrushes/EditorTileBrush.cs
  OpenRA.Mods.Common/Traits/World/EditorActionManager.cs
  OpenRA.Mods.Common/Widgets/Logic/Editor/ActorEditLogic.cs
  mods/common/languages/en.ftl
Labels: PR: Needs +2

#20889 Fixed benchmark CSV export using inconsistent formatting
  OpenRA.Game/Support/Benchmark.cs
Labels: PR: Needs +2

#20857 Fix the ExplicitSequenceFilenames rule breaking when updating single maps
  OpenRA.Mods.Common/UpdateRules/Rules/20221203/ExplicitSequenceFilenames.cs
Labels: PR: Needs +2
