Repository OpenRA/OpenRA, pull requests merged in 2023-12, with the labels that each got.

#21228 Fix InitialActor in Carryall not initialized correctly
  OpenRA.Mods.Common/Activities/PickupUnit.cs
  OpenRA.Mods.Common/Traits/Carryable.cs
  OpenRA.Mods.Common/Traits/Carryall.cs
Labels: PR: Needs +2

#21240 Use higher colour depth R16 sprites in D2k.
  OpenRA.Mods.D2k/Graphics/D2kSpriteSequence.cs
  OpenRA.Mods.D2k/SpriteLoaders/R8Loader.cs
  mods/d2k/bits/fog.pal
  mods/d2k/bits/fog.png
  mods/d2k/bits/fullshroud.shp
  mods/d2k/bits/shroud.pal
  mods/d2k/bits/shroud.png
  mods/d2k/cursors.yaml
  mods/d2k/installer/d2k.yaml
  mods/d2k/installer/downloads.yaml
  mods/d2k/installer/gruntmods.yaml
  mods/d2k/maps/atreides-04/sequences.yaml
  mods/d2k/maps/harkonnen-05/rules.yaml
  mods/d2k/maps/harkonnen-06a/rules.yaml
  mods/d2k/maps/harkonnen-06b/rules.yaml
  mods/d2k/maps/harkonnen-07/rules.yaml
  mods/d2k/maps/harkonnen-08/rules.yaml
  mods/d2k/maps/harkonnen-09a/rules.yaml
  mods/d2k/maps/harkonnen-09b/rules.yaml
  mods/d2k/maps/ordos-05/rules.yaml
  mods/d2k/mod.yaml
  mods/d2k/rules/campaign-palettes.yaml
  mods/d2k/rules/defaults.yaml
  mods/d2k/rules/palettes.yaml
  mods/d2k/rules/world.yaml
  mods/d2k/sequences/aircraft.yaml
  mods/d2k/sequences/infantry.yaml
  mods/d2k/sequences/misc.yaml
  mods/d2k/sequences/structures.yaml
  mods/d2k/sequences/vehicles.yaml
  mods/d2k/tilesets/arrakis.yaml
Labels: PR: Is Dependency

#21269 implements flashing on healing units
  OpenRA.Mods.Common/Warheads/FlashTargetsInRadiusWarhead.cs
  mods/ra/weapons/other.yaml
  mods/ts/weapons/healweapons.yaml
Labels: PR: Fixup requested
