Repository OpenRA/OpenRA, pull requests merged in 2023-10, with the labels that each got.

#21094 Add NotBefore<SpawnStartingUnitsInfo> to LuaScriptInfo
  OpenRA.Mods.Common/Scripting/LuaScript.cs
Labels: PR: For stable

#21090 GrantConditionOnDeployWithCharge requires no IMove
  OpenRA.Mods.Common/Traits/Conditions/GrantConditionOnDeployWithCharge.cs
Labels: PR: Needs +2

#21110 Added missing deprecation notices to Lua docs
  OpenRA.Mods.Common/UtilityCommands/ExtractLuaDocsCommand.cs
Labels: PR: Needs +2

#21074 Remove the possibility of ReloadDelay becoming 0 with modifiers
  OpenRA.Mods.Common/Traits/Armament.cs
Labels: PR: Needs +2

#21128 DetectCloaked: actor should be in world
  OpenRA.Mods.Common/Traits/Cloak.cs
Labels: PR: Needs +2

#21124 Allow actors to target terrain without force-fire
  OpenRA.Mods.Common/Traits/Attack/AttackBase.cs
Labels: PR: Fixup requested

#21100 Update DiscordRichPresence to version 1.2.1.24
  OpenRA.Mods.Common/OpenRA.Mods.Common.csproj
Labels: PR: Needs +2

#21165 Fix Locomotor.CanMoveFreelyInto when using ignoreSelf.
  OpenRA.Mods.Common/Traits/World/Locomotor.cs
Labels: PR: Needs +2

#21159 Allow changing ZOffset of renderables in ActorPreviewPlaceBuildingPreview
  OpenRA.Mods.Common/Traits/Buildings/ActorPreviewPlaceBuildingPreview.cs
Labels: PR: Needs +2

#21013 Enable Roslynator
  .editorconfig
  Directory.Build.props
Labels: PR: Needs +2

#21174 Increase sound source pool size to the maximum
  OpenRA.Platforms.Default/OpenAlSoundEngine.cs
Labels: PR: Needs +2
