Repository OpenRA/OpenRA, pull requests merged in 2023-09, with the labels that each got.

#21038 Simplify matrix utils
  OpenRA.Game/Graphics/Util.cs
Labels: PR: Needs +2

#21018 Better Naval AI
  mods/ra/rules/ai.yaml
Labels: PR: Fixup requested

#20261 Move ValidRelations from Capturable to Captures
  OpenRA.Mods.Common/Activities/CaptureActor.cs
  OpenRA.Mods.Common/Scripting/Properties/CaptureProperties.cs
  OpenRA.Mods.Common/Traits/BotModules/CaptureManagerBotModule.cs
  OpenRA.Mods.Common/Traits/Capturable.cs
  OpenRA.Mods.Common/Traits/CaptureManager.cs
  OpenRA.Mods.Common/Traits/Captures.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20230801/RemoveValidRelationsFromCapturable.cs
  OpenRA.Mods.Common/UpdateRules/UpdatePath.cs
  mods/cnc/rules/defaults.yaml
  mods/cnc/rules/infantry.yaml
  mods/ra/maps/intervention/rules.yaml
  mods/ra/rules/defaults.yaml
Labels: PR: Needs +2

#20120 Add Play Map button to map editor
  OpenRA.Mods.Common/Widgets/Logic/Ingame/IngameMenuLogic.cs
  mods/cnc/chrome/ingame-menu.yaml
  mods/common/chrome/ingame-menu.yaml
  mods/common/languages/en.ftl
  mods/d2k/chrome/ingame-menu.yaml
Labels: PR: Needs +2

#20806 Fix Drop Pods
  OpenRA.Mods.Cnc/Traits/SupportPowers/DropPodsPower.cs
Labels: PR: Needs +2

#20832 Increase Iron Curtain's footprint
  mods/ra/rules/structures.yaml
  mods/ra/sequences/structures.yaml
Labels: PR: Needs +2

#21063 Bumped Eluant NuGet version
  OpenRA.Game/OpenRA.Game.csproj
Labels: PR: For stable

#21026 Add backup `ExplicitSequenceFilenames` to update rules
  OpenRA.Mods.Common/UpdateRules/Rules/20230225/ExplicitSequenceFilenames.cs
Labels: PR: For stable

#21071 Fix units considering terrain when entering other actors
  OpenRA.Mods.Common/Activities/Enter.cs
  OpenRA.Mods.Common/Activities/Move/LocalMoveIntoTarget.cs
Labels: PR: Needs +2

#21065 Bytes -> Hex conversion update
  OpenRA.Game/CryptoUtil.cs
  OpenRA.Game/Primitives/Color.cs
  OpenRA.Test/OpenRA.Game/Sha1Tests.cs
Labels: PR: Needs +2

#20515 Fix EjectOnDeath checks
  OpenRA.Mods.Common/Traits/Cargo.cs
Labels: PR: Needs +2

#20835 Improve CandidateMouseoverCells logic
  OpenRA.Game/Graphics/Viewport.cs
Labels: PR: Needs +2

#21022 Improve lookups of nodes by key in MiniYaml.
  OpenRA.Game/ExternalMods.cs
  OpenRA.Game/GameRules/SoundInfo.cs
  OpenRA.Game/GameRules/WeaponInfo.cs
  OpenRA.Game/GameSpeed.cs
  OpenRA.Game/Graphics/CursorProvider.cs
  OpenRA.Game/HotkeyDefinition.cs
  OpenRA.Game/Manifest.cs
  OpenRA.Game/Map/Map.cs
  OpenRA.Game/MiniYaml.cs
  OpenRA.Game/Network/GameServer.cs
  OpenRA.Game/Network/LocalizedMessage.cs
  OpenRA.Game/Network/Session.cs
  OpenRA.Game/PlayerDatabase.cs
  OpenRA.Game/PlayerProfile.cs
  OpenRA.Game/Settings.cs
  OpenRA.Game/Traits/TraitsInterfaces.cs
  OpenRA.Game/Widgets/WidgetLoader.cs
  OpenRA.Game/World.cs
  OpenRA.Mods.Cnc/Graphics/ClassicTilesetSpecificSpriteSequence.cs
  OpenRA.Mods.Cnc/UtilityCommands/ImportGen1MapCommand.cs
  OpenRA.Mods.Common/Graphics/DefaultSpriteSequence.cs
  OpenRA.Mods.Common/Graphics/TilesetSpecificSpriteSequence.cs
  OpenRA.Mods.Common/Installer/InstallerUtils.cs
  OpenRA.Mods.Common/Installer/SourceActions/ExtractIscabSourceAction.cs
  OpenRA.Mods.Common/Installer/SourceActions/ExtractRawSourceAction.cs
  OpenRA.Mods.Common/Installer/SourceResolvers/GogSourceResolver.cs
  OpenRA.Mods.Common/Installer/SourceResolvers/SteamSourceResolver.cs
  OpenRA.Mods.Common/Lint/CheckCursors.cs
  OpenRA.Mods.Common/ModContent.cs
  OpenRA.Mods.Common/Terrain/TerrainInfo.cs
  OpenRA.Mods.Common/Traits/AppearsOnMapPreview.cs
  OpenRA.Mods.Common/Traits/BotModules/BaseBuilderBotModule.cs
  OpenRA.Mods.Common/Traits/BotModules/McvManagerBotModule.cs
  OpenRA.Mods.Common/Traits/BotModules/SquadManagerBotModule.cs
  OpenRA.Mods.Common/Traits/BotModules/Squads/Squad.cs
  OpenRA.Mods.Common/Traits/BotModules/SupportPowerBotModule.cs
  OpenRA.Mods.Common/Traits/BotModules/UnitBuilderBotModule.cs
  OpenRA.Mods.Common/Traits/Buildings/Building.cs
  OpenRA.Mods.Common/Traits/HitShape.cs
  OpenRA.Mods.Common/Traits/Player/GameSaveViewportManager.cs
  OpenRA.Mods.Common/Traits/World/ControlGroups.cs
  OpenRA.Mods.Common/Traits/World/EditorResourceLayer.cs
  OpenRA.Mods.Common/Traits/World/Locomotor.cs
  OpenRA.Mods.Common/Traits/World/ResourceLayer.cs
  OpenRA.Mods.Common/Traits/World/ResourceRenderer.cs
  OpenRA.Mods.Common/Traits/World/Selection.cs
  OpenRA.Mods.Common/Traits/World/SmudgeLayer.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20230225/ExplicitSequenceFilenames.cs
  OpenRA.Mods.Common/UpdateRules/UpdateUtils.cs
  OpenRA.Mods.Common/Widgets/ControlGroupsWidget.cs
  OpenRA.Mods.Common/Widgets/Logic/Installation/InstallFromSourceLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/ServerListLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Settings/HotkeysSettingsLogic.cs
  OpenRA.Mods.Common/Widgets/ProductionPaletteWidget.cs
  OpenRA.Mods.Common/Widgets/SupportPowersWidget.cs
  OpenRA.Mods.Common/Widgets/ViewportControllerWidget.cs
  OpenRA.Mods.D2k/UtilityCommands/D2kMapImporter.cs
  OpenRA.Test/OpenRA.Game/MiniYamlTest.cs
  mods/ts/sequences/civilian.yaml
  mods/ts/sequences/structures.yaml
Labels: PR: Needs +2
