Repository OpenRA/OpenRA, pull requests merged in 2024-12, with the labels that each got.

#21659 Translation Key Fixes Round 2
  mods/cnc/chrome/editor.yaml
  mods/cnc/chrome/ingame-infostats.yaml
  mods/cnc/chrome/lobby-kickdialogs.yaml
  mods/cnc/fluent/chrome.ftl
  mods/common/chrome/editor.yaml
  mods/common/chrome/ingame-infostats.yaml
  mods/common/chrome/lobby-kickdialogs.yaml
  mods/common/fluent/chrome.ftl
  mods/d2k/chrome/ingame-infostats.yaml
  mods/d2k/fluent/lua.ftl
  mods/d2k/fluent/rules.ftl
  mods/d2k/maps/atreides-01a/atreides01a.lua
  mods/d2k/maps/atreides-01b/atreides01b.lua
  mods/d2k/maps/harkonnen-01a/harkonnen01a.lua
  mods/d2k/maps/harkonnen-01b/harkonnen01b.lua
  mods/d2k/maps/harkonnen-08/harkonnen08.lua
  mods/d2k/maps/ordos-01a/ordos01a.lua
  mods/d2k/maps/ordos-01b/ordos01b.lua
  mods/d2k/rules/player.yaml
  mods/d2k/rules/structures.yaml
  mods/ra/fluent/lua.ftl
  mods/ra/maps/allies-08a/allies08a.lua
  mods/ra/maps/allies-08b/allies08b.lua
Labels: PR: Needs +2

#21673 Revert "Restore threaded renderer on Windows in windowed mode."
  OpenRA.Platforms.Default/Sdl2PlatformWindow.cs
Labels: PR: For stable

#21670 Fix broken condition support for InstantlyRepairable.
  OpenRA.Mods.Common/Traits/InstantlyRepairs.cs
Labels: PR: Needs +2, PR: For stable

#21664 Fix "Package 'NuGet.CommandLine' 4.4.1 has a known moderate severity vulnerability"
  OpenRA.Mods.Common/OpenRA.Mods.Common.csproj
Labels: PR: For stable

#21672 Reduce the size of battlefield news when messages are short
  OpenRA.Mods.Common/Widgets/Logic/MainMenuLogic.cs
  mods/cnc/chrome/dialogs.yaml
  mods/common/chrome/dropdowns.yaml
  mods/d2k/chrome/dropdowns.yaml
  mods/ts/chrome/dropdowns.yaml
Labels: PR: For stable, PR: Fixup requested

#21665 Fix BaseBuilderBotModule.LocomotorsForProducibles.
  OpenRA.Mods.Common/Traits/BotModules/BaseBuilderBotModule.cs
Labels: PR: For stable

#21661 Add deploy while moving to Saboteur
  OpenRA.Mods.Common/Traits/Conditions/GrantChargedConditionOnToggle.cs
  mods/d2k/rules/infantry.yaml
  mods/ts/rules/gdi-vehicles.yaml
Labels: PR: For stable
