Repository OpenRA/OpenRA, pull requests merged in 2024-08, with the labels that each got.

#21501 Improve Lua type documentation and bindings.
  OpenRA.Game/CPos.cs
  OpenRA.Game/CVec.cs
  OpenRA.Game/WAngle.cs
  OpenRA.Game/WDist.cs
  OpenRA.Game/WPos.cs
  OpenRA.Game/WVec.cs
  OpenRA.Mods.Cnc/Scripting/Properties/ChronosphereProperties.cs
  OpenRA.Mods.Common/ActorInitializer.cs
  OpenRA.Mods.Common/Scripting/Global/ActorGlobal.cs
  OpenRA.Mods.Common/Scripting/Global/AngleGlobal.cs
  OpenRA.Mods.Common/Scripting/Global/ColorGlobal.cs
  OpenRA.Mods.Common/Scripting/Global/CoordinateGlobals.cs
  OpenRA.Mods.Common/Scripting/Global/DateTimeGlobal.cs
  OpenRA.Mods.Common/Scripting/Global/LightingGlobal.cs
  OpenRA.Mods.Common/Scripting/Global/MapGlobal.cs
  OpenRA.Mods.Common/Scripting/Global/MediaGlobal.cs
  OpenRA.Mods.Common/Scripting/Global/PlayerGlobal.cs
  OpenRA.Mods.Common/Scripting/Global/ReinforcementsGlobal.cs
  OpenRA.Mods.Common/Scripting/Global/TriggerGlobal.cs
  OpenRA.Mods.Common/Scripting/Global/UserInterfaceGlobal.cs
  OpenRA.Mods.Common/Scripting/Global/UtilsGlobal.cs
  OpenRA.Mods.Common/Scripting/Properties/CombatProperties.cs
  OpenRA.Mods.Common/Scripting/Properties/GeneralProperties.cs
  OpenRA.Mods.Common/Scripting/Properties/HealthProperties.cs
  OpenRA.Mods.Common/Scripting/Properties/PlayerExperienceProperties.cs
  OpenRA.Mods.Common/Scripting/Properties/ProductionProperties.cs
  OpenRA.Mods.Common/Scripting/ScriptEmmyTypeOverrideAttribute.cs
  OpenRA.Mods.Common/UtilityCommands/ExtractEmmyLuaAPI.cs
  mods/d2k/maps/atreides-01a/atreides01a.lua
  mods/d2k/maps/atreides-01b/atreides01b.lua
  mods/d2k/maps/atreides-03a/atreides03a.lua
  mods/d2k/maps/atreides-03b/atreides03b.lua
  mods/d2k/maps/harkonnen-01a/harkonnen01a.lua
  mods/d2k/maps/harkonnen-01b/harkonnen01b.lua
  mods/d2k/maps/ordos-01a/ordos01a.lua
  mods/d2k/maps/ordos-01b/ordos01b.lua
Labels: PR: Unaddressed comment(s)

#21356 Implement Stream.Read(Span<byte>) overloads.
  OpenRA.Game/Primitives/MergedStream.cs
  OpenRA.Game/Primitives/ReadOnlyAdapterStream.cs
  OpenRA.Game/Primitives/SegmentStream.cs
  OpenRA.Mods.Cnc/AudioLoaders/VocLoader.cs
  OpenRA.Mods.Common/AudioLoaders/OggLoader.cs
Labels: PR: Needs +2

#21522 Fix editor crash from added mission fencing
  mods/ra/maps/allies-05b/map.yaml
  mods/ra/maps/fall-of-greece-1-personal-war/map.yaml
  mods/ra/maps/soviet-09/map.yaml
Labels: PR: Needs +2

#21390 Add a more helpful crash on missing frames
  OpenRA.Game/Graphics/SpriteCache.cs
Labels: PR: Needs +2, PR: Unaddressed comment(s)

#21492 Fix map update with incompatible ZIP extra data
  OpenRA.Game/FileSystem/ZipFile.cs
Labels: PR: Needs +2

#21523 Update macOS runner
  .github/workflows/packaging.yml
Labels: PR: Needs +2

#21520 Fix TFD asset installation.
  mods/cnc/installer/firstdecade.yaml
  mods/ra/installer/firstdecade.yaml
  mods/ts/installer/firstdecade.yaml
Labels: PR: Needs +2

#21568 Allow more than 32 terrain types
  OpenRA.Mods.Common/Traits/World/Locomotor.cs
Labels: PR: Needs +2

#21569 Fixed a crash in RallyPointOrderTargeter.CanTarget
  OpenRA.Mods.Common/Traits/Buildings/RallyPoint.cs
Labels: PR: Needs +2
