Repository OpenRA/OpenRA, pull requests merged in 2024-03, with the labels that each got.

#21243 Add navy orders, fixes to Soviet 06b
  mods/ra/maps/soviet-06a/soviet06a.lua
  mods/ra/maps/soviet-06b/map.yaml
  mods/ra/maps/soviet-06b/soviet06b-AI.lua
  mods/ra/maps/soviet-06b/soviet06b-reinforcements_teams.lua
  mods/ra/maps/soviet-06b/soviet06b.lua
Labels: PR: Needs +2

#21255 ActorMoveBrush for Editor
  OpenRA.Mods.Common/EditorBrushes/EditorDefaultBrush.cs
  OpenRA.Mods.Common/Traits/World/EditorActorPreview.cs
  OpenRA.Mods.Common/Traits/World/EditorCursorLayer.cs
  mods/common/languages/en.ftl
Labels: PR: Changes requested

#21363 Improve sheet packing.
  OpenRA.Game/Graphics/SpriteCache.cs
Labels: PR: Unaddressed comment(s)

#21265 Add unique beacon and join/leave/change sounds in lobby
  mods/d2k/audio/notifications.yaml
  mods/d2k/bits/CHAT1REVERSE.WAV
  mods/d2k/metrics.yaml
Labels: PR: Unaddressed comment(s)

#21360 Improve BotModule performance.
  OpenRA.Mods.Common/AIUtils.cs
  OpenRA.Mods.Common/ActorIndex.cs
  OpenRA.Mods.Common/Traits/BotModules/BaseBuilderBotModule.cs
  OpenRA.Mods.Common/Traits/BotModules/BotModuleLogic/BaseBuilderQueueManager.cs
  OpenRA.Mods.Common/Traits/BotModules/CaptureManagerBotModule.cs
  OpenRA.Mods.Common/Traits/BotModules/HarvesterBotModule.cs
  OpenRA.Mods.Common/Traits/BotModules/McvManagerBotModule.cs
  OpenRA.Mods.Common/Traits/BotModules/SquadManagerBotModule.cs
  OpenRA.Mods.Common/Traits/BotModules/UnitBuilderBotModule.cs
Labels: PR: Needs +2

#21354 Fix map editor not removing an actor properly.
  OpenRA.Mods.Common/Traits/World/EditorActorPreview.cs
  OpenRA.Mods.Common/Widgets/Logic/Editor/ActorEditLogic.cs
  mods/common/languages/en.ftl
Labels: PR: Fixup requested
