Repository OpenRA/OpenRA, pull requests merged in 2024-01, with the labels that each got.

#21252 adds Hovers WorldVisualOffset to muzzle calculations
  OpenRA.Mods.Common/Traits/Armament.cs
  OpenRA.Mods.Common/Traits/Render/Hovers.cs
Labels: PR: Unaddressed comment(s)

#21225 Task #20918 (Improve PNG filesize on save)
  OpenRA.Game/FileFormats/Png.cs
  OpenRA.Test/OpenRA.Game/PngTest.cs
Labels: PR: Fixup requested

#21292 Fix smudges incorrectly generating on slopes
  OpenRA.Mods.Common/Traits/World/SmudgeLayer.cs
Labels: PR: Needs +2

#21271 Adds tilting on slopes to suitable actor previews
  OpenRA.Mods.Common/ActorInitializer.cs
  OpenRA.Mods.Common/Graphics/ActorPreview.cs
  OpenRA.Mods.Common/Traits/World/EditorActorPreview.cs
Labels: PR: Fixup requested

#21246 Add IsDead/aircraft checks to Soviet 11
  mods/ra/maps/soviet-11a/map.yaml
  mods/ra/maps/soviet-11a/soviet11a-AI.lua
  mods/ra/maps/soviet-11b/soviet11b-AI.lua
Labels: PR: Needs +2

#21311 Use HashSets instead of .Distinct
  OpenRA.Mods.Cnc/UtilityCommands/LegacyTilesetImporter.cs
  OpenRA.Mods.Common/Scripting/Properties/ProductionProperties.cs
  OpenRA.Mods.Common/Traits/SupportPowers/GrantExternalConditionPower.cs
  OpenRA.Mods.Common/UtilityCommands/ExtractEmmyLuaAPI.cs
  OpenRA.Mods.Common/Widgets/Logic/Installation/ModContentLogic.cs
  OpenRA.Mods.D2k/Activities/SwallowActor.cs
Labels: PR: Needs +2

#21261 Store ICrushable traits as actor field.
  OpenRA.Game/Actor.cs
  OpenRA.Game/Traits/TraitsInterfaces.cs
  OpenRA.Mods.Common/Pathfinder/HierarchicalPathFinder.cs
  OpenRA.Mods.Common/Traits/Air/Aircraft.cs
  OpenRA.Mods.Common/Traits/AutoCrusher.cs
  OpenRA.Mods.Common/Traits/Crushable.cs
  OpenRA.Mods.Common/Traits/Husk.cs
  OpenRA.Mods.Common/Traits/Mobile.cs
  OpenRA.Mods.Common/Traits/World/Locomotor.cs
  OpenRA.Mods.Common/TraitsInterfaces.cs
Labels: PR: Needs +2
