Repository OpenRA/OpenRA, pull requests merged in 2025-01, with the labels that each got.

#21624 Allow maps to override the player viewport size.
  OpenRA.Game/Graphics/Viewport.cs
  OpenRA.Mods.Common/Traits/World/MapOptions.cs
Labels: PR: Needs +2

#21636 Avoid unit continuing to follow the unattackable target around
  OpenRA.Mods.Common/Activities/Air/FlyAttack.cs
  OpenRA.Mods.Common/Activities/Attack.cs
  OpenRA.Mods.Common/Traits/Attack/AttackFollow.cs
Labels: PR: Needs +2

#21694 Added link to GH source code to online documentation
  packaging/format-docs.py
Labels: PR: Changes requested

#21724 Fix some campaign Fluent keys
  mods/d2k/fluent/lua.ftl
  mods/ra/fluent/campaign.ftl
  mods/ra/fluent/lua.ftl
  mods/ra/maps/allies-08a/allies08a.lua
  mods/ra/maps/allies-08b/allies08b.lua
  mods/ra/maps/sarin-gas-2-down-under/rules.yaml
Labels: PR: For stable

#21722 D2k shellmap: Hide pickup indicators
  mods/d2k/maps/shellmap/rules.yaml
Labels: PR: Needs +2
