Repository OpenRA/OpenRA, pull requests merged in 2025-04, with the labels that each got.

#21827 Fix PBOG offset not accounting for zoom.
  OpenRA.Mods.Common/Orders/PlaceBuildingOrderGenerator.cs
Labels: PR: Unaddressed comment(s)

#21826 Use the TerrainRenderer for rendering template-based bridges.
  OpenRA.Mods.Common/Traits/Buildings/Bridge.cs
Labels: PR: Unaddressed comment(s)

#21832 Silence IDE0290.
  .editorconfig
  OpenRA.Game/FieldLoader.cs
  OpenRA.Game/Graphics/Model.cs
  OpenRA.Game/Graphics/PlatformInterfaces.cs
  OpenRA.Game/Graphics/RenderPostProcessPassVertex.cs
  OpenRA.Game/Graphics/ShaderBindings.cs
  OpenRA.Game/Input/IInputHandler.cs
  OpenRA.Game/Map/ActorInitializer.cs
  OpenRA.Game/Map/TileReference.cs
  OpenRA.Game/MiniYaml.cs
  OpenRA.Game/PlayerProfile.cs
  OpenRA.Game/Scripting/ScriptContext.cs
  OpenRA.Game/Sound/SoundDevice.cs
  OpenRA.Game/Support/Benchmark.cs
  OpenRA.Game/Support/Log.cs
  OpenRA.Game/Traits/LintAttributes.cs
  OpenRA.Game/Traits/Player/Shroud.cs
  OpenRA.Game/Traits/TraitsInterfaces.cs
  OpenRA.Game/Traits/World/ScreenMap.cs
  OpenRA.Game/Widgets/Widget.cs
  OpenRA.Game/World.cs
  OpenRA.Mods.Cnc/FileFormats/VxlReader.cs
  OpenRA.Mods.Cnc/Traits/Chronoshiftable.cs
  OpenRA.Mods.Common/ActorInitializer.cs
  OpenRA.Mods.Common/EditorBrushes/EditorBlit.cs
  OpenRA.Mods.Common/EditorBrushes/EditorResourceBrush.cs
  OpenRA.Mods.Common/EditorBrushes/EditorTileBrush.cs
  OpenRA.Mods.Common/FileFormats/InstallShieldCABCompression.cs
  OpenRA.Mods.Common/FileSystem/InstallShieldPackage.cs
  OpenRA.Mods.Common/Graphics/DefaultSpriteSequence.cs
  OpenRA.Mods.Common/Lint/CheckChromeHotkeys.cs
  OpenRA.Mods.Common/Orders/UnitOrderGenerator.cs
  OpenRA.Mods.Common/Scripting/ScriptEmmyTypeOverrideAttribute.cs
  OpenRA.Mods.Common/Terrain/DefaultTileCache.cs
  OpenRA.Mods.Common/Traits/Conditions/ExternalCondition.cs
  OpenRA.Mods.Common/Traits/Demolishable.cs
  OpenRA.Mods.Common/Traits/LintAttributes.cs
  OpenRA.Mods.Common/Traits/Modifiers/FrozenUnderFog.cs
  OpenRA.Mods.Common/Traits/SupportPowers/SelectDirectionalTarget.cs
  OpenRA.Mods.Common/Traits/World/Locomotor.cs
  OpenRA.Mods.Common/Traits/World/MarkerLayerOverlay.cs
  OpenRA.Mods.Common/Traits/World/ResourceLayer.cs
  OpenRA.Mods.Common/Traits/World/ShroudRenderer.cs
  OpenRA.Mods.Common/Traits/World/TerrainLighting.cs
  OpenRA.Mods.Common/Traits/World/WarheadDebugOverlay.cs
  OpenRA.Mods.Common/UtilityCommands/ExtractChromeStrings.cs
  OpenRA.Mods.Common/UtilityCommands/ExtractYamlStrings.cs
  OpenRA.Mods.Common/Widgets/LineGraphWidget.cs
  OpenRA.Mods.Common/Widgets/Logic/Editor/ActorSelectorLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Editor/SaveMapLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Lobby/LobbyUtils.cs
  OpenRA.Mods.D2k/PackageLoaders/D2kSoundResources.cs
Labels: PR: Needs +2

#21839 MiniYaml applies removal during merging as well as inheritance.
  OpenRA.Game/MiniYaml.cs
  OpenRA.Test/OpenRA.Game/MiniYamlTest.cs
Labels: PR: Needs +2

#21836 Fix incorrect tile definition
  mods/cnc/tilesets/winter.yaml
Labels: PR: Needs +2

#21834 Add SoundFX for Ornibomb, Devastator meltdown and Saboteur
  mods/d2k/bits/DEVASTATORMELTDOWN.WAV
  mods/d2k/bits/ORNIBOMB.WAV
  mods/d2k/rules/arrakis.yaml
  mods/d2k/rules/defaults.yaml
  mods/d2k/rules/infantry.yaml
  mods/d2k/rules/vehicles.yaml
  mods/d2k/weapons/other.yaml
Labels: PR: Needs +2

#21846 Use MultiBrush as the input and output of TilingPath
  OpenRA.Mods.Common/MapGenerator/MultiBrush.cs
  OpenRA.Mods.Common/MapGenerator/TilingPath.cs
  OpenRA.Mods.Common/Terrain/DefaultTerrain.cs
  OpenRA.Mods.Common/Terrain/TemplateSegment.cs
  OpenRA.Mods.Common/Terrain/TerrainInfo.cs
  OpenRA.Mods.Common/Traits/World/ExperimentalMapGenerator.cs
  mods/cnc/tilesets/desert.yaml
  mods/cnc/tilesets/snow.yaml
  mods/cnc/tilesets/temperat.yaml
  mods/cnc/tilesets/winter.yaml
  mods/ra/tilesets/desert.yaml
  mods/ra/tilesets/snow.yaml
  mods/ra/tilesets/temperat.yaml
Labels: PR: Needs +2

#21759 Initialise VertexBuffers immediately
  OpenRA.Game/Graphics/PlatformInterfaces.cs
  OpenRA.Game/Graphics/TerrainSpriteLayer.cs
  OpenRA.Game/Renderer.cs
  OpenRA.Mods.Cnc/Graphics/VoxelLoader.cs
  OpenRA.Mods.Cnc/Traits/World/ChronoVortexRenderer.cs
  OpenRA.Mods.Common/Traits/World/RenderPostProcessPassBase.cs
  OpenRA.Mods.D2k/Traits/World/SonicBlastRenderer.cs
  OpenRA.Platforms.Default/Sdl2GraphicsContext.cs
  OpenRA.Platforms.Default/ThreadedGraphicsContext.cs
  OpenRA.Platforms.Default/VertexBuffer.cs
Labels: PR: Needs +2

#21370 Don't allocate empty sheets
  OpenRA.Game/Graphics/CursorManager.cs
  OpenRA.Game/Graphics/SheetBuilder.cs
  OpenRA.Game/Graphics/SpriteCache.cs
  OpenRA.Game/Map/MapCache.cs
  OpenRA.Mods.Cnc/Graphics/VoxelLoader.cs
  OpenRA.Mods.Common/Terrain/DefaultTileCache.cs
Labels: PR: Needs +2, PR: Is Dependency

#21729 Improve HD sheet creation
  OpenRA.Game/FileFormats/Png.cs
  OpenRA.Mods.Common/UtilityCommands/DumpSequenceSheetsCommand.cs
Labels: PR: Needs +2

#21869 Require map generators to specify valid tilesets.
  OpenRA.Mods.Common/Traits/World/ClearMapGenerator.cs
  OpenRA.Mods.Common/Traits/World/ExperimentalMapGenerator.cs
  OpenRA.Mods.Common/TraitsInterfaces.cs
  OpenRA.Mods.Common/Widgets/Logic/Editor/MapToolsLogic.cs
  mods/cnc/rules/map-generators.yaml
  mods/ra/rules/map-generators.yaml
Labels: PR: Is Dependency

#21870 Move map installed check to LobbyLogic.
  OpenRA.Game/Map/MapPreview.cs
  OpenRA.Mods.Common/Widgets/Logic/Lobby/LobbyLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Lobby/MapPreviewLogic.cs
Labels: PR: Is Dependency

#21871 Dynamically populate map chooser tabs.
  OpenRA.Mods.Common/Widgets/Logic/MapChooserLogic.cs
  mods/cnc/chrome/mapchooser.yaml
  mods/cnc/fluent/chrome.ftl
  mods/common/chrome/map-chooser.yaml
  mods/common/fluent/chrome.ftl
  mods/common/fluent/common.ftl
Labels: PR: Is Dependency

#21868 Prevent remote map searches overwriting local or generated state.
  OpenRA.Game/Map/MapCache.cs
  OpenRA.Game/Map/MapPreview.cs
Labels: PR: Is Dependency

#21860 Fix invalid CachedTransform uses of MapPreview.
  OpenRA.Mods.Common/Widgets/Logic/Lobby/MapPreviewLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/ServerListLogic.cs
Labels: PR: Is Dependency

#21814 DockClientManager: enter cursor per DockHost's DockType
  OpenRA.Mods.Common/Traits/Buildings/TransformsIntoDockClientManager.cs
  OpenRA.Mods.Common/Traits/DockClientManager.cs
Labels: PR: Fixup requested
