Repository OpenRA/OpenRA, pull requests merged in 2025-02, with the labels that each got.

#21736 Match the squad check inside .CenterPosition
  OpenRA.Mods.Common/Traits/BotModules/Squads/Squad.cs
Labels: PR: For stable

#21743 Update SDL to 2.32.0
  OpenRA.Platforms.Default/OpenRA.Platforms.Default.csproj
  OpenRA.WindowsLauncher/OpenRA.WindowsLauncher.csproj
Labels: PR: Needs +2, PR: For stable

#21742 Fix a bad comparison against Target.Invalid.
  OpenRA.Mods.Common/Traits/BotModules/HarvesterBotModule.cs
Labels: PR: For stable

#21746 Run spell check over solution.
  OpenRA.Game/Graphics/Sheet.cs
  OpenRA.Game/Primitives/RingBuffer.cs
  OpenRA.Game/Settings.cs
  OpenRA.Game/Support/MersenneTwister.cs
  OpenRA.Mods.Cnc/SpriteLoaders/ShpTDLoader.cs
  OpenRA.Mods.Cnc/Traits/Attack/AttackTesla.cs
  OpenRA.Mods.Common/Activities/PickupUnit.cs
  OpenRA.Mods.Common/MapGenerator/MatrixUtils.cs
  OpenRA.Mods.Common/MapGenerator/TilingPath.cs
  OpenRA.Mods.Common/Pathfinder/HierarchicalPathFinder.cs
  OpenRA.Mods.Common/Traits/BotModules/BotModuleLogic/MinelayerBotModule.cs
  OpenRA.Mods.Common/Traits/Conditions/GrantChargedConditionOnToggle.cs
  OpenRA.Mods.Common/Traits/Conditions/ProximityExternalCondition.cs
  OpenRA.Mods.Common/Traits/DockClientManager.cs
  OpenRA.Mods.Common/Traits/Player/ProductionQueue.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20230225/RenameContrailWidth.cs
  OpenRA.Mods.Common/UpdateRules/Rules/20231010/RemoveParentTopParentLeftSubstitutions.cs
  OpenRA.Mods.Common/Widgets/Logic/Ingame/ScriptErrorLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Settings/GamePlaySettingsLogic.cs
  OpenRA.Mods.Common/Widgets/WorldInteractionControllerWidget.cs
Labels: PR: Needs +2

#21741 Annotate campaign.lua
  mods/cnc/scripts/campaign.lua
  mods/d2k/scripts/campaign.lua
  mods/ra/scripts/campaign.lua
Labels: PR: Needs +2

#21691 Allow passing map author as an argument
  OpenRA.Mods.Cnc/UtilityCommands/ImportGen1MapCommand.cs
  OpenRA.Mods.Cnc/UtilityCommands/ImportGen2MapCommand.cs
  OpenRA.Mods.Cnc/UtilityCommands/ImportRedAlertMapCommand.cs
  OpenRA.Mods.Cnc/UtilityCommands/ImportTiberianDawnMapCommand.cs
  OpenRA.Mods.Cnc/UtilityCommands/ImportTiberianSunMapCommand.cs
Labels: PR: Needs +2

#21745 Enable Net 7 and Net 8 style rules.
  .editorconfig
  OpenRA.Game/CryptoUtil.cs
  OpenRA.Game/FileFormats/ReplayMetadata.cs
  OpenRA.Game/FluentBundle.cs
  OpenRA.Game/GameInformation.cs
  OpenRA.Game/Graphics/Model.cs
  OpenRA.Game/Primitives/ActionQueue.cs
  OpenRA.Game/Primitives/ActorInfoDictionary.cs
  OpenRA.Game/Primitives/Cache.cs
  OpenRA.Game/Primitives/ConcurrentCache.cs
  OpenRA.Game/Primitives/ReadOnlyAdapterStream.cs
  OpenRA.Game/Primitives/RingBuffer.cs
  OpenRA.Game/Primitives/SegmentStream.cs
  OpenRA.Game/Scripting/ScriptMemberWrapper.cs
  OpenRA.Game/Sound/Sound.cs
  OpenRA.Mods.Cnc/SpriteLoaders/ShpTDLoader.cs
  OpenRA.Mods.Common/EditorBrushes/EditorMarkerLayerBrush.cs
  OpenRA.Mods.Common/FileFormats/WavReader.cs
  OpenRA.Mods.Common/FileSystem/DefaultFileSystemLoader.cs
  OpenRA.Mods.Common/ItchIntegration.cs
  OpenRA.Mods.Common/Lint/CheckFluentReferences.cs
  OpenRA.Mods.Common/Lint/CheckSequences.cs
  OpenRA.Mods.Common/Lint/CheckTraitLocation.cs
  OpenRA.Mods.Common/Scripting/Global/TriggerGlobal.cs
  OpenRA.Mods.Common/Scripting/ScriptTriggers.cs
  OpenRA.Mods.Common/ServerTraits/SkirmishLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Editor/SaveMapLogic.cs
  OpenRA.Mods.Common/Widgets/Logic/Ingame/ObserverStatsLogic.cs
  OpenRA.Mods.Common/Widgets/TextFieldWidget.cs
  OpenRA.Test/OpenRA.Game/CoordinateTest.cs
  OpenRA.Test/OpenRA.Game/VariableExpressionTest.cs
Labels: PR: Needs +2

#21750 Adjust to a 4 space standard
  OpenRA.Mods.Common/UtilityCommands/ExtractChromeStrings.cs
  OpenRA.Mods.Common/UtilityCommands/ExtractYamlStrings.cs
  mods/cnc/fluent/campaign.ftl
  mods/cnc/fluent/chrome.ftl
  mods/cnc/fluent/rules.ftl
  mods/common/fluent/chrome.ftl
  mods/d2k/fluent/campaign.ftl
  mods/d2k/fluent/chrome.ftl
  mods/d2k/fluent/rules.ftl
  mods/ra/fluent/campaign.ftl
  mods/ra/fluent/chrome.ftl
  mods/ra/fluent/lua.ftl
  mods/ra/fluent/rules.ftl
  mods/ra/maps/bomber-john/map.ftl
  mods/ra/maps/fort-lonestar/map.ftl
  mods/ra/maps/top-o-the-world/map.ftl
  mods/ts/fluent/chrome.ftl
  mods/ts/fluent/rules.ftl
  mods/ts/maps/sunstroke/map.ftl
Labels: PR: Needs +2, PR: For stable

#21756 Sanitize saved skirmish factions.
  OpenRA.Mods.Common/ServerTraits/LobbyCommands.cs
  OpenRA.Mods.Common/ServerTraits/SkirmishLogic.cs
  mods/common/fluent/common.ftl
Labels: PR: For stable

#21763 Fix soviet-06 harvester production crash
  mods/ra/maps/soviet-06a/soviet06a-AI.lua
  mods/ra/maps/soviet-06b/soviet06b-AI.lua
Labels: PR: For stable

#21769 Fix .NET 6 CI false positives.
  .github/workflows/ci.yml
Labels: PR: For stable
