Repository OpenRA/OpenRA, pull requests merged in 2025-05, with the labels that each got.

#21877 Polish map generator settings.
  mods/cnc/fluent/rules.ftl
  mods/cnc/rules/map-generators.yaml
  mods/ra/fluent/rules.ftl
  mods/ra/rules/map-generators.yaml
Labels: PR: Is Dependency

#21900 Fix trike stuck
  mods/d2k/rules/vehicles.yaml
  mods/d2k/sequences/vehicles.yaml
  mods/d2k/weapons/smallguns.yaml
Labels: PR: Needs +2

#21904 Add path auto-tiling tool to map editor
  OpenRA.Mods.Common/EditorBrushes/EditorBlit.cs
  OpenRA.Mods.Common/EditorBrushes/EditorTilingPathBrush.cs
  OpenRA.Mods.Common/MapGenerator/CellLayerUtils.cs
  OpenRA.Mods.Common/MapGenerator/Direction.cs
  OpenRA.Mods.Common/MapGenerator/MultiBrush.cs
  OpenRA.Mods.Common/MapGenerator/TilingPath.cs
  OpenRA.Mods.Common/Traits/World/EditorActorPreview.cs
  OpenRA.Mods.Common/Traits/World/TerrainRenderer.cs
  OpenRA.Mods.Common/Traits/World/TilingPathTool.cs
  OpenRA.Mods.Common/TraitsInterfaces.cs
  OpenRA.Mods.Common/Widgets/Logic/Editor/TilingPathToolLogic.cs
  mods/cnc/chrome/editor.yaml
  mods/cnc/fluent/chrome.ftl
  mods/cnc/rules/map-generators.yaml
  mods/cnc/rules/world.yaml
  mods/cnc/tilesets/desert.yaml
  mods/cnc/tilesets/snow.yaml
  mods/cnc/tilesets/temperat.yaml
  mods/cnc/tilesets/winter.yaml
  mods/common/chrome/editor.yaml
  mods/common/fluent/chrome.ftl
  mods/common/fluent/common.ftl
  mods/ra/fluent/chrome.ftl
  mods/ra/rules/map-generators.yaml
  mods/ra/rules/world.yaml
  mods/ra/tilesets/desert.yaml
  mods/ra/tilesets/snow.yaml
  mods/ra/tilesets/temperat.yaml
Labels: PR: Fixup requested

#21784 Add The Tiberium Strain (CnC, scb31ea)
  mods/cnc/fluent/lua.ftl
  mods/cnc/maps/the-tiberium-strain/map.bin
  mods/cnc/maps/the-tiberium-strain/map.png
  mods/cnc/maps/the-tiberium-strain/map.yaml
  mods/cnc/maps/the-tiberium-strain/rules.yaml
  mods/cnc/maps/the-tiberium-strain/the-tiberium-strain.lua
  mods/cnc/missions.yaml
Labels: PR: Needs +2

#21905 Preview clipboard when copy-pasting in the map editor
  OpenRA.Mods.Common/EditorBrushes/EditorBlit.cs
  OpenRA.Mods.Common/EditorBrushes/EditorCopyPasteBrush.cs
Labels: PR: Changes requested
