Repository OpenRA/OpenRA, pull requests merged in 2025-03, with the labels that each got.

#21782 Add civilian idle sequences
  mods/cnc/rules/civilian.yaml
  mods/cnc/rules/defaults.yaml
  mods/cnc/sequences/civilian.yaml
  mods/ra/rules/defaults.yaml
  mods/ra/sequences/infantry.yaml
Labels: PR: Fixup requested

#21801 Fix wrong frame reference on 1141 tile in arrakis tileset
  mods/d2k/tilesets/arrakis.yaml
Labels: PR: For stable

#21792 Fix tree husks on jungle tileset
  mods/cnc/sequences/decorations.yaml
Labels: PR: Needs +2, PR: For stable

#21802 Fix a potential crash when cancelling capture
  OpenRA.Mods.Common/Activities/CaptureActor.cs
  OpenRA.Mods.Common/Traits/CaptureManager.cs
Labels: PR: Needs +2, PR: For stable

#21785 Harvesters prefer ore near to the refinery.
  OpenRA.Mods.Common/Activities/FindAndDeliverResources.cs
Labels: PR: Needs +2, PR: For stable

#21809 Fix green glitch in crush anim in d2k mod
  mods/d2k/sequences/infantry.yaml
Labels: PR: Needs +2, PR: For stable

#21805 Avoid a thirdparty action to upload releases
  .github/workflows/packaging.yml
Labels: PR: For stable

#21783 Add explosion effects to RA bridges
  mods/ra/rules/civilian.yaml
  mods/ra/rules/defaults.yaml
  mods/ra/weapons/explosions.yaml
Labels: PR: Needs +2

#21813 Work around Raspberry Pi GLSL bug.
  glsl/combined.frag
Labels: PR: For stable

#21810 Fix wrong Spread on some Warheads
  mods/d2k/weapons/debris.yaml
  mods/d2k/weapons/largeguns.yaml
  mods/d2k/weapons/missiles.yaml
  mods/d2k/weapons/other.yaml
Labels: PR: Needs +2, PR: For stable

#21432 SonicBlast projectile
  OpenRA.Mods.D2k/Projectiles/SonicBlast.cs
  mods/d2k/weapons/other.yaml
Labels: PR: Needs +2

#21819 Fix camera being in an incorrect position of first frame
  mods/d2k/maps/shellmap/d2k-shellmap.lua
Labels: PR: Needs +2, PR: For stable

#21798 Add missing dispose calls
  OpenRA.Mods.Cnc/Traits/World/ChronoVortexRenderer.cs
  OpenRA.Mods.Common/Traits/World/RenderPostProcessPassBase.cs
  OpenRA.Mods.Common/Widgets/ColorMixerWidget.cs
  OpenRA.Mods.Common/Widgets/HueSliderWidget.cs
  OpenRA.Mods.Common/Widgets/Logic/EncyclopediaLogic.cs
  OpenRA.Mods.Common/Widgets/VideoPlayerWidget.cs
Labels: PR: Needs +2, PR: For stable

#21791 Fix rallypoints not showing full target lines
  OpenRA.Mods.Common/Traits/Air/Aircraft.cs
  OpenRA.Mods.Common/Traits/Mobile.cs
Labels: PR: Needs +2, PR: For stable

#21820 Fix resource calculation
  OpenRA.Mods.Common/Traits/World/EditorResourceLayer.cs
  OpenRA.Mods.Common/Traits/World/ResourceLayer.cs
Labels: PR: Needs +2, PR: For stable

#21686 Add sound to capturable blink
  OpenRA.Mods.Common/Traits/CapturableProgressBlink.cs
Labels: PR: Needs +2

#21828 Fix custom bot names being untranslated in lobby
  OpenRA.Mods.Common/Widgets/Logic/Lobby/LobbyUtils.cs
Labels: PR: For stable

#21831 Increase perf for parsing remote maps
  OpenRA.Game/Map/MapCache.cs
Labels: PR: Needs +2, PR: For stable
